### ISSUE TITLE
Allow running as root using explicit parameter

### ISSUE THREAD

**Issue by webwurst** [yeoman/yo#101]
Most time i am using [Docker](http://docs.docker.io/en/latest/examples/) for quick tests of new software. For the sake of convinience i just install and run everything there as root and throw away the container later.

It would be nice if yo could allow beeing executed as root like bower [does](https://github.com/bower/bower/issues/498).

**Comment by sindresorhus** [comment]
Good news. `yo` will no longer block sudo when run inside a docker container :)

https://github.com/sindresorhus/sudo-block/commit/ee9cb78e4cc2bd186ae750e930e0ab7061d8420f

**Comment by addyosmani** [comment]
:+1:
