### ISSUE TITLE
yoyo can't find generators after installing

### ISSUE THREAD

**Issue by stephenplusplus** [yeoman/yo#120]
Just did a fresh nvm install of v0.10.24, installed `yo`, and had this experience:

``` bash
$ yo
[?] What would you like to do? Install a generator
[?] Search NPM for generators: angular
[?] Here's what I found. Install one? generator-angular
-- npm logs --
I just installed your generator by running:

    npm install -g generator-angular

[?] What would you like to do? (Use arrow keys)
❯ Install a generator
  Find some help
  Get me out of here!
```

So, the list didn't detect I installed a new generator.

I then ran, `yo` again and Angular and Karma were there. I decided to test again...

```
[?] What would you like to do? Install a generator
[?] Search NPM for generators: backbone
[?] Here's what I found. Install one? generator-backbone
-- npm logs --
I just installed your generator by running:

    npm install -g generator-backbone

[?] What would you like to do? (Use arrow keys)
❯ Install a generator
  Find some help
  Get me out of here!
```

So, the list completed emptied itself; it didn't even show that I had Angular and Karma.

**Comment by thespacecadette** [comment]
Had the same issue, had to create a system variable called NODE_PATH and added my node path to it.

**Comment by bretonio** [comment]
I found that closing the terminal session and opening a new one did the trick. The options I installed were listed now. Go figure.
