### ISSUE TITLE
Add ability to remove a scaffold

### ISSUE THREAD

**Issue by MattFriedman** [yeoman/yo#124]
I believe this has been raised before but closed. 

I would like to be able to reverse a scaffold action. 

Use cases: 
- I made a typo and I want to easily reverse my scaffolding action
- I changed my mind about the architecture. I created a service and later discovered it should have been a provider instead. 

If I do:

```
yo angular:service nanner
```

I'd like to be able to:

```
yo angular:service -rm nanner
```

So that I can:

```
yo angular:provider banana
```

Thanks!

**Comment by vladyn** [comment]
+1 from me

**Comment by bokeyy** [comment]
+1

**Comment by tille** [comment]
I feel it's not handle at all by the use of version control, there might be a way to undo possible error situations as running `yo webapp` in my main codes folder as I did.

For clear reasons I have not versioned the entire folder so version control didn't come to the rescue.

P.S. 
Syntax pointed by @maksimr sounds pretty natural by the way. 

Thanks!
