### ISSUE TITLE
Install Script Issues

### ISSUE THREAD

**Issue by BillKracke** [yeoman/yo#138]
I have seen issue 128 & 129, tried the solutions there, and I still get the same problem.  

npm i -g yo  yields this:

> yo@1.1.2 postinstall /usr/local/lib/node_modules/yo
> node ./scripts/doctor

sh: node: command not found
npm ERR! yo@1.1.2 postinstall: `node ./scripts/doctor`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the yo@1.1.2 postinstall script.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/doctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.0.0
npm ERR! command "node" "/usr/local/bin/npm" "i" "-g" "yo"
npm ERR! cwd /Users/billkracke/Dropbox/sites/clients/mission_coffee
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.24
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/billkracke/Dropbox/sites/clients/mission_coffee/npm-debug.log
npm ERR! not ok code 0

I cannot install

**Comment by junibrosas** [comment]
@juliancantillo `s answer solved my problem using windows 8.1. Install the source code, cd to the folder, remove the script then run npm i -g.
