### ISSUE TITLE
Yo command is not recognized for windows 8

### ISSUE THREAD

**Issue by icebergdelphi** [yeoman/yo#201]
Hi,i installed yeoman and then npm install -g generator-angular and everything is fine, but when i write : yo angular an error rise in the command window: Yo is not recognized as internal or external command.

What is the problem? thank you.

**Comment by pogakudilip** [comment]
I am also facing the same problem could you please provide detailed information to fix the problem

Thanks in advance

**Comment by kevva** [comment]
There are steps to fix it in the linked issue.
