### ISSUE TITLE
Cannot install yeoman 'Failed at the yo@1.3.0 postinstall script'

### ISSUE THREAD

**Issue by andrewbarsoum** [yeoman/yo#213]
Hi, 

When I run 'npm install -g yo' I get the following error message. 

I've reinstalled node.js and have been able to install other applications like brunch but can't get yo to work. 

I'm on a Windows 7 machine. 

Any ideas would be very welcome. 

Thanks, 

Andrew

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Andrew>npm install -g yo
C:\Users\Andrew\AppData\Roaming\npm\yo -> C:\Users\Andrew\AppData\Roaming\npm\no
de_modules\yo\cli.js

> yo@1.3.0 postinstall C:\Users\Andrew\AppData\Roaming\npm\node_modules\yo
> node ./scripts/doctor

npm ERR! yo@1.3.0 postinstall: `node ./scripts/doctor`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the yo@1.3.0 postinstall script.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/doctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "yo"
npm ERR! cwd C:\Users\Andrew
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! syscall spawn
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! not ok code 0

C:\Users\Andrew>

**Comment by xtphty** [comment]
I'm seeing this issue on Windows again.  Npm install fails on "post install script failed" with the error
`yodoctor is not recognized as an internal or external command,
operable program or batch file.`

I noticed that yodoctor is not on my path after installing yo (using npm install -g yo).  Yo is available in C:\Users\<user>\AppData\Roaming\npm, however the yodoctor binary is in C:\Users\<user>\AppData\Roaming\npm\node_modules\yo\node_modules\.bin

Is this a problem with my PATH configuration or should the yo installation?

**Comment by SBoudrias** [comment]
@xtphty This is not an issue with your path, `npm` scripts are run from the local .bin folder - you shouldn't add it to your path. Maybe open an issue on npm and see what they have to say about it.

**Comment by sindresorhus** [comment]
Make sure you're on latest npm version. This is an npm issue and has nothing to do with Yeoman.

https://github.com/npm/npm/wiki/Troubleshooting#upgrading-on-windows
