### ISSUE TITLE
Update notification doesn't go away

### ISSUE THREAD

**Issue by cfjedimaster** [yeoman/yo#214]
I ran yo, noticed I had updates for generators, and told the CLI to update. It said it did, but when the menu was displayed again they were still marked with the old versions and had the 'update available' text by them. I had to quit yo and rerun it.

**Comment by petereberlecom** [comment]
I tried to reproduce this issue but it didn't worked. Maybe it's already fixed :wink:

**Comment by SBoudrias** [comment]
I'll close as the issue is very old and might already be fixed. Feel free to reopen if that's still an issue.
