### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by hemanth** [yeoman/yo#222]
With `n` number of generators installed to access a particular one with the current workflow, one must execute the `yo` command first and then select the required from the list of installed or recall the name.

Will it be more useful to have tab completion here? 

Will it be feasible to have such an implementation?

Say for example:

```
$ yo ang<tab> 
# Should auto complete to angular and related if they are installed.
```

//cc @yeoman/yeoman-core 

-

Earlier issue https://github.com/yeoman/yeoman/issues/357

**Comment by chovy** [comment]
+1 for tab completion on yeoman prompts.

**Comment by JavaTheHood** [comment]
+1

**Comment by SBoudrias** [comment]
Big thanks @mklabs for sending an amazing PR!

**Comment by hemanth** [comment]
Nice! @mklabs is back, I recall us doing the tab completion for bower!
