### ISSUE TITLE
Yo cannot run in docker

### ISSUE THREAD

**Issue by Colin-Murphy** [yeoman/yo#230]
I am trying to run generator-angular within a docker container in a project and I have run into the error of it telling me not to be sudo. According to https://github.com/yeoman/yo/issues/101 it seems that I should not be getting this probem as I am am running version 1.3.3 of yo.

I understand that by generating files as root I run the risk of shooting myself in the foot, I can handle permission issues on my own, but I still need to be able to do this.

Additional information
Host os: fedora 21
docker version: 1.2
container os ubuntu 14.04
yo version: 1.3.3

**Comment by dpkirchner** [comment]
Unfortunately the latest yo doesn't solve the issue. It looks like issue #101 was the first to track this bug but it was closed with this same note (that it's working if you sudo). I can confirm sudo doesn't make a difference. Opening a new ticket.
