### ISSUE TITLE
Can't find generators under Win32

### ISSUE THREAD

**Issue by Kyle2123** [yeoman/yo#243]
Having a problem with Yo finding generator packages under Win32.  I believe the problem is due to backslashes in the glob pattern.  According to node-glob docs at https://github.com/isaacs/node-glob, only forward slashes should be used in glob patterns, even on Windows.  If I edit node_modules/yeoman-environment/lib/resolver.js and add this on line 44, it works:

pattern = pattern.replace(/\/g, '/');

Without that change, here is what I get when trying to run a generator:

C:\Code\YoTest>npm install generator-hottowel -g

generator-hottowel@0.0.7 C:\Users\kwest\AppData\Roaming\npm\node_modules\generator-hottowel

+-- chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)

+-- yosay@0.3.0 (ansi-regex@0.2.1, string-length@0.1.2, pad-component@0.0.1, word-wrap@0.1.3, ansi-styles@1.1.0, strip-ansi@0.2.2,

0.2.0, chalk@0.4.0, taketalk@0.1.1)

+-- yeoman-generator@0.17.7 (dargs@2.1.0, diff@1.2.0, class-extend@0.1.1, rimraf@2.2.8, text-table@0.2.0, github-username@1.0.0, u

string@2.4.0, mime@1.2.11, async@0.9.0, debug@1.0.4, isbinaryfile@2.0.3, grouped-queue@0.3.0, cross-spawn@0.2.3, nopt@3.0.1, mkdir

helljs@0.3.0, run-async@0.1.0, iconv-lite@0.4.5, findup-sync@0.1.3, glob@4.3.1, file-utils@0.2.1, lodash@2.4.1, request@2.49.0, ch

.0, gruntfile-editor@0.2.0, download@1.0.7, inquirer@0.7.3)

C:\Code\YoTest>npm list -g --depth=0

C:\Users\kwest\AppData\Roaming\npm

+-- bower@1.3.12

+-- generator-hottowel@0.0.7

+-- grunt-cli@0.1.13

+-- gulp@3.8.10

+-- nodemon@1.2.1

+-- typescript@1.0.1

+-- yo@1.3.3

C:\Code\YoTest>yo hottowel helloWorld

Error hottowel helloWorld

You don't seem to have a generator with the name hottowel installed.

You can see available generators with npm search yeoman-generator and then install them with npm install [name].

To see the 0 registered generators run yo with the `--help` option.

**Comment by elparkino** [comment]
this is still a problem for me, tried both your suggestions but neither helped.

it seems like all the paths returned in the module lookup can't be accessed.  Although they are the right  paths and the generators are there and NODE_HOME is set.  I'm at a loss

**Comment by SBoudrias** [comment]
@elparkino please run `yo doctor` to get help on debugging your system.

**Comment by elparkino** [comment]
@SBoudrias I have, and it says everything is fine

**Comment by elparkino** [comment]
Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version
√ NODE_PATH matches the npm root

Everything looks all right!

**Comment by elparkino** [comment]
D:\PlayVerse\Ancillary\playtricsfrontend> npm install generator-hottowel -g
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-hottowel will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
generator-hottowel@0.2.14 C:\Users\Parker.Jones\AppData\Roaming\npm\node_modules\generator-hottowel
├── chalk@0.5.1 (escape-string-regexp@1.0.3, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── yosay@0.3.0 (ansi-regex@0.2.1, string-length@0.1.2, ansi-styles@1.1.0, pad-component@0.0.1, word-wrap@0.1.3, minimist@0.2.0, strip-ansi@0.2.2, chalk@0.4.0, taketalk@0.1.1)
└── yeoman-generator@0.17.7 (dargs@2.1.0, isbinaryfile@2.0.4, class-extend@0.1.1, diff@1.4.0, rimraf@2.4.0, text-table@0.2.0, underscore.string@2.4.0, mime@1.3.4, async@0.9.2, grouped-queue@0.3.0, cro
ss-spawn@0.2.9, nopt@3.0.2, debug@1.0.4, mkdirp@0.5.1, run-async@0.1.0, shelljs@0.3.0, iconv-lite@0.4.10, glob@4.5.3, file-utils@0.2.2, github-username@1.1.1, findup-sync@0.1.3, lodash@2.4.2, request@
2.57.0, download@1.0.7, cheerio@0.17.0, gruntfile-editor@0.2.0, inquirer@0.7.3)

false
Error hottowel playtrics

You don't seem to have a generator with the name hottowel installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.


in resolve.js I'm logging out fs.existsSync(process.env.NODE_PATH) wich is the false.  That's obviously a problem, becasue that's where the generator I need lives

**Comment by SBoudrias** [comment]
Maybe you have multiple npm binaries installed?

**Comment by elparkino** [comment]
@SBoudrias I do not
