### ISSUE TITLE
Improve readme for npmjs.org

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yo#246]
As yo is on the front page, maybe we should have something a bit better? https://www.npmjs.com/package/yo

**Comment by addyosmani** [comment]
I'm happy to work on this. Suggestions:

* Philosophy - What is Yeoman? Why do you need it?
* Quick start
* Features
* Docs and community

I like the simplicity of the Express README: https://www.npmjs.com/package/express. It covers just about what you need without being overly verbose.

**Comment by SBoudrias** [comment]
@addyosmani That sounds great!
