### ISSUE TITLE
Yeoman just quits when trying to use bootstrap generator

### ISSUE THREAD

**Issue by nmaxcom** [yeoman/yo#251]
I haven't used Yeoman very little in the past, but I don't remember havingn this problem. I want to run the bootstrap generator to start working on a new web:

![enter image description here][1]

  [1]: http://i.stack.imgur.com/zCPPa.png

**It just quits** on my face. The folder remains empty and no errors.
I've tried selecting less or sass just to try, same result.

I've uninstalled the generators, yeoman and even the whole npm/node thing and reinstalled alll again. Same result.

I'm not finding anything on the internet, so it must be something really stupid on my site. What is it?

**Comment by sindresorhus** [comment]
That's weird. You should have gotten the Bower install output.

This is what I get:

```
❯ yo bootstrap
? In what format would you like the Bootstrap stylesheets? css
bower bootstrap#*           not-cached git://github.com/twbs/bootstrap.git#*
bower bootstrap#*              resolve git://github.com/twbs/bootstrap.git#*
bower bootstrap#*             download https://github.com/twbs/bootstrap/archive/v3.3.1.tar.gz
bower bootstrap#*             progress received 2.2MB of 2.8MB downloaded, 78%
bower bootstrap#*              extract archive.tar.gz
bower bootstrap#*             resolved git://github.com/twbs/bootstrap.git#3.3.1
bower jquery#>= 1.9.1           cached git://github.com/jquery/jquery.git#2.1.3
bower jquery#>= 1.9.1         validate 2.1.3 against git://github.com/jquery/jquery.git#>= 1.9.1
bower bootstrap#~3.3.1         install bootstrap#3.3.1
bower jquery#>= 1.9.1          install jquery#2.1.3
bower                          no-json No bower.json file to save to, use bower init to create one

bootstrap#3.3.1 bower_components/bootstrap
└── jquery#2.1.3

jquery#2.1.3 bower_components/jquery
```

Can you make sure you're running the latest version of Node, Bower and Yo?

**Comment by kevva** [comment]
I was under the assumption he got it working but was just wondering why it installed it in the `bower_components` directory.

**Comment by eddiemonge** [comment]
Can this issue be closed since it seems like it might be working?

**Comment by nmaxcom** [comment]
I can't get on tryin atm so yeah you should close it
