### ISSUE TITLE
can not install yeoman on my mac running OS X Yosemite 10.10.1

### ISSUE THREAD

**Issue by wbarnie** [yeoman/yo#253]
i have tried several times to install yeoman on my mac but the install fails.  i am installing as root so there should be no permission issues.  here is the output:

sh-3.2# npm install -g yo
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/cli.js

> yo@1.3.3 postinstall /usr/local/lib/node_modules/yo
> yodoctor

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: yodoctor: command not found

npm ERR! yo@1.3.3 postinstall: `yodoctor`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the yo@1.3.3 postinstall script.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.0.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! cwd /
npm ERR! node -v v0.10.34
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
sh-3.2# 

Please tell me how i can fix this problem.  Thank you.

**Comment by caiosba** [comment]
If you really want to run it as root (e.g., in a docker container), you can use the `--unsafe-perm=true` flag. Not recommended, though.
