### ISSUE TITLE
Installing Yo along with bower and grunt-cli failed on Win 8.1

### ISSUE THREAD

**Issue by senal** [yeoman/yo#258]
Hi,
I tried installing Yo along with bower and grunt-cli on win 8.1 and it was ended with the following error on the cmd promot. ( There were no npm-debug.log created in the drive c:)

Highly appreciate your prompt reply in this regard.

Following the error that I copied from the cmd prompt to text.
|------------------------------ error start --------------------------------------------------------------|

> node-gyp rebuild

C:\Users\rsf\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-generator\n
ode_modules\download\node_modules\decompress\node_modules\vinyl-fs\node_modules\
glob-watcher\node_modules\gaze>node "C:\Program Files (x86)\nodejs\node_modules\
npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
npm http 304 https://registry.npmjs.org/balanced-match
npm http 200 https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Platform.t
argets(42,5): error MSB8020: The builds tools for Visual Studio 2010 (Platform
Toolset = 'v100') cannot be found. To build using the v100 build tools, either
click the Project menu or right-click the solution, and then select "Update VC+
+ Projects...". Install Visual Studio 2010 to build using the Visual Studio 201
0 build tools. [C:\Users\rsf\AppData\Roaming\npm\node_modules\yo\node_modules\y
eoman-generator\node_modules\download\node_modules\decompress\node_modules\viny
l-fs\node_modules\glob-watcher\node_modules\gaze\build\pathwatcher.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files (x86)\nodejs\node_mo
dules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\rsf\AppData\Roaming\npm\node_modules\yo\node_modules\yeoma
n-generator\node_modules\download\node_modules\decompress\node_modules\vinyl-fs\
node_modules\glob-watcher\node_modules\gaze
gyp ERR! node -v v0.10.13
gyp ERR! node-gyp -v v0.10.2
gyp ERR! not ok
unbuild gaze@0.6.4
unbuild glob-watcher@0.0.7
unbuild vinyl-fs@0.3.13
unbuild decompress@2.1.1
unbuild download@0.1.19
unbuild yeoman-generator@0.16.0
unbuild yo@1.1.2
npm ERR! weird error 1
npm ERR! not ok code 0

|------------------------------ error end ---------------------------------------------------------------|

Please find the attached screen shot.

![yoinstallationfailed](https://cloud.githubusercontent.com/assets/2841066/5592162/94a4c760-91e0-11e4-9523-9e3993561d97.png)

**Comment by senal** [comment]
The error posted by me above seems to be related to 
https://github.com/yeoman/yeoman/issues/1330
It seems that Yo wants VS 2010 but I have only 2012 installed. Isn't possible to get the yo to build with VS 2012 ?

**Comment by SBoudrias** [comment]
This is related to a dependency, not Yeoman. As so, I'll close this issue.

Reopen on the relevant project.

**Comment by senal** [comment]
Hi SBoudrias,
Thanks for the prompt feedback.
However, Could you please let me know the place where I can log an issue for this problem as I couldn't find a separate location dedicated for dependencies ?

Thanks in advance for your prompt reply.

**Comment by jbillybytes** [comment]
did anyone find a solution to this?

**Comment by senal** [comment]
No feedback yet. @SBoudrias  said this is relating to some dependency issue. 
Waiting for a positive feedback.

**Comment by SBoudrias** [comment]
The dependency not being build as you can see when reading the log is either gaze or node-gyp or both. My guess is you don't have any C build tools on your machine (which is pretty weird, so maybe you deleted it? Or maybe it's not in a standard path - I don't know)

Anyway, install visual studio or something and it should work. Otherwise, you can google with this information and try to find a solution. I'm sorry, but there's usually no windows expert around here.

**Comment by senal** [comment]
@SBoudrias thank you very much for your prompt reply.
I will try installing VS again.
