### ISSUE TITLE
Broken link in npm install output

### ISSUE THREAD

**Issue by fabiosantoscode** [yeoman/yo#259]
Hey!

I have a new computer, and was trying to install yeoman on it.

So I ran `sudo npm install -g yeoman` and got a warning (and took heed of it):

`npm WARN deprecated yeoman@0.9.6: The Yeoman CLI is deprecated. See http://yeoman.io/migrate.html for more info.`

The link to http://yeoman.io/migrate.html is broken so I thought I'd tell you guys.

Thanks for a wonderful tool!

Much love from Portugal <3

**Comment by sindresorhus** [comment]
The Yeoman CLI was deprecated over a year ago. It's not going to be updated anymore.

Use `npm install -g yo` is what you're looking for.

As for the referenced site, see: https://gist.github.com/sindresorhus/f70745187f3003bb3634
