### ISSUE TITLE
Cannot be found custom yeoman generator  "Install a generator"

### ISSUE THREAD

**Issue by masakura** [yeoman/yo#260]
I made a yeoman generator that generator-graybullet-cordova, but can not be found by "Install a generator".

```
? 'Allo Tomo! What would you like to do? Install a generator
? Search NPM for generators: graybullet
? Sorry, nothing was found: (Use arrow keys)
❯ Search again 
  Return home 
```

Yo is seems to be using the "http://isaacs.iriscouch.com/". but, isaacs seems not synchronized from per August of last year. For this reason, it is not possible to find the newly created yeoman generator.

```
$ yo --version
1.3.3
$ npm --version
2.1.17
$ node --version
v0.10.35
$ npm info generator-graybullet-cordova description
Webapp like yeoman generator for Apache Cordova
```

**Comment by SBoudrias** [comment]
Did you added the special keyword in your package.json?

**Comment by masakura** [comment]
Thanks.

Special keyword it points to a "yeoman-generator"? Of course, I have written it.

```
$ npm info generator-graybullet-cordova keywords
 
[ 'yeoman-generator',
  'web',
  'app',
  'front-end',
  'h5bp',
  'jquery',
  'grunt',
  'cordova',
  'mobile' ]
```

```
$ w3m -dump http://isaacs.iriscouch.com/rnoegistry/generator-graybullet-cordova
{"error":"not_found","reason":"missing"}
```

In GENERATOR-WEBAPP...

```Thanks.

Special keyword it points to a "yeoman-generator"? Of course, I have written it.

```
$ npm info generator-graybullet-cordova keywords
 
[ 'yeoman-generator',
  'web',
  'app',
  'front-end',
  'h5bp',
  'jquery',
  'grunt',
  'cordova',
  'mobile' ]
```

To begin with, the package to isaacs is not registered.

```
$ w3m -dump http://isaacs.iriscouch.com/registry/generator-graybullet-cordova
{"error":"not_found","reason":"missing"}
```

**Comment by SBoudrias** [comment]
Alright, well master should work fine as we updated to the official npm couchdb. We just need to carve a release soonish.

**Comment by sindresorhus** [comment]
Should be fixed in 1.4.0 ;)

**Comment by masakura** [comment]
Thanks! :smile: 

Worked correctly!

```
$ yo --version
1.4.0
$ yo
? 'Allo Tomo! What would you like to do? Install a generator
? Search npm for generators: graybullet
? Here's what I found. (:{ represents offical generators)
  Install one? (Use arrow keys)
❯ graybullet-cordova 
  Search again 
  Return home 
```

**Comment by xtianus79** [comment]
yes thank you!
