### ISSUE TITLE
Share generator blocklist with `yo` and the website

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/yo#261]
Currently it's duplicated.

Put it in a JSON file on yeoman/yeoman.io and have the website and yo use it.

- [x] website: https://github.com/yeoman/yeoman.io/blob/1d3a9c8b77ee88d6c98f92e48dec534723414990/app/assets/js/script.js#L39-L47
- [ ] yo: https://github.com/yeoman/yo/commit/681bf11ee5619fd76a093abb04a660784a835d96

**Comment by eddiemonge** [comment]
i think a better solution is to remove the blocklist and have those packages updated

**Comment by sindresorhus** [comment]
I think both. From experience with the gulp blocklist it's hard to get random people to fix their package. Easier to block first and have them fix it later (usually never happens anyways).

**Comment by ankurkaushal** [comment]
I think I want to work on this, can I get this one assigned to myself?

**Comment by SBoudrias** [comment]
@ankurkaushal just send a PR.

We usually assign only when someone of the core team is working on it for a long time to let people know this is being worked on.

**Comment by ankurkaushal** [comment]
Sure thing! Thanks for letting me know.

**Comment by gaboesquivel** [comment]
I'm working on this see https://github.com/gaboesquivel/yo/blob/blacklist/lib/routes/install.js   
let me know your thoughts, is q ok or you prefer http?   how to handle error on blacklist request? use empty object or callback(err) ? 
list can be mocked with nock, however can you make it a separate file to test with real response?  https://github.com/yeoman/yo/pull/290

**Comment by sindresorhus** [comment]
> let me know your thoughts, is q ok or you prefer http?

https://github.com/gaboesquivel/yo/commit/b87dbf7e384be6efe486ee8a5708bd4c65252e71#commitcomment-9538657

> how to handle error on blacklist request? use empty object or callback(err) ? 

Empty object.

**Comment by gaboesquivel** [comment]
@sindresorhus I think this issue can be closed now
