### ISSUE TITLE
Generator called from CLI is not being found

### ISSUE THREAD

**Issue by taiansu** [yeoman/yo#264]
In 1.3.3, I can use yo like:
```bash
yo generator my-generator
```

But after update to 1.4.0 will response:
```
Error generator

You don't seem to have a generator with the name generator installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
``` 

I do have generator-generator installed globally, also `yo --help` list nothing beneath like 1.3.3

And interactive usage looks normal:
```
? 'Allo Taian! What would you like to do? (Use arrow keys)
  Run a generator
❯ Generator
  Rf
  ──────────────
  Update your generators
  Install a generator
  Find some help
  Get me out of here!
  ──────────────
```

> Envorinment
node: v0.10.35
npm: 2.1.18
yo: 1.4.0

**Comment by marcin-wosinek** [comment]
I confirm that. Help is empty and generators are not found. Downgrading to 1.3 helps. Having CI test as a part of the fix would be great - I will try to take a look on this.

**Comment by jdahdah** [comment]
Having this issue as well with 1.4.0 and a local generator installed via `npm link`.

**Comment by sindresorhus** [comment]
Sorry about that. I've pulled the update. We should definitely have regressions tests before doing another release.

You can downgrade by running: `npm install --global yo@1.3.3`.

**Comment by m3hr** [comment]
Hi, did the commits fix this? Because I'm still having trouble in 1.4.5

**Comment by SBoudrias** [comment]
@m3hr run `yo doctor`

**Comment by m3hr** [comment]
```
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ NODE_PATH matches the npm root

Everything looks all right!
```

For the record, I'm running the latest io.js installed from nvm. Is io.js not officially supported?

**Comment by SBoudrias** [comment]
@m3hr didn't test myself with io.js, but my guess is that it should just work.

My guess is that you might have multiple npm versions running in different context and installing packages in different location. Maybe setting the NODE_PATH env variable manually to the npm global installation will fix it.

**Comment by m3hr** [comment]
Like the OP, running `yo --help` does spit out a list of generators I'm using, so they seem to be in the right place? And I triple checked my NODE_PATH variable, though the .npm folder in my root directory than the node_modules folder in nvm, but I'm guessing this is how it is supposed to be.

**Comment by SBoudrias** [comment]
@m3hr you're on windows?

**Comment by m3hr** [comment]
Ubuntu 14.10 lol

**Comment by SBoudrias** [comment]
@m3hr I don't really have time ATM to debug this. If you can dig in, it'd be nice.

The thing to know is the generators are found by yeoman-environment (the resolver module). And they're used from `yo` on the `run` route. Maybe you can debug and inspect the states and help pointing the wrong state.

**Comment by m3hr** [comment]
Yeah, sorry, I didn't really want to take up your time. I'll see what I can do.

**Comment by m3hr** [comment]
I read through some of the code, it seems that by default yo looks for index.js in the module folder but not the app/ directory (which my generators have), though there's another function to create path aliases, so I think it should work. I also tried node instead of io.js and it still didn't recognize it.

**Comment by m3hr** [comment]
@SBoudrias I FIGURED IT OUT. I had to do `yo generator:app:index` instead of just `yo generator`. I'm not really sure why other than the resolver module not checking when there is a different hierarchy. Thanks for the info!

**Comment by SBoudrias** [comment]
Ok, this is probably another issue than the one initially reported, but that's still a bug. Is your generator on github?

**Comment by m3hr** [comment]
I tested https://github.com/julien/generator-phaser and https://github.com/yeoman/generator-ember

**Comment by SBoudrias** [comment]
io.js support have been fixed recently BTW :)
