### ISSUE TITLE
Cannot update to 1.4.1 on Windows 8.1

### ISSUE THREAD

**Issue by patrickgrey** [yeoman/yo#272]
Hello, looking forward to some 1.4 goodness from current version 1.3.3 but each way I try fails. Another user on twitter also has this problem using Windows 8.1. I've updated npm (node 0.10.3). I've had no problems with previous installs and PATH settings.

I try npm install -g yo and that goes through the process without errors but yo -v returns 1.3.3. I tried npm install -g yo@LATEST but get an ERR! notarget returned (log output below). Any pointers on how to debug please?

0 info it worked if it ends with ok
1 verbose cli [ 'c:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '-g',
1 verbose cli   'install',
1 verbose cli   'yo@LATEST' ]
2 info using npm@1.4.21
3 info using node@v0.10.30
4 verbose cache add [ 'yo@LATEST', null ]
5 verbose cache add name=undefined spec="yo@LATEST" args=["yo@LATEST",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'yo@LATEST',
6 verbose parsed url   path: 'yo@LATEST',
6 verbose parsed url   href: 'yo@LATEST' }
7 verbose cache add name="yo" spec="LATEST" args=["yo","LATEST"]
8 verbose parsed url { protocol: null,
8 verbose parsed url   slashes: null,
8 verbose parsed url   auth: null,
8 verbose parsed url   host: null,
8 verbose parsed url   port: null,
8 verbose parsed url   hostname: null,
8 verbose parsed url   hash: null,
8 verbose parsed url   search: null,
8 verbose parsed url   query: null,
8 verbose parsed url   pathname: 'LATEST',
8 verbose parsed url   path: 'LATEST',
8 verbose parsed url   href: 'LATEST' }
9 verbose addNamed [ 'yo', 'LATEST' ]
10 verbose addNamed [ null, null ]
11 silly lockFile 94ff678b-yo-LATEST yo@LATEST
12 verbose lock yo@LATEST C:\Users\Patrick\AppData\Roaming\npm-cache\94ff678b-yo-LATEST.lock
13 info addNameTag [ 'yo', 'LATEST' ]
14 verbose request where is /yo
15 verbose request registry https://registry.npmjs.org/
16 verbose request id fbc1b5f3aeed363a
17 verbose url raw /yo
18 verbose url resolving [ 'https://registry.npmjs.org/', './yo' ]
19 verbose url resolved https://registry.npmjs.org/yo
20 verbose request where is https://registry.npmjs.org/yo
21 info trying registry request attempt 1 at 19:27:02
22 verbose etag "60DZLE9FF89I1AH8H4IMBTWQZ"
23 http GET https://registry.npmjs.org/yo
24 http 304 https://registry.npmjs.org/yo
25 silly registry.get cb [ 304,
25 silly registry.get   { date: 'Fri, 09 Jan 2015 19:27:03 GMT',
25 silly registry.get     server: 'Apache',
25 silly registry.get     via: '1.1 varnish',
25 silly registry.get     'last-modified': 'Fri, 09 Jan 2015 19:27:03 GMT',
25 silly registry.get     'cache-control': 'max-age=60',
25 silly registry.get     etag: '"60DZLE9FF89I1AH8H4IMBTWQZ"',
25 silly registry.get     age: '0',
25 silly registry.get     'x-served-by': 'cache-lcy1122-LCY',
25 silly registry.get     'x-cache': 'HIT',
25 silly registry.get     'x-cache-hits': '1',
25 silly registry.get     'x-timer': 'S1420831623.348552,VS0,VE154',
25 silly registry.get     vary: 'Accept',
25 silly registry.get     'content-length': '0',
25 silly registry.get     'keep-alive': 'timeout=10, max=50',
25 silly registry.get     connection: 'Keep-Alive' } ]
26 verbose etag https://registry.npmjs.org/yo from cache
27 silly lockFile 94ff678b-yo-LATEST yo@LATEST
28 silly lockFile 94ff678b-yo-LATEST yo@LATEST
29 error notarget No compatible version found: yo@'LATEST'
29 error notarget Valid install targets:
29 error notarget ["1.0.0-beta.1","1.0.0-beta.2","1.0.0-beta.3","1.0.0-beta.4","1.0.0-beta.5","1.0.0-beta.6","1.0.0-beta.7","1.0.0-rc.1","1.0.0-rc.1.1","1.0.0-rc.1.2","1.0.0-rc.1.3","1.0.0-rc.1.4","1.0.0","1.0.1","1.0.2","1.0.3","1.0.4","1.0.5","1.0.6","1.0.7-pre.1","1.0.7-pre.2","1.0.7-pre.3","1.1.0","1.1.1","1.1.2","1.2.0","1.2.1","1.3.0","1.3.2","1.3.3"]
29 error notarget
29 error notarget This is most likely not a problem with npm itself.
29 error notarget In most cases you or one of your dependencies are requesting
29 error notarget a package version that doesn't exist.
30 error System Windows_NT 6.2.9200
31 error command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "-g" "install" "yo@LATEST"
32 error cwd d:\Offline\patrickgrey\clients\2015\paulClelland\pg-clients-2015-paul-clelland
33 error node -v v0.10.30
34 error npm -v 1.4.21
35 error code ETARGET
36 verbose exit [ 1, true ]

**Comment by SBoudrias** [comment]
You need at least npm 2.1 to use yo. `npm -g install npm`
