### ISSUE TITLE
1.4.1 ignores --skip-install option

### ISSUE THREAD

**Issue by taiansu** [yeoman/yo#274]
yo@1.4.1 seems to ignore commend options like `--skip-install` or `--skip-test`, but the options without dash in between works normally.

Even if I specify the value like `--skip-install=true` still no luck. By the way, I can use `yo generator MyApp -singleDashOrTwo` in 1.3.3, but that doesn't work unless I use two dash instead, that means neither `yo -v` nor `yo -h` works.

> Env
yo@1.4.1
npm@2.1.18
node v0.10.35

**Comment by SBoudrias** [comment]
ping @sindresorhus could this be related to the switch from nopt to meow?

**Comment by sindresorhus** [comment]
Ah, yeah. `meow` camelCases flags for easier use. So you can use `--skip-install` as `skipInstall`. So we just have to change those cases to camelCase.

**Comment by SBoudrias** [comment]
@sindresorhus this will be problematic as it is handled by yeoman-generator, so generators on older version won't work.

I think we should revert to nopt.

**Comment by sindresorhus** [comment]
@SBoudrias Where in `yeoman-generator` are these flags defined?
