### ISSUE TITLE
Config store isn't saving data

### ISSUE THREAD

**Issue by MikaAK** [yeoman/yo#275]
Recently I updated my generator with a few template changes and after generating a new project and noticed the following code no longer works. I have a `.yo-rc.json` in the root of the project that is generated and the same code used to work.  I even tried creating a separate file with only a configuration save but nothing saved to the `.yo-rc.json`. 

This could just be I'm using an old syntax but I couldn't find documentation of that anywhere. 

```javascript
var MikaGenerator = yeoman.generators.Base.extend({
  config: function() {
    this.config.set('coffeescript', false);
    this.config.save()
  }
})
```

**Comment by SBoudrias** [comment]
The documentation is here: http://yeoman.github.io/generator/Storage.html

Your code seem correct, can you explain how you realized the file was not created?

**Comment by MikaAK** [comment]
The file is actually created, but just contains an empty object `{}`. I came to this realization after none of my subgenerators were working as some names would show up as `undefined`

**Comment by SBoudrias** [comment]
What version of yeoman-generator are you using?

**Comment by MikaAK** [comment]
^0.18.0 - yeoman-generator
^1.4.0 - yo

**Comment by robdodson** [comment]
Seeing the same issue with the [generator-polymer](https://github.com/yeoman/generator-polymer).

It's pretty strange. I wrote a unit test:

```
assert.fileContent(
  '.yo-rc.json', /"includeSass": true/
);
```
and that passes when I test my generator with mocha. However, when I use `npm link` to run the generator it ends up writing out a `.yo-rc.json` which only contains `{}`. I can see that `includeSass` is true as the generator is running, so seems to be related to recent changes in either 0.18.0 generator or yo 1.4

**Comment by robdodson** [comment]
Ah, I realized why my test was passing. I hadn't cleaned out my `node_modules` dir after upgrading to generator 0.18. Reverting to 0.17 fixes the issue. So something is afoul in generator 0.18.

**Comment by VinSpee** [comment]
+1 - I cant seem to read config on v0.18 either.

**Comment by Dmitry-N-Medvedev** [comment]
this bug has been filed 10 days ago. Either I am an idiot, or I just do not understand why this has not yet been fixed. The config does not read .yo-rc.json, it does not write .yo-rc.json. I've seen new features introduces to yeoman-generator@0.18.0 with a machine global storage ( "{store: true}" ) which does not work also.

gentlemen, my former generator fails with this issue. my new project is just freezed with no understanding when things will be up and running.

**Comment by SBoudrias** [comment]
@Dmitry-N-Medvedev Maybe because I didn't had the time to sit and take time to fix it yet. If it is so major for you, feel free to fix and send a PR. It'll get merge.

**Comment by Dmitry-N-Medvedev** [comment]
@SBoudrias, I would if only I could produce acceptable code in JavaScript. Sir, my work now depends on your free time.

**Comment by VinSpee** [comment]
@Dmitry-N-Medvedev dude. Seriously, don't.

- Option 1: roll back 1 minor version.
- Option 2: fix it yourself and submit a PR
- Option 3: wait patiently
- Option 4: use something else

Please don't be rude.

**Comment by eddiemonge** [comment]
* option 5 Sponsor the issue: https://www.bountysource.com/teams/yeoman/issues?tracker_ids=75869

Again, this project is done in our free time, after working full time jobs. We have to have down time as well for things like, you know, the real world and activities for our own enjoyment.

**Comment by SBoudrias** [comment]
Hey, I investigated that issue and I'll push a fix soon.

In the meantime, to fix it just don't call `config.save()` by yourself. Using `config.set()` automatically save the config correctly.

**Comment by robdodson** [comment]
Great, thanks for working on htis @SBoudrias :)
