### ISSUE TITLE
Generator 'Update Available!' message doesn't shown

### ISSUE THREAD

**Issue by stefanbuck** [yeoman/yo#278]
Yesterday I recognised that my installed angular generator version is outdated. My versions are `generator-angluar v0.9.8` (latest is 0.10.0) and `yo v1.4.2`. So normally it should display a nice "♥ Update Available!" message, but It doesn't shown up. Have anybody else problems?

**Comment by stefanbuck** [comment]
@sindresorhus @SBoudrias can you confirm that?

**Comment by SBoudrias** [comment]
Might be broken, but the code is still there: https://github.com/yeoman/yo/blob/master/lib/router.js#L79

**Comment by stefanbuck** [comment]
I will take a look on it.

**Comment by stefanbuck** [comment]
@SBoudrias should the update message appears only once per day? 

1) If I set `lastUpdateCheck` in `update-notifier-generator-angular.yml` to `1` to force an update and run `yo` the content of the file changed to:
```
optOut: false
lastUpdateCheck: 1421359974632
update:
  latest: 0.10.0
  current: 0.9.8
  type: minor
  name: generator-angular
```
But no update message comes up. 

2) Then I run `yo` again and the update message comes up and the files changed to
```
  optOut: false
  lastUpdateCheck: 1421359974632
```

3) Kill `yo` without updating the generator

4) Now on the next run the message is gone for one day because of this `updateCheckInterval` https://github.com/yeoman/update-notifier/blob/7dbf2725f096198765fba7f89bdf1d43f1fba4b2/index.js#L28

In my opinion, the message should be visible all the time until the generator was updated.

**Comment by sindresorhus** [comment]
> should the update message appears only once per day?

Yes.

> In my opinion, the message should be visible all the time until the generator was updated.

Sounds like you would enjoy Windows XP.

![image7](https://cloud.githubusercontent.com/assets/170270/5771038/45e7d6bc-9d70-11e4-9333-f4378d149229.png)

We're not going to annoy users with update notifications all the time. Generators update often and that would mean the update notifications would pretty much be there all the time.

**Comment by stefanbuck** [comment]
Hehe, it's just a string, not a disturbing pop up. But I agree with your last statement.

**Comment by SBoudrias** [comment]
@stefanbuck so... To make it very clear; it is not broken? It's only showing once a day?

**Comment by stefanbuck** [comment]
@SBoudrias Yes, it is NOT broken. Just the behavior was not clear, now it is :wink:
