### ISSUE TITLE
Description is not synchronized on yeoman.io/generators

### ISSUE THREAD

**Issue by masakura** [yeoman/yo#279]
http://yeoman.io/generators/

It seems that generator's description is not synchronized.

[generator-graybullet-cordova](https://github.com/GrayBullet/generator-graybullet-cordova)'s description is `Webapp like yeoman generator for Apache Cordova`.

```
$ npm info generator-graybullet-cordova description                                                    
Webapp like yeoman generator for Apache Cordova
```

However, the description is displayed as `Apache Cordova`.

![graybullet-cordova-description](https://cloud.githubusercontent.com/assets/6840413/5798454/9ad94434-a00a-11e4-9828-45bee2c2ef46.jpg)

Old description of the generator was `Yeoman generator for Apache Cordova`.

description that appears in yeoman.io appear to be the ones that have been deleted "Yeoman generator for". Old ones seem to have been displayed.

What should I do in order to synchronize the description?

**Comment by sindresorhus** [comment]
We strip useless things some the description as mentioning it's a "Yeoman generator" is superfluous. The generator description should say what it does, not what it is.

And per the description from the generator page:

> Your generator must have the "yeoman-generator" keyword and a repo description to be listed.

We use the repo description.

**Comment by masakura** [comment]
I'm sorry. I was a misunderstanding.

I Understand that it used  GitHub repo description, not NPM description.

I've rewritten the description of GitHub. Let’s wait and see for a while.

**Comment by masakura** [comment]
Thaks!

Now, If I look at the yeoman.io, it had been synchronized. :smile:
