### ISSUE TITLE
yo --help does not list subgenerators.

### ISSUE THREAD

**Issue by dnozay** [yeoman/yo#280]
I'm trying to find that particular command that I always mis-type.
But the help is of no help.

```
(jk)Damiens-MacBook-Air:foo damien$ yo --generators
angular
jekyllrb
karma
mocha
```
```
(jk)Damiens-MacBook-Air:foo damien$ yo angular --help
Usage:
  yo angular:app [options] [<appname>]

Options:
  -h,   --help                # Print generator's options and usage                   Default: false
        --app-suffix          # Allow a custom suffix to be added to the module name  Default: false
        --appPath             # Generate CoffeeScript instead of JavaScript           Default: false
        --coffee              # Generate CoffeeScript instead of JavaScript           Default: false
        --angular:common      # Angular:common to be invoked                          Default:
        --angular:main        # Angular:main to be invoked                            Default:
        --angular:controller  # Angular:controller to be invoked                      Default:

Arguments:
  appname  # Type: String  Required: false
```

**Comment by SBoudrias** [comment]
Just type `yo --help`. `yo generator --help` provide help for that specific generator.

What would you like more as help information?

**Comment by dnozay** [comment]
the list of subgenerators for generators that are installed.

**Comment by dnozay** [comment]
in this code:
```
exports.generatorsFromEnv = function (env) {
  return arrayUniq(Object.keys(env.getGeneratorsMeta()).map(exports.namespaceToName));
};
```
you already have all the generators, but then you shrink down the list to the namespaces instead of generators.

**Comment by sindresorhus** [comment]
`yo --generators` is meant for programmatic consumption and only contains the top level ones. I've made `yo --help` output subgenerators too.

**Comment by JuliusKoronci** [comment]
This actually doesn't work..I have 10 folders in the generators dir but only the app is listed when running yo mygenerator --help

**Comment by jedmao** [comment]
Same issue here. `yo --help` shows sub-generators:
```
Available Generators:
  generator
    sub-generator
```
But `yo generator --help` only shows usage, options, description and example w/o exposing the sub-generators at all!
