### ISSUE TITLE
Installing error - No compatible version found: inquirer@'>=0.8.1 <0.9.0'

### ISSUE THREAD

**Issue by grsabreu** [yeoman/yo#283]
Hi guys, I'm trying to install yo but I'm just getting this error in my console:
npm ERR! Linux 3.16.0-23-generic
npm ERR! argv "node" "/home/gabriel/local/bin/npm" "install" "-g" "yo"
npm ERR! node v0.10.35
npm ERR! npm  v2.2.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: inquirer@'>=0.8.1 <0.9.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.1.0","0.1.1","0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.2.0","0.2.1","0.1.11","0.1.12","0.2.2","0.2.3","0.2.4","0.2.5","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.5","0.4.0","0.4.1","0.5.0","0.5.1","0.6.0","0.7.1","0.7.2","0.7.3","0.8.0"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

How to solve that? I googled for that, but no solution has worked for me.

**Comment by SBoudrias** [comment]
I had to unpublish 0.8.1 due to issues.

Just set as `"inquirer": "^0.8.0"` in your package.json

**Comment by grsabreu** [comment]
Thanks @SBoudrias
installing an older version of yo worked for me too

**Comment by SBoudrias** [comment]
The latest version should work fine. You probably just had an issue with the npm cache.

**Comment by SBoudrias** [comment]
Found the issue, it is now correctly fixed.

**Comment by mohsinkerai** [comment]
npm cache clean worked for me.
