### ISSUE TITLE
How can I over come ?

### ISSUE THREAD

**Issue by angryillusionist** [yeoman/yo#287]
![error-yo-webapp-install](https://cloud.githubusercontent.com/assets/9817515/5954587/778111d6-a7c3-11e4-93b5-267e520f78e4.png)

I am very new in yo. I generate yo webapp. grant server is running well. if I ignore those error How can it effect my web app and what is the solution. By the way first time win command line don't recognize bower, grunt also yo but I set the path manually then it works.

**Comment by sindresorhus** [comment]
The error message says exactly what you should do **if you need help**.
