### ISSUE TITLE
yo project wrong path

### ISSUE THREAD

**Issue by lipangit** [yeoman/yo#288]
When I yo 'projectname' ,this project must in /~ , wrong path,where ever I call it.
![image](https://cloud.githubusercontent.com/assets/2038071/5992125/b22257e4-aa54-11e4-9fcf-268604b4a68a.png)

**Comment by ragingwind** [comment]
Create a project path first and run `yo` command in your command.

**Comment by lipangit** [comment]
Yes I created, example ~/MyHobby/testExpress/ ,then yo projectName,but this project created in my home path.

**Comment by SBoudrias** [comment]
Remove the .yo-rc.json file from your home folder
