### ISSUE TITLE
"I'm all done" message can be confusing

### ISSUE THREAD

**Issue by kevinschaul** [yeoman/yo#295]
Yeoman tells us he is "all done" but then goes on to run `bower install` and `npm install` for us. It's a nit-picky point, but some members of our team have gotten confused by this message.

Something to the effect of "I am running bower install & npm install for you, and then I'll be done" could be an improvement.

**Comment by SBoudrias** [comment]
Are you using the last version?

**Comment by kevinschaul** [comment]
Now I am. Sorry!
