### ISSUE TITLE
Unable to generate the gulp-angular! Error on windows 8.1... Why ? any solution ? It is not only for gulp-angular but for every generator on my PC

### ISSUE THREAD

**Issue by iamkdev** [yeoman/yo#296]
F:\node-ng-js-workspace\wms\node_modules\browser-sync\node_modules\socket.io\nod
e_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>node "C
:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\nod
e-gyp\bin\node-gyp.js" rebuild
npm ERR! EEXIST, open 'C:\Users\kamal\AppData\Roaming\npm-cache\f7fcffd5-adable-
stream-1-0-33-package-tgz.lock'
File exists: C:\Users\kamal\AppData\Roaming\npm-cache\f7fcffd5-adable-stream-1-0
-33-package-tgz.lock
Move it away, and try again.

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd F:\node-ng-js-workspace\wms
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! path C:\Users\kamal\AppData\Roaming\npm-cache\f7fcffd5-adable-stream-1-
0-33-package-tgz.lock
npm ERR! code EEXIST
npm ERR! errno 47

**Comment by kevva** [comment]
`npm install -g npm@next` and clean your cache.
