### ISSUE TITLE
Generator Unit-Test question

### ISSUE THREAD

**Issue by hanneshal** [yeoman/yo#300]
Hey there,

I've created a generator which uses several sub generators. I start the sub generators from inside the main app with with a prompt (checkbox list).

The Unit Test for the main generator, without the sub generators works fine. The tests for every single sub generator are also fine. 
Now I wan't to test the whole thing. Not just the sub generators itself.

So the main app asks 2 questions and then shows a checkbox list. 
```javascript
  ...
  type:    'checkbox',
  name:    'wantedFeatures',
  message: 'What kind of features do you need?',
  choices: [
    {
      name:    'Feature 1',
      value:   'includeFeature1',
      checked: false
    },
    {
      name:    'Feature 2',
      value:   'includeFeature2',
      checked: false
    }
  ]
  ...

```

Later in the code I start the sub generators with 
```javascript
this.composeWith('example:feature1'{})
```

The test itself should now answer Question 1-3 and select Feature 1, answers the questions for sub generator Feature 1 and check for files. 

Is this possible? Can you give me an advice how to achieve this, if it's possible.

Thx in advance.
regards
Johannes

P.S.:
The current tests looks like this (example):
```javascript
'use strict';

var path = require('path');
var os = require('os');
var helpers = require('yeoman-generator').test;
var assert = require('yeoman-generator').assert;

var mockPrompts = {
  customerContradiction: 'Foo',
  packageName: 'Bar',
  wantedFeatures: ['includeFeature2']
};

var example, tmpDir;
var testDir = process.cwd();

var deps = [path.join(testDir, '/app'),
            path.join(testDir, '/feature1'),
           ];

var expected = [
  '.editorconfig',
  'feature.md',
   mockPrompts.customerContradiction+'-'+mockPrompts.packageName+'.xml',
];

describe('Test', function () {

  describe('', function () {
    before(function (done) {
      tmpDir = path.join(os.tmpdir(), '/tmp');
      helpers.testDirectory(tmpDir, function (err) {
        if (err) { done(err); }
        example = helpers.createGenerator('example:app',deps,false, { 'skipInstall': true, 'skipLog': true });
        helpers.mockPrompt(example, mockPrompts);
        example.run(done);
      });
    });

    it('should at least have created the basic files', function () {
      helpers.assertFile(expected);
    });


  });
});
```

**Comment by SBoudrias** [comment]
This would be an integration test, and that would require something to instrument/control the terminal. I know not of such things.

Testing each generator in isolation is usually sufficient.
