### ISSUE TITLE
confusing "npm root value is not in your NODE_PATH" error after global install on mac

### ISSUE THREAD

**Issue by psnider** [yeoman/yo#304]
```
npm install -g yo
```
issued this error when I installed on my Mac:

```
✖
npm root value is not in your NODE_PATH
```

It seems that **npm root** resolves to the absolute path for  *./node_modules*, regardless of the current directory. For example,  /Users/me/projects/a/node_modules. That clearly isn't what is meant. After looking into the meaning of *npm root*, I discovered that the above error message is asking for the value of **npm root -g**, since I installed *yo* globally.

Upon adding the value of *npm root -g* to my NODE_PATH, *yo* started working properly.

Could you please change this confusing error message to reference the **-g** flag if **yo** is installed globally?

**Comment by PubuduMahesh** [comment]
run this command.

 echo "export NODE_PATH=$NODE_PATH:/home/pubudurw/local/install/node/lib/node_modules" >> ~/.bashrc && source ~/.bashrc
