### ISSUE TITLE
cannot install Yo

### ISSUE THREAD

**Issue by wramirez09** [yeoman/yo#306]
I cannot install YO 
I keep getting this error on my terminal. 
this after I updated my OS to Yosemite 

/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.4.6 postinstall /usr/local/lib/node_modules/yo
> yodoctor

env: node: No such file or directory
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! yo@1.4.6 postinstall: `yodoctor`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the yo@1.4.6 postinstall script 'yodoctor'.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/williamramirez/my-new-project/npm-debug.log
Williams-MacBook-Pro:my-new-project williamramirez$ sudo npm install -g yo bower grunt-cli gulp
/usr/local/bin/gulp -> /usr/local/lib/node_modules/gulp/bin/gulp.js
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.4.6 postinstall /usr/local/lib/node_modules/yo
> yodoctor

env: node: No such file or directory
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo" "bower" "grunt-cli" "gulp"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! yo@1.4.6 postinstall: `yodoctor`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the yo@1.4.6 postinstall script 'yodoctor'.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/williamramirez/my-new-project/npm-debug.log
Williams-MacBook-Pro:my-new-project williamramirez$ sudo npm cache clean && npm uninstall -g yo && npm install -g yo?
Password:
npm WARN uninstall not installed in /usr/local/lib/node_modules: "yo"
npm ERR! addLocal Could not install /Users/williamramirez/my-new-project/yo?
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo?"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /Users/williamramirez/my-new-project/yo?
npm ERR! code ENOENT
npm ERR! errno -2

npm ERR! enoent ENOENT, open '/Users/williamramirez/my-new-project/yo?'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/williamramirez/my-new-project/npm-debug.log
Williams-MacBook-Pro:my-new-project williamramirez$

**Comment by SBoudrias** [comment]
Please google it.
