### ISSUE TITLE
windows 8.1 generators installed but not showing

### ISSUE THREAD

**Issue by criesbeck** [yeoman/yo#307]
None of my globally installed generators are being listed or can be called, but they appear to be installed in Program Files (x86).  I.e.,

    C:\Users\riesbeck\workspace>yo --help
    Usage: yo GENERATOR [args] [options]

    General options:
      -h, --help     # Print generator's options and usage
      -f, --force    # Overwrite files that already exist

    Available Generators:

    C:\Users\riesbeck\workspace>

But the appropriate directories seem to be there are and are non-empty

    C:\Users\riesbeck\workspace>dir "C:\Program Files (x86)\nodejs\node_modules"
    Volume in drive C has no label.
    Volume Serial Number is 48E3-AD77

    Directory of C:\Program Files (x86)\nodejs\node_modules

    03/18/2015  01:03 PM    <DIR>          .
    03/18/2015  01:03 PM    <DIR>          ..
    03/05/2015  06:49 PM    <DIR>          bower
    03/18/2015  12:58 PM    <DIR>          generator-angular
    03/17/2015  03:47 PM    <DIR>          generator-gulp-angular
    03/18/2015  12:59 PM    <DIR>          generator-karma
    03/17/2015  03:50 PM    <DIR>          generator-mocha
    03/17/2015  03:50 PM    <DIR>          generator-webapp
    03/18/2015  01:03 PM    <DIR>          grunt-cli
    03/17/2015  03:41 PM    <DIR>          gulp
    02/05/2015  12:21 PM    <DIR>          npm
    03/18/2015  09:36 AM    <DIR>          npm-check
    03/17/2015  03:41 PM    <DIR>          yo

Yo doctor is also happy:

    C:\Users\riesbeck\workspace>yo doctor

    Yeoman Doctor
    Running sanity checks on your system

    √ Global configuration file is valid
    √ NODE_PATH matches the npm root
    √ No .bowerrc file in home directory
    √ No .yo-rc.json file in home directory

    Everything looks all right!

What else can I check? Here's the requested platform info. NODE_PATH is not set and there's no gruntfile.js. This is all part of a new setup to use yeoman with gulp and angular. 

    C:\Users\riesbeck\workspace>yo --version && echo %PATH% %NODE_PATH% && node -e "console.lo
    g(process.platform, process.versions)" && type Gruntfile.js
    1.4.6
    C:\Coding\Ruby\Ruby193\bin;C:\Program Files\Java\jdk1.7.0_51\bin;C:\Coding\Java\apache\db-derby-10.10.1.1-bin\bin;C:\Coding\Java\apache\apache-ant-1.9.4\bin;c:\Users\riesbeck\\bin;C:\Users\riesbeck\AppData\Local\Box\Box Edit\;C:\Users\riesbeck\AppData\Local\.meteor;C:\Program Files\MongoDB\Server\3.0\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\SlikSvn\bin;C:\Coding\Python\Python27;C:\Coding\Python\Python27\Scripts;C:\Program Files x86)\Git\cmd;C:\Users\riesbeck\bin\;C:\Users\riesbeck\AppData\Roaming\npm;C:\Program Files (x86)\nodejs\;C:\Coding\HashiCorp\Vagrant\bin %NODE_PATH%
    win32 { http_parser: '1.0',
      node: '0.10.36',
      v8: '3.14.5.9',
      ares: '1.9.0-DEV',
      uv: '0.10.30',
      zlib: '1.2.8',
      modules: '11',
      openssl: '1.0.1l' }
    The system cannot find the file specified.

**Comment by SBoudrias** [comment]
You can manually set NODE_PATH to `C:\Program Files (x86)\nodejs\node_modules`.

As to why you have the issue, I don't know, but my guess is that `npm prefix` isn't the value you expect. Maybe you have two versions of npm installed and they're not installing in the same directory or something like that.

**Comment by criesbeck** [comment]
Thanks very much for the prompt response! I did this

   set NODE_PATH="C:\Program Files (x86)\nodejs\node_modules"

Alas, it didn't fix the problem, and doctor became unhappy. As I read the message, it's saying that path is already there in the npm root

    C:\Users\riesbeck\workspace>yo --help
    Usage: yo GENERATOR [args] [options]

    General options:
      -h, --help     # Print generator's options and usage
      -f, --force    # Overwrite files that already exist

    Available Generators:


    C:\Users\riesbeck\workspace>yo doctor

    Yeoman Doctor
    Running sanity checks on your system

    √ Global configuration file is valid
    √ No .bowerrc file in home directory
    √ No .yo-rc.json file in home directory
    x
    npm root value is not in your NODE_PATH

    [Info]
      NODE_PATH = "C:\Program Files (x86)\nodejs\node_modules"
      npm root  = C:\Program Files (x86)\nodejs\node_modules

    [Fix] Append the npm root value to your NODE_PATH variable
      If you're using cmd.exe, run this command to fix the issue:
        setx NODE_PATH "%NODE_PATH%;C:\Program Files (x86)\nodejs\node_modules"
      Then restart your command-line. Otherwise, you can setup NODE_PATH manually:
        https://github.com/sindresorhus/guides/blob/master/set-environment-variables.md#window
    s


    Found potential issues on your machine :(

**Comment by criesbeck** [comment]
Oops. My error with those string quotes.

  set NODE_PATH=C:\Program Files (x86)\nodejs\node_modules

fixes the yo --help 

Now to figure out why

THANKS!
