### ISSUE TITLE
yo installed but don't run

### ISSUE THREAD

**Issue by fbsrosa** [yeoman/yo#311]
Hi,

May you help me please?
Installed 'yo' but when I give any command, it gives me the follow:

Error: EACCES, permission denied '/root/.config/configstore/insight-yo.yml'
You don't have access to this file.
    at Object.fs.openSync (evalmachine.<anonymous>:439:18)
    at Object.fs.readFileSync (evalmachine.<anonymous>:290:15)
    at Object.create.all.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:34:29)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:36:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:117:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
------------------------------------------------------------
The file "insight-yo.yml" don't exist at the folder. 

And below is the result of "yo --version && echo $PATH $NODE_PATH && node -e 'console.log(process.platform, process.versions)' && cat Gruntfile.js" :

1.4.6
/usr/local/rvm/gems/ruby-2.2.0/bin:/usr/local/rvm/gems/ruby-2.2.0@global/bin:/usr/local/rvm/rubies/ruby-2.2.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
linux { http_parser: '1.0',
  node: '0.10.37',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.36',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1l' }
cat: Gruntfile.js: No such file or directory

Thank You very much.

**Comment by kevva** [comment]
Did you install as `root`?

**Comment by fbsrosa** [comment]
Yes, because when I tried to install as not sudo/root it didn't run.

**Comment by kevva** [comment]
Well, then you're problem is bigger. You should never install anything from npm as `sudo`. Read https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md.

**Comment by fbsrosa** [comment]
I readed do not use to use npm as root, and tried to install 'yo' as not root, but 'yo' didn't run and gave me some dozen lines of ERR, so I wnt to root.

**Comment by fbsrosa** [comment]
At folder "/root/.config/configstore/" there are two files installed by 'yo'. "insight-bower.yml" and "update-notifier-bower.yml", but "insight-yo.yml" don't exist.

**Comment by fbsrosa** [comment]
I'm tired, spent some six hours with this problem and I can't think straight anymore. Thank You very much for your interest. I'll try another way to do what I want. Yeoman is not working here an I will uninstall it.

**Comment by SBoudrias** [comment]
Post your trace, we can't help you on error without details.

**Comment by fbsrosa** [comment]
Thank you for your attention.
There's no need to think about it anymore as I uninstalled Yeoman and 
will not use it.
Wasted six hours yesterday and was enough.
