### ISSUE TITLE
Create global overrides file, .yorc

### ISSUE THREAD

**Issue by aendrew** [yeoman/yo#312]
My team uses Yeoman *a lot*, and there are things common to all projects that would be great to override. For instance, I always forget to change the Yeoman favicon, and it would be nice if there was a way to always use the favicon my team uses for projects by default.

Another use case: I use `generator-angular` a lot, and it would be nice if I could specify a different `index.html` pre-populated with my Google Analytics code (another thing I [chronically forget to change](http://aendrew.tumblr.com/post/85034300107/my-first-year-at-the-times-and-sunday-times)), possibly even a bower.json file pre-populated with all the Angular modules I commonly use. Or if I have a documentation template for my README.txt files, I can supply that instead and be a step ahead on documentation.

While all this could be done by creating your own customised fork, you then have to keep that fork updated if you want any new features added by the parent generator, and forking every generator I use just to override the favicon is kind of a pain.

To this end, I propose creating a `.yorc` file format, that Yeoman walks up the domain tree looking for and parses on scaffold creation. Could look like this:

```
{
"overrides":  {
  "favicon.ico": {
    "replace": "~/etc/yeoman/favicon.ico"
  },
  "index.html": {
    generators: [
      "generator-angular",
      "generator-angular-fullstack"
    ],
    "regex": "s/UA-XXXXX-X/UA-12345-6/i"
  },
  ".jshintrc": {
    "diff": "@@ -17,7 +17,10 @@\n \"jquery\": true,\n \"globals\": {\n \"Tabletop\": true,\n- \"_\": true\n+ \"_\": true,\n+ \"console\": true,\n+ \"c3\": true,\n+ \"Handlebars\": true\n }"
  }
}
```

I'm sure there's other functionality that could be built into this beyond simply replacing files; in addition to overrides, `.yorc` could, for instance, have default instructions for various generator (E.g., always elect to use `node-sass` when using `generator-angular`). 

Any thoughts? The other way to provide this level of functionality would be to create a plugin API that extends various generators or `yo` more generally, but that seems like a lot more work (apologies if this already exists and I've failed to find it).

Thanks!

**Comment by aendrew** [comment]
Should note, I'm totally willing to write a PR for this if there's any appetite for such a feature. :smile:

**Comment by SBoudrias** [comment]
You should check composability features.

http://yeoman.io/authoring/composability.html

Compose with generator-angular and write custom functions to execute the specific changes you needs.

**Comment by aendrew** [comment]
@SBoudrias Ah, that's indeed looks like what I was wanting. Apologies for missing that part of the documentation!
