### ISSUE TITLE
npm install failed (multiple times)

### ISSUE THREAD

**Issue by kloyl** [yeoman/yo#315]
npm install of yeoman failed multiple times over 2 days. Other software packages installed successfully during same period i.e. grunt, gulp, bootstrap.

I re-installed npm, followed npm trouble shooting instructions: no luck.

best regards,
kenneth lea
lea.kenneth@gmail.com

**Comment by arthurvr** [comment]
Can you give us some more information? In the progress of the installation, where are you having troubles? Is npm throwing some kind of error message? If so, could you please post that one so we can see what's going wrong?

**Comment by sindresorhus** [comment]
npm support: https://github.com/npm/npm/issues

**Comment by kloyl** [comment]
re: yeoman npm install failed  - lea.kenneth@gmail.com
Thank you for your timely response, its appreciated.
On windows 8.1 at cmd prompt: npm install -g yeoman
a fragment of the npm-debug.log follows:

\AppData\Roaming\npm-cache\grunt\0.4.0-a\package\package.json not in flight; writing
2133 verbose afterAdd C:\Users\Kenneth Lea\AppData\Roaming\npm-cache\grunt\0.4.0-a\package\package.json written
2134 http fetch 406 http://github.com/yeoman/generators/archive/0.9.5.tar.gz
2135 error fetch failed http://github.com/yeoman/generators/archive/0.9.5.tar.gz
2136 warn retry will retry, error on last attempt: Error: fetch failed with status code 406
2137 info retry fetch attempt 2 at 5:32:42 PM
2138 info attempt registry request try #1 at 5:32:42 PM
2139 http fetch GET http://github.com/yeoman/generators/archive/0.9.5.tar.gz
2140 http fetch 406 http://github.com/yeoman/generators/archive/0.9.5.tar.gz
2141 error fetch failed http://github.com/yeoman/generators/archive/0.9.5.tar.gz
2142 warn retry will retry, error on last attempt: Error: fetch failed with status code 406
2143 info retry fetch attempt 3 at 5:33:43 PM
2144 info attempt registry request try #1 at 5:33:43 PM
2145 http fetch GET http://github.com/yeoman/generators/archive/0.9.5.tar.gz
2146 http fetch 406 http://github.com/yeoman/generators/archive/0.9.5.tar.gz
2147 error fetch failed http://github.com/yeoman/generators/archive/0.9.5.tar.gz
2148 verbose about to build C:\Users\Kenneth Lea\AppData\Roaming\npm\node_modules\yeoman
2149 verbose unlock done using C:\Users\Kenneth Lea\AppData\Roaming\npm-cache\_locks\yeoman-dcafb91e6795ba2c.lock for C:\Users\Kenneth Lea\AppData\Roaming\npm\node_modules\yeoman
2150 verbose stack Error: fetch failed with status code 406
2150 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\fetch.js:51:14)
2150 verbose stack     at Request.emit (events.js:107:17)
2150 verbose stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1176:10)

**Comment by SBoudrias** [comment]
> http fetch 406 http://github.com/yeoman/generators/archive/0.9.5.tar.gz

npm is trying to fetch that url (which doesn't exist). My guess is you're pointing to a github tarball instead of a version.

**Comment by kloyl** [comment]
re: yeoman install failure,

Why would I have an invalid URL. I entered the command as specified on the Yeoman sit.

npm install -g yeoman

Why would this send me to the wrong URL.

best regards,
k

**Comment by SBoudrias** [comment]
`npm install -g yeoman` is deprecated since multiple years. I'm pretty sure you haven't found this on our website.

http://yeoman.io for documentation.
