### ISSUE TITLE
Question Repeating

### ISSUE THREAD

**Issue by denzelwamburu** [yeoman/yo#316]
Am not sure if this error is tied to one generator or one OS , since am running Ubuntu 14.04 and run a meanjs generator, the description questions are repeating themselves.Each time a letter is input, the whole question just reappears.

**Comment by denzelwamburu** [comment]
![yeomanerro2](https://cloud.githubusercontent.com/assets/6532631/7143991/2d308ce8-e2eb-11e4-8dd7-b50d433e9a3d.png)
![yeomanerror](https://cloud.githubusercontent.com/assets/6532631/7143998/4059b416-e2eb-11e4-9839-2c9f52bd819d.png)

**Comment by SBoudrias** [comment]
That's because of the line wrap. It's a known Inquirer.js issue, but it is low importance as it's an edge case.

Feel free to work on a pull request for Inquirer.js if you want to see this resolved faster. https://github.com/SBoudrias/Inquirer.js/issues/6

**Comment by denzelwamburu** [comment]
@SBoudrias Thanks for the clarification, guess we should work on the Inquire.js first :)
