### ISSUE TITLE
.config/.yo-rc.json

### ISSUE THREAD

**Issue by shannonmoeller** [yeoman/yo#321]
As more and more tools have become best-practice when authoring npm modules, from `package.json` to `.*rc` to `*file.js`, the root directory of projects has become a very loud place. This dot-noise pushes README content farther and farther down the main page of git repos.

![screenshot 2015-05-01 21 41 51](https://cloud.githubusercontent.com/assets/155164/7439468/e8f2ff9e-f04a-11e4-8c1b-4248379053e9.png)

What if the above could optionally be simplified to the following?

![screenshot 2015-05-01 21 50 12](https://cloud.githubusercontent.com/assets/155164/7439513/179455c2-f04c-11e4-9577-c3b73c2b01c3.png)

This is a simple example and that's already about a 30% vertical space savings. I started the conversation over in the [npm repo](https://github.com/npm/npm/issues/8159), and already submitted an issue for [`findup-sync`](https://github.com/cowboy/node-findup-sync/issues/17), but I wanted to get visibility here.

**Comment by arthurvr** [comment]
I'm :-1: for now but would reconsider this when this system gets a little more usage. I don't see much benefit anyways, the argument of the vertical space isn't worth much for me. I mean... it's as easy as scrolling :)

**Comment by addyosmani** [comment]
I'm with Arthur on this one. Sorry. I don't see this as being a particularly bad UX issue and it's solved by scrolling, so... :-1:

**Comment by sindresorhus** [comment]
I wouldn't mind it, but I've seen it tried multiple times before and it never goes anywhere. I hope you succeed though. For now, there's https://github.com/sindresorhus/github-hide-files

**Comment by shannonmoeller** [comment]
@arthurvr @addyosmani GitHub is only one of many places that a list of files is displayed, simply the most convenient for illustration purposes. `ls` much? :)

@sindresorhus Thanks for the vote of confidence.

Thanks, all, for the consideration.

**Comment by sindresorhus** [comment]
@shannonmoeller `ls` doesn't display dotfiles by default.

**Comment by shannonmoeller** [comment]
@sindresorhus Quite right. :) The first thing I do when I setup a new computer is to show all files, unhide extensions, and alias `ls` to `ll -Al`. I suppose I've made my bed in that regard. I'd like to think that the existence of the XDG standard shows I'm not alone, but I'll quit beating a dead horse. Thanks again.
