### ISSUE TITLE
Yo did not work successfully on Windows 8.1

### ISSUE THREAD

**Issue by rahul-desai3** [yeoman/yo#322]
I have a directory where in I have given all rights to all users as of now.

I am following this tutorial: https://www.youtube.com/watch?v=OhPFgqHz68o. I have setup the backend with Node.js which had no problem.

When I started with the frontend, all I tried to do was:

`mkdir client`
`cd client`
`npm install -g yo`
`npm install -g generator-angular`
`yo angular`

I answered all of the questions asked and then it began its process. Somewhere in between it said that there is a conflict and asked if it should overwrite `package.json`. I agreed to it by hitting `Enter` key since I did not see any other option. 

I could see a lot of errors in the process.

Here is the `npm-debug.log`: https://gist.githubusercontent.com/rahul-desai3/9f1d1d0a1ddeec2a4ad0/raw/npm-debug.log

What am I doing wrong here?

**Comment by SBoudrias** [comment]
Looks like you can't connect to the npm registry. Maybe proxy issues or something.

It's not related to yeoman. Open an issue on npm if you can't figure out, but the log is pretty explicit if you read it.
