### ISSUE TITLE
Static files accessed incorrectly

### ISSUE THREAD

**Issue by smithjessk** [yeoman/yo#324]
In my MEAN app, I have two routes, `/:room` and `/:room/manage`. Both of these routes serve an HTML template that accesses static files. However, `/:room/manage`, returns a 404 when it tries to grab these files. For instance, with `:room = 0`, it tries to access `/0/lib/bootstrap/...` instead of `/lib/bootstrap/...`.

This is because there is no leading slash in the generated `layout.server.view.html`. That is, the problem was fixed for me by changing 

```
{% for cssFile in cssFiles %}<link rel="stylesheet" href="{{cssFile}}">{% endfor %}
```

to 

```
{% for cssFile in cssFiles %}<link rel="stylesheet" href="/{{cssFile}}">{% endfor %}
```

Hope this helps.

**Comment by SBoudrias** [comment]
Open this issue on the generator you've used. `yo` is only the tool running these generators, it doesn't know anything of what is generated.
