### ISSUE TITLE
Failed at the yo@1.4.6 postinstall script 'yodoctor'.

### ISSUE THREAD

**Issue by shaunstanislaus** [yeoman/yo#325]
shaunstanislaus@Master ~ (master) $ yo
-bash: yo: command not found
shaunstanislaus@Master ~ (master) $ grunt
grunt-cli: The grunt command line interface. (v0.1.13)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
shaunstanislaus@Master ~ (master) $ sudo npm install -g yo
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.4.6 postinstall /usr/local/lib/node_modules/yo
> yodoctor

env: node: No such file or directory
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! yo@1.4.6 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the yo@1.4.6 postinstall script 'yodoctor'.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor

npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

**Comment by SBoudrias** [comment]
Please search for issues before opening new one. This have been reported multiple time.

This is an issue with npm. Open an issue on their repository.

Also, make sure you're using the latest version and retry installing. If it doesn't work, you can alternatively install yodoctor globally manually before installing yo:

```
npm -g install yodoctor
npm -g install yo
```

**Comment by shaunstanislaus** [comment]
You asked me to install yo doctor, yo doctor was installed fine and didnt detect any issues but doing the second command after installing yo, i still can't install. NPM said it was Yo's issue and wasn't NPM.

please kindly help to resolve this issue

shaunstanislaus@Master /usr/local/lib/node_modules (master) $ yodoctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory

Everything looks all right!
shaunstanislaus@Master /usr/local/lib/node_modules (master) $ sudo npm -g install yo
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.4.6 postinstall /usr/local/lib/node_modules/yo
> yodoctor

env: node: No such file or directory
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "-g" "install" "yo"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! yo@1.4.6 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the yo@1.4.6 postinstall script 'yodoctor'.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm-debug.log
shaunstanislaus@Master /usr/local/lib/node_modules (master) $

**Comment by SBoudrias** [comment]
> NPM said it was Yo's issue and wasn't NPM.

npm just assume any failures here is due to the package. But in this case it's apparently a race condition in their dependency install process.

**Comment by shaunstanislaus** [comment]
so for now i can't use yo, and there isn't any other way to fix it?

**Comment by SBoudrias** [comment]
Install yodoctor globally.

**Comment by shaunstanislaus** [comment]
i installed it globally, yet it isn't working.

**Comment by SBoudrias** [comment]
Well I gave you some direction of potential troubleshooting. It's now time for you to help yourself further.

**Comment by tossp** [comment]
`npm -g install yeoman-doctor`
can fix it

**Comment by cannibal-dance** [comment]
I tried your fix tosspig! It worked in the sense that even $npm install -g yodoctor was not working. So with your link I did get yo doctor installed but I still have the same problem as OP. It will not install Yo. 

Jesses-Air:~ jesselawson$ npm install -g yo
/Users/jesselawson/.node_modules_global/bin/yo -> /Users/jesselawson/.node_modules_global/lib/node_modules/yo/lib/cli.js

> yo@1.5.0 postinstall /Users/jesselawson/.node_modules_global/lib/node_modules/yo
> yodoctor

sh: yodoctor: command not found
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! yo@1.5.0 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the yo@1.5.0 postinstall script 'yodoctor'.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jesselawson/npm-debug.log
Jesses-Air:~ jesselawson$

**Comment by hariDasu** [comment]
yeah this doesn't work. posters telling people to look up issues are not helping at all, considering the real issue is with YEOMAN's website, which claims installing yeoman is as simple as just typing in npm install -g yo. this is wrong.
