### ISSUE TITLE
Why am I unable to run yo angular successfully?

### ISSUE THREAD

**Issue by kalyandechiraju** [yeoman/yo#326]
I am running a windows 8.1 64-bit machine.

Node and npm were installed.(latest versions 0.12.2 and 2.7.4)

Installed YO BOWER GRUNT-CLI GULP GENERATOR-ANGULAR correctly.

Now when I run "yo angular", the project files are being generated and bower install and npm install are running. Till now its fine.

bower install goes well. But npm install stuck in middle and gives different ERR (sample - ERR registry parsing json sometimes different) and finally it freezes executing phantomjs.exe forever. If I quit that cmd prompt and run grunt in that folder, it says grunt not installed.

This happened every time I run this. Tried almost all googled suggestions. One more thing is that I cannot delete that folders created by yo angular.

Kindly help me run it completely

**Comment by SBoudrias** [comment]
Open issue on generator-angular.

This is an issue with npm install.

You can run `yo angular --skip-install` to not run the install process. Then run `npm install` and `bower install` manually, if you can't figure out what's wrong, then ask question on stackoverflow or the tool bug tracker.

**Comment by eddiemonge** [comment]
Oh Windows, stop creating so many problems.
