### ISSUE TITLE
About generator-angular

### ISSUE THREAD

**Issue by StarryF** [yeoman/yo#328]
After i used this sentence: sudo npm install -g generator-angular. And then ,there are some WARN and

generator-angular@0.11.1 /usr/local/lib/node_modules/generator-angular
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── yosay@1.0.3 (string-length@1.0.0, ansi-regex@1.1.1, ansi-styles@2.0.1, word-wrap@1.0.3, strip-ansi@2.0.1, pad-component@0.0.1, minimist@1.1.1, taketalk@1.0.0, chalk@1.0.0)
├── wiredep@2.2.2 (propprop@0.3.0, minimist@1.1.1, lodash@2.4.2, through2@0.6.5, glob@4.5.3, bower-config@0.5.2)
└── yeoman-generator@0.16.0 (dargs@0.1.0, isbinaryfile@2.0.4, diff@1.0.8, debug@0.7.4, class-extend@0.1.1, rimraf@2.2.8, findup-sync@0.1.3, text-table@0.2.0, mime@1.2.11, async@0.2.10, mkdirp@0.3.5, shelljs@0.2.6, chalk@0.4.0, underscore.string@2.3.3, iconv-lite@0.2.11, glob@3.2.11, lodash@2.4.2, file-utils@0.1.5, cheerio@0.13.1, request@2.30.0, download@0.1.19, inquirer@0.4.1)

Finally, I use yo to see my generators, but there is no angular. Why ?

**Comment by SBoudrias** [comment]
Run `yo doctor`.

**Comment by SBoudrias** [comment]
Also don't run npm with sudo

**Comment by StarryF** [comment]
Thank you!
