### ISSUE TITLE
Can't run Yeoman on Yosemite 10.10.3

### ISSUE THREAD

**Issue by gregbriandavis** [yeoman/yo#332]
I'm using Yosemite 10.10.3, Homebrew 0.9.5, Node v0.12.3, NPM 2.9.1

For whatever reason, I can't get Yeoman to properly install. The install seems to go fine, no errors, but when I check to confirm the install it wont give me the --version, nor can I execute the yo function...

![screen shot 2015-05-24 at 10 44 58 pm](https://cloud.githubusercontent.com/assets/5198793/7791258/264b694e-026b-11e5-938b-0f3385246538.png)

I've opened the .bashrc (have to use sudo to be able to open + save it). Without sudo I can't save the changes.

>sudo nano /.bashrc

The bashrc file reads:

![screen shot 2015-05-24 at 10 57 57 pm](https://cloud.githubusercontent.com/assets/5198793/7791262/3069648a-026b-11e5-9ea7-8c1603158ba4.png)

I've tried installing Node thru Homebrew first and found out about this issue which I couldnt resolve either. https://gist.github.com/DanHerbert/9520689

Since that didn't I blew everything away in terminal including node, npm, and homebrew.

Now I'm stuck, npm lets me install packages like grunt-cli, bower, and yeoman, but any time I try calling those packages I get:

>-bash: yo: command not found

I'm assuming it has something to do with the /.bashrc contents, somebody help :(

**Comment by sindresorhus** [comment]
http://bit.ly/1ApeH5t
