### ISSUE TITLE
Font directory issues

### ISSUE THREAD

**Issue by COMPsmith** [yeoman/yo#333]
Im having issues trying to get all my fonts to work after I grunt build. When I "grunt serve" my app fonts works fine. 

The issue is some of my bower components css files use a different directory for fonts than what is expected for grunt. 

Grunt wants fonts in app/styles/fonts/ if they are to be coppied durring the build

I have a custom font placed in app/font (i can change this in my main css so not a big issue)
@font-face {
  font-family: 'iec_unicoderegular';
  src: url('../font/Unicode_IEC_symbol/Unicode_IEC_symbol.eot');
  src: url('../font/Unicode_IEC_symbol/Unicode_IEC_symbol.eot?#iefix') format('embedded-opentype'),
       url('../font/Unicode_IEC_symbol/Unicode_IEC_symbol.woff') format('woff'),
       url('../font/Unicode_IEC_symbol/Unicode_IEC_symbol.ttf') format('truetype'),
       url('../font/Unicode_IEC_symbol/Unicode_IEC_symbol.svg#iec_unicoderegular') format('svg');
  font-weight: normal;
  font-style: normal;

materialize.css wants fonts in ../font/roboto/ and ../font/material-design-icons
@font-face {
  font-family: "Roboto";
  src: url("../font/roboto/Roboto-Thin.woff2") format("woff2"), url("../font/roboto/Roboto-Thin.woff") format("woff"), url("../font/roboto/Roboto-Thin.ttf") format("truetype");
  font-weight: 200; }
@font-face {
  font-family: "Material-Design-Icons";
  src: url("../font/material-design-icons/Material-Design-Icons.eot?#iefix") format("embedded-opentype"), url("../font/material-design-icons/Material-Design-Icons.woff2") format("woff2"), url("../font/material-design-icons/Material-Design-Icons.woff") format("woff"), url("../font/material-design-icons/Material-Design-Icons.ttf") format("truetype"), url("../font/material-design-icons/Material-Design-Icons.svg#Material-Design-Icons") format("svg");

materialdesignicons.css wants fonts in ../fonts/
@font-face {
  font-family: 'MaterialDesignIcons';
  src: url("../fonts/materialdesignicons-webfont.eot?v=1.0.62");

I do not want to change the css in the bower components rather is there a change in my gruntfile.js that could take all the font sources and combine them then to one font file and modify the css during the build to reflect the changes? If not what is the best way to handle this issue? Thanks

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)

**Comment by kevva** [comment]
Additionally, describe which generator you're running into problems with.
