### ISSUE TITLE
yo --help mangles subgenerator names with colons

### ISSUE THREAD

**Issue by CExMAllen** [yeoman/yo#334]
I encountered an issue with `--help`. To make a long story short, I've created some subgenerators which have `:` in their names. This works great with the `composeWith` functionality to allow me to logically nest generator hierarchies. The issue comes when I try to use `yo --help` to list my generators. It comes from [here](https://github.com/yeoman/yo/blob/master/lib/cli.js#L82), where the generator names are split on `:` and only the first two parts are used. I've already fixed this in my local copy and since it's trivial and passes all tests I'll open a PR shortly.

note: I am anticipating that some people might disagree with the concept of having `:`s in sub-generator names at all, but I think that is a seperate issue. If they are not specifically disallowed then there is no reason not to fix the output for this case.

**Comment by SBoudrias** [comment]
If we can run `yo gen:foo:subname` then let's fix it.

**Comment by CExMAllen** [comment]
It does work, I've been using it for things like 

foo:foo-sub-command:foo-sub-command-sub-command 

so that users have a logical hierarchy

**Comment by CExMAllen** [comment]
tbh, I think it would be way cooler if sub generators could have sub generators, and then this would be moot. That said, this naming standard is a sort of workaround for me atm. :)
