### ISSUE TITLE
Unable to differentiate between empty arguments and undefined

### ISSUE THREAD

**Issue by olsonpm** [yeoman/yo#336]
yo <generator>

vs

    yo <generator> ""

will always pass undefined to a generator expecting an optional string argument.

There are various ways for me to get around it, so I don't think specifying my use-case is important.  I just feel this is unexpected behavior when compared with node's built-in capability of differentiating between undefined and empty string.

**Comment by eddiemonge** [comment]
This is also probably similar to `--optionname` vs `--optionname=foo`

**Comment by eddiemonge** [comment]
This should be opened at https://github.com/yeoman/generator or possibly https://github.com/SBoudrias/Inquirer.js/

**Comment by olsonpm** [comment]
Yeah the bug seems to exist in yeoman-environment.  My apologies.
