### ISSUE TITLE
bulkDirectory / template questions

### ISSUE THREAD

**Issue by atian25** [yeoman/yo#338]
1. how to skip some file when using `bulkDirectory`
2. how to skip conflict question when using `template` (no global force)
3. what is `process`?

**Comment by eddiemonge** [comment]
1. Why would you skip files?
2. there shouldn't be conflicts with the new write system but if there are, i dont know

take a look at the docs for [generator](https://github.com/yeoman/generator) and it should help. Also, these questions are better asked on stackoverflow.
