### ISSUE TITLE
Yeoman creating directories that are dozens of levels deep (on Windows)

### ISSUE THREAD

**Issue by sunil-c** [yeoman/yo#342]
For some reason when you scaffold something like Backbone.js it creates a folder structure so deep that Windows can't deal with it when you try and delete the top folder. I tried following the structure it created on my machine but it literally felt like it would never end -- I think I went at least 20 or more levels down.

It did this when scaffolded Polymer and then again with Backbone (on two different drives).

This was a brand new install of node, npm, and yeoman on a fresh OS install.

**Comment by arthurvr** [comment]
The "dozens of levels" are just npm dependencies.

> I tried following the structure it created on my machine but it literally felt like it would never end -- I think I went at least 20 or more levels down.

The windows file system has quite a bit of known issues for dealing with deep folders. Which unfortunately, we can't do anything about. It's a bug on their side, not ours.

I think chances are high you're in the same situations as https://github.com/npm/npm/issues/5641 or https://github.com/google/web-starter-kit/issues/489.

**Comment by sunil-c** [comment]
I guess I'll wait to see if a fix ever emerges. Yeoman seems like a very useful tool. I look forward to using it someday.

**Comment by sindresorhus** [comment]
There's an easy fix: http://www.ubuntu.com/download
