### ISSUE TITLE
Can't find generators under Win32 (reopened)

### ISSUE THREAD

**Issue by elparkino** [yeoman/yo#343]
https://github.com/yeoman/yo/issues/243

**Comment by SBoudrias** [comment]
Please give details that are unique to your case here. The other issue was 1 year ago so probably unrelated.

Also FWIW, it's an issue with your own setup. We have a lot of other windows user who're not having issue and we haven't made a release in the past two weeks.

**Comment by elparkino** [comment]
I'm sure it's probably my own set-up. I've discovered that grunt also can't find any of it's modules either. I have a feeling it has something to do with the path separator, but I can't be completely sure.

 I installed on windows with choclatey perhaps that has something to do with it. Still trying to figure it out.

**Comment by elparkino** [comment]
uninstalled node and all modules from my system and reinstalled the official MSI from the node home page, still getting the same issues.

not doing anything too strange:

yo doctor still says everything is good.
all modules installed locally to project
generator wont find any of the generators. 

If it's my personal setup then I can't for the life of me figure out what's wrong.

**Comment by SBoudrias** [comment]
Check your NODE_PATH value, and check if modules are installed in that folder.

If they're not, then you know what's wrong.

**Comment by elparkino** [comment]
I know the node pat is set correctly, and yo isn't able to find then in either the local modules or the global

I've tried installing them in both places, and just one or the other

nothing

**Comment by kevva** [comment]
@elparkino, yes, it is. I can't reproduce your problem on Windows.
