### ISSUE TITLE
yeoman installation error ->Your Node.js version is outdated.

### ISSUE THREAD

**Issue by rohitraja** [yeoman/yo#344]
workspace/workspace (master) $ npm install -g yo                                                                                        
 
> spawn-sync@1.0.11 postinstall /home/ubuntu/.nvm/v0.10.35/lib/node_modules/yo/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

/home/ubuntu/.nvm/v0.10.35/bin/yo -> /home/ubuntu/.nvm/v0.10.35/lib/node_modules/yo/lib/cli.js

> yo@1.4.7 postinstall /home/ubuntu/.nvm/v0.10.35/lib/node_modules/yo
> yodoctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ No .bowerrc file in home directory
✔ NODE_PATH matches the npm root
✖ Node.js version

Your Node.js version is outdated.
Upgrade to the latest version: https://nodejs.org

✔ No .yo-rc.json file in home directory
✔ npm version

Found potential issues on your machine :(
yo@1.4.7 /home/ubuntu/.nvm/v0.10.35/lib/node_modules/yo
├── titleize@1.0.0
├── array-uniq@1.0.2
├── figures@1.3.5
├── user-home@1.1.1

**Comment by sindresorhus** [comment]
The message says exactly what to do...
