### ISSUE TITLE
Getting the following errors when trying to use 'npm install -g yo' in command prompt

### ISSUE THREAD

**Issue by AzzyDude24601** [yeoman/yo#345]
My node is on version 0.12.4 and I have been able to successfully globally install bower and grunt. But when I attempt to use 'npm install -g yo' from an elevated command prompt, I get the following error: 

-----------------------------------------------------------------------------------------------------------------------------

> spawn-sync@1.0.11 postinstall C:\Program Files\nodejs\node_modules\yo\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! file ;C:\Windows\system32\cmd.exe
npm ERR! path ;C:\Windows\system32\cmd.exe
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn ;C:\Windows\system32\cmd.exe

npm ERR! spawn-sync@1.0.11 postinstall: `node postinstall`
npm ERR! spawn ;C:\Windows\system32\cmd.exe ENOENT
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.11 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log

-----------------------------------------------------------------------------------------------------------------------------

I have no idea what this means and I can't seem to fix it. Does anyone recognise these errors?

**Comment by SBoudrias** [comment]
```
npm ERR! Failed at the spawn-sync@1.0.11 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
```

**Comment by AzzyDude24601** [comment]
That doesn't help me in least. I have been able to install grunt and bower and a number of other things using NPM but Yo is getting these errors. How the hell are you supposed to troubleshoot the spawn-sync package. I don't even know what the hell a spawn-sync package is.

**Comment by SBoudrias** [comment]
You should open an issue on their project, the issue you experience is not directly related to yo.

**Comment by AzzyDude24601** [comment]
Is spawn-cycle not packaged with Yo? Does Yo not use spawn-cycle? Is spawn-cycle not inherently part of the Yo repo? I am trying to get 'npm install -g yo' to work. I am not trying to get 'npm install -g spawn-cycle' to work. If there is a relationship there, then it's because Yo requires it. Therefore it seems reasonable to open an issue on the Yo repo.

**Comment by SBoudrias** [comment]
Maybe for you, but it's out of our direct control. We do not own that repo.

So open an issue over there, the maintainers will fix it and release a new patch. And then installing yo will just work.
