### ISSUE TITLE
How to stop running generator

### ISSUE THREAD

**Issue by milan-kraus** [yeoman/yo#349]
Is there any way how to stop running generator + a way how to unit test this? For example: user starts the same generator in the same directory multiple times. I check if generator already ran and if yes, I want to stop the generator.

Currently I use `this.env.error()`, it works fine, but I have problems with unit testing.
Since `this.env.error()` throws error from asynchronous code, I cannot use try-catch. About two weeks ago this worked fine, because the error was swallowed (by yo CLI, I think), and all I had to do was to add listener to error event onto generator running context. But now the error is propagated into unit test and causes the test to fail.

I know I can add listener to error event onto generator environment, so I can catch the error, but then generator keeps running even after the error occured.

**Comment by SBoudrias** [comment]
A couple things:

Why would you want to prevent re-runs? What if someone wants to re-run with the latest version and check the diff? What if someone mess something up and want to reset the defaults configs? Re-running have legitimate uses, I don't see why you'd want to prevent it.

Second thing is, if you're going to prevent re-runs, throwing an error looks like a fine solution. You don't want this to be transparent. Users will just be wondering why the generator is not working and they won't figure it out. So throw an error with a relevant message so people know what they done wrong.

On the technical side, you close a node process using `process.exit()`. But *don't* do this.
