### ISSUE TITLE
Update generators that are installed with a git url (not in NPM registry)

### ISSUE THREAD

**Issue by yvele** [yeoman/yo#350]
Let's consider a generator that is not in NPM registry and that need to be installed with a git URL:

    npm install -g git://domain.com/scope/generator-foo.git

Now I would like to update it using `yo` with the **Update your generator** menu item, but I get the following error:

    yo
    ? 'Allo Yves! What would you like to do? Update your generators
    ? Generators to update: @scope/generator-foo
    npm ERR! Darwin 14.4.0
    npm ERR! argv "/Users/yves/.nvm/versions/node/v0.12.6/bin/node" "/Users/yves/.nvm/versions/node/v0.12.6/bin/npm" "install" "-g" "@scope/generator-foo"
    npm ERR! node v0.12.6
    npm ERR! npm  v2.11.2
    npm ERR! code E404
    
    npm ERR! 404 Not found : @scope/generator-foo
    npm ERR! 404
    npm ERR! 404 '@scope/generator-foo' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    I've just updated your generators. Remember, you can update
    a specific generator with npm by running:

    npm install -g generator-_______

Yes `'@scope/generator-foo' is not in the NPM registry.` on purpose.

`yo` is not aware that the generator is not in NPM registry and don't know the git URL to be able to update it.

Would adding a config within the generator containing update instructions (git URL, ..) a nice feature to have? (to make yo be able to update appropriately).

By the way, when update fails, yo still display the *I've just updated your generators* message.

PS: [Related StackOverflow question](http://stackoverflow.com/questions/31313437/using-yo-to-update-a-yeoman-generator-initially-installed-from-a-git-url)

**Comment by eddiemonge** [comment]
Can you open this as a new issue please: 

> By the way, when update fails, yo still display the I've just updated your generators message.

I'm not sure the value in adding code to do this. If it's simple maybe it adds to much branching logic I feel

**Comment by sindresorhus** [comment]
Open to it if it doesn't requrie too many changes and can happen automagically, but should not require an option.

**Comment by SBoudrias** [comment]
We just spawn `npm update <x>` to update generator. This would be on npm side to handle updating packages installed from git.
