### ISSUE TITLE
Parts of the react-reflux-webpack not installing.

### ISSUE THREAD

**Issue by nickbae91** [yeoman/yo#351]
Hi, I'm a beginner developer and tried setting up react-reflux-webpack, and got a bunch of errors. Not sure if they're critical components, but I thought I should get it checked up. Thanks a lot for the patience!!

--------CMDER Output-----------------

WARNING: Enable-GitColors is Obsolete and will be removed in a future version of posh-git.
Identity added: /c/Users/Jbbae/.ssh/id_rsa (/c/Users/Jbbae/.ssh/id_rsa)
C:\Users\Jbbae\Documents\GitHub
λ mkdir compass

    Directory: C:\Users\Jbbae\Documents\GitHub

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
d----         7/23/2015  10:33 PM            compass

C:\Users\Jbbae\Documents\GitHub
λ npm install -g generator-react-reflux-webpack
npm WARN peerDependencies The peer dependency yo@>=1.2.0 included from generator-react-reflux-webpack will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
generator-react-reflux-webpack@1.1.14 C:\Users\Jbbae\AppData\Roaming\npm\node_modules\generator-react-reflux-webpack
└── yeoman-generator@0.17.7 (dargs@2.1.0, isbinaryfile@2.0.4, class-extend@0.1.1, diff@1.4.0, text-table@0.2.0, underscore.string@2.4.0, mime@1.3.4, async@0.9.2, debug@1.0.4, grouped-queue@0.3.0, cross-spawn@0.2.9, chalk@0.5.1, nopt@3.0.3, run-async@0.1.0, shelljs@0.3.0, mkdirp@0.5.1, glob@4.5.3, file-utils@0.2.2, iconv-lite@0.4.11, rimraf@2.4.2, findup-sync@0.1.3, github-username@1.1.1, download@1.0.7, lodash@2.4.2, cheerio@0.17.0, request@2.60.0, gruntfile-editor@0.2.0, inquirer@0.7.3)
C:\Users\Jbbae\Documents\GitHub
λ cd compass
C:\Users\Jbbae\Documents\GitHub\compass
λ yo react-reflux-webpack

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Out of the box I include Webpack, Reflux, and some default React components.

? Would you like to include react-router? Yes
? Would you like to include Immutable.js? Yes
? Would you like to include superagent (a HTTP lib)? Yes
? Which styles language you want to use? SASS
   create src\index.html
   create package.json
   create webpack.config.js
   create webpack.dist.config.js
   create Gruntfile.js
   create .gitignore
   create src\styles\main.css
   create src\styles\normalize.css
   create src\images\yeoman.png
   create karma.conf.js
   create .editorconfig
   create .jshintrc
   create src\favicon.ico
   create src\scripts\actions\index.js
   create src\scripts\stores\index.js
   create src\scripts\stores\RouterStore.js
   create test\.jshintrc
   create test\helpers\phantomjs-shims.js
   create test\helpers\react\addons.js
   create src\scripts\components\CompassApp.js
   create test\spec\components\CompassApp.js
   create src\scripts\components\main.js

I'm all done. Running npm install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN peerDependencies The peer dependency file-loader@* included from url-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency jshint@^2.5.0 included from jshint-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency babel-core@* included from babel-loader will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! git clone --template=C:\Users\Jbbae\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/lox/sass-graph.git C:\Users\Jbbae\AppData\Roaming\npm-cache\_git-remotes\https-github-com-lox-sass-graph-git-70b89faa: Cloning into bare repository 'C:\Users\Jbbae\AppData\Roaming\npm-cache\_git-remotes\https-github-com-lox-sass-graph-git-70b89faa'...
npm ERR! git clone --template=C:\Users\Jbbae\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/lox/sass-graph.git C:\Users\Jbbae\AppData\Roaming\npm-cache\_git-remotes\https-github-com-lox-sass-graph-git-70b89faa: fatal: Unable to find remote helper for 'https'
npm WARN optional dep failed, continuing fsevents@0.3.6
/

> phantomjs@1.9.17 install C:\Users\Jbbae\Documents\GitHub\compass\node_modules\karma-phantomjs-launcher\node_modules\phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip
Saving to C:\Users\Jbbae\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Receiving...
- [==================================------] 84% 0.0s/
Extracting zip contents
Removing C:\Users\Jbbae\Documents\GitHub\compass\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\Jbbae\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1437705882729\phantomjs-1.9.8-windows -> C:\Users\Jbbae\Documents\GitHub\compass\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\Jbbae\Documents\GitHub\compass\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom\phantomjs.exe
npm WARN optional dep failed, continuing fsevents@0.3.6
npm WARN optional dep failed, continuing fsevents@0.3.6
|

> ws@0.4.32 install C:\Users\Jbbae\Documents\GitHub\compass\node_modules\webpack-dev-server\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
C:\Users\Jbbae\Documents\GitHub\compass\node_modules\webpack-dev-server\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
npm WARN prefer global babel@4.7.16 should be installed with -g

> ws@0.4.32 install C:\Users\Jbbae\Documents\GitHub\compass\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\Jbbae\Documents\GitHub\compass\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Jbbae\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror https://github.com/lox/sass-graph.git C:\Users\Jbbae\AppData\Roaming\npm-cache\_git-remotes\https-github-com-lox-sass-graph-git-70b89faa
npm ERR! Cloning into bare repository 'C:\Users\Jbbae\AppData\Roaming\npm-cache\_git-remotes\https-github-com-lox-sass-graph-git-70b89faa'...
npm ERR! fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jbbae\Documents\GitHub\compass\npm-debug.log
C:\Users\Jbbae\Documents\GitHub\compass
λ

**Comment by eddiemonge** [comment]
This is a npm issue. try running npm install again to fix it.
