### ISSUE TITLE
Can anyone tell me anything about "unicorn approved"?

### ISSUE THREAD

**Issue by techird** [yeoman/yo#353]
![image](https://cloud.githubusercontent.com/assets/1901286/8923552/c0e82564-3524-11e5-99c7-6c48432b1795.png)

What is that "unicorn approved" on `README`?

**Comment by SBoudrias** [comment]
Unicorns love Yeoman and they approved our project.

So they'd allowed us to add their badge - they're rad!

More info http://shields.io/

**Comment by techird** [comment]
@SBoudrias pretty awesome!
