### ISSUE TITLE
yo can't recognize private yeoman generator?

### ISSUE THREAD

**Issue by adcentury** [yeoman/yo#356]
I have a private yeoman generator on my gitlab.

After using `npm install -g [url_to_my_generator]`, I found that yo can't recognize it.

But when I clone it to local and then use `npm install && npm link`, it works fine and appears in "Available Generators".

Here is my generator's package.json
```json
{
  "name": "generator-my-generator",
  "version": "0.0.1",
  "description": "xxx",
  "keywords": [
    "yeoman-generator",
    "generator"
  ],
  "author": {
    "name": "xxx",
    "email": "xxx",
    "url": "xxx"
  },
  "main": "app/index.js",
  "repository": {
    "type": "git",
    "url": "git+ssh://xxx/generator-my-generator.git"
  },
  "dependencies": {
    "yeoman-generator": "^0.19.0",
    "chalk": "^1.0.0",
    "yosay": "^1.0.2"
  },
  "devDependencies": {},
  "files": [
    "app"
  ]
}
```

My environments:
```
OS: Windows 7
yo: 1.4.7
npm: 2.13.5
```

**Comment by SBoudrias** [comment]
Where does npm install packages from git?

**Comment by adcentury** [comment]
Git Bash. (which is actually a MingW)

BTW, the generator installed correctly .

```
$ npm ls -g --depth=0
c:\Program Files\nodejs
├── anyproxy@3.6.0
├── babel@5.8.21
├── browserify@10.2.4
├── generator-express@2.7.2
├── generator-generator@0.8.1
├── generator-my-generator@0.0.1 (git+ssh://git@xxx:xxx/gen
erator-my-generator.git#8d64f60a630149fd373ca92fada6dcfc4590f485)
```

**Comment by adcentury** [comment]
I have fixed it.

As I put the app folder into generators folder, the `files` property in package.json should be `["generators"]` (`["generators/app"] also works`).

Thanks for replying. @SBoudrias
