### ISSUE TITLE
How can I specify a runtime for the generator?

### ISSUE THREAD

**Issue by ghaiklor** [yeoman/yo#359]
I would like to include Babel runtime for the generator, so I able to write code in ES6 syntax. How can it be achieved?

Example: `yo generator-my-generator --require babelhook.js`.

Or `.yo.rc` with the following content:

```
{
  "require": "babelhook.js"
}
```

Thanks!

**Comment by SBoudrias** [comment]
Just use a generator supporting es6 code like generator-node.

Yo and Yeoman are not doing any magic to allow/disallow the use of es6. It's just javascript and the usual workflow.

**Comment by ghaiklor** [comment]
@SBoudrias generator-node sources is written with ES5 syntax. I mean to write ES6 syntax in generator steps itself. In generators/app/index.js, etc...

**Comment by SBoudrias** [comment]
@ghaiklor Just use the generator-node workflow to write your own generator. Build you babel code and publish the compiled code. You don't publish packages to NPM with babel compilation at runtime.

**Comment by ghaiklor** [comment]
Then it not copies templates when compiling because of errors. I have templates with EJS and when I'm running Babel it says that can't transpile templates. Also what about others files in templates ?

In a nutshell, if I'm compiling sources of the generator on prepublish, then I need somehow to copy templates folder from src to lib too. Did you write generator with ES6 syntax?  Because I thinking that you don't understand my problem.

**Comment by SBoudrias** [comment]
Please refer to IRC or StackOverflow for further question. You need help with coming up with a correct babel workflow, this is not a bug on yeoman-generator.

Please don't take this request as me being rude or refusing to help. I'm only one person and I can't offer direct support for every programming questions about things that are unrelated to Yeoman.

You should ask questions to the babel community.

**Comment by ghaiklor** [comment]
Yeah, I understand. I was looking for gitter room, but all of them is not alive.

**Comment by zckrs** [comment]
Facing same problem

* I writing a simple generator with `generator-generator` and `generator-node` who should prompt one question
* I use babeljs to write ES5 equivalent in `dist/app/index.js` and define main package.json to `dist/app/index.js`
* `npm link` to install my local package globally.
* `yo` show me this new generator but run ES6 code instead of `dist/app/index.js`

```
/generator-samplegenerator/generators/app/index.js:1
(function (exports, require, module, __filename, __dirname) { import { Base } 
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
```

**Comment by zckrs** [comment]
I think problem is in `yeoman-environment`  used by `yo` https://github.com/yeoman/environment/blob/master/lib/environment.js#L57

@SBoudrias maybe environnement should read main pprt in package.json ?

**Comment by zckrs** [comment]
@ghaiklor  can you rename issue for more specific title like "How to write generator in ES2015?"

**Comment by ghaiklor** [comment]
@zckrs here is my question on StackOverflow and my answer to this question :smile_cat: 
http://stackoverflow.com/questions/32647945/yeoman-generator-with-babel-flow/32655450#32655450

I've found a solution for this edge-case and works fine. @SBoudrias can close this issue.

**Comment by SBoudrias** [comment]
Yes, your out directory cannot be `dist` as this is not a valid generator directory name for Yeoman.

**Comment by zckrs** [comment]
Thank you for informations.

In final answer I created a boilerplate for Yeoman generator written in ES6.

https://github.com/FountainJS/generator-yeoman-boilerplate-es6
