### ISSUE TITLE
Why not Bower, Grunt-CLI and Gulp as dependencies to Yo package?

### ISSUE THREAD

**Issue by HopefulLlama** [yeoman/yo#362]
On the Getting Started page (at http://yeoman.io/learning/), you are given the very first command of:

`npm install -g yo bower grunt-cli gulp`

If these are required by Yo, would it make more sense to have these listed as dependencies? This way the user will not need to specify the packages explicitly.

If they are only required for the `generator-webapp` example, perhaps it would be clearer if the installation of Bower, Grunt-CLI and Gulp was listed in there, rather than with the installation of Yo.

**Comment by arthurvr** [comment]
Those aren't required for yo, but are generally used by a bunch (nearly all) of the generators. Besides from that those can't really be autmatically installed with `yo` as we're talking about global packages.

**Comment by eddiemonge** [comment]
You could include them as dependencies but then its harder to run them as you have to setup a npm script for them and remember how to pass args in to that script every time
