### ISSUE TITLE
Strange error on windows 7 install

### ISSUE THREAD

**Issue by italodirenzo93** [yeoman/yo#367]
When following the steps outlined to install the 'yo' package, it fails during the postinstall and always presents me with this:

![image](https://cloud.githubusercontent.com/assets/12662675/10409151/7fb29c0e-6ee1-11e5-83df-03ef834d935e.png)

I've been Googling for the past hour looking for answers but have found nothing so I thought I'd ask here...

**Comment by SBoudrias** [comment]
Looks like node is not in your system PATH. https://en.wikipedia.org/wiki/PATH_(variable)
