### ISSUE TITLE
Peer dependency warnings with angular generator

### ISSUE THREAD

**Issue by Elliot87** [yeoman/yo#370]
Hi, I'm following along with the codelab on yeoman.io, and trying to use the angular generator. The generator itself seemed to install fine, and it even seemed to run fine, the live preview showed up how it was supposed to, but I got some errors in the terminal that I'm not sure is a problem or not.

`UNMET PEER DEPENDENCY jasmine-core@*`
`UNMET PEER DEPENDENCY karma@^0.13.0 || >= 0.14.0-rc.0`
and also, I had already just installed karma because it said I needed it for the angular generator
`UNMET PEER DEPENDENCY phantomjs@>=1.9`
I have no idea what jasmine-core or phantomjs are, and the codelab didn't say anything about adding them.

All things considered, these are just warnings, and not errors....so I didn't get an actual npm-debug log, but I don't want anything to cause errors in the future. Also, if I'm not using the live preview, none of the styles or images show up on the index.html in the 'app' directory....is this normal? Does it have to be live for the styles to show up?

Also is there any way to make these warnings go away for future projects, or should I just ignore them? Thanks.

**Comment by eddiemonge** [comment]
You'll only have problems once you start testing. But its easy to solve by doing `npm install jasmine-core karma phantomjs`

**Comment by Elliot87** [comment]
Is it normal that none of the styles, images or buttons show up when viewing opening the index.html with a browser? They only show if i use live preview with  `gulp start`

**Comment by eddiemonge** [comment]
yeah at the moment it is. I have to figure out why since I thought i fixed the broken bootstrap bower implementation

**Comment by damienstanton** [comment]
`yo` does not appear to be reporting as a peer properly, in any generators. I am using OS X 10.11, node 4.2.1 and npm 3.3.9.

Output of two tests, one with `generator-bangular` and another with `generator-gulp-angular`:
```bash
 work_folder  》 npm install -g generator-gulp-angular
/usr/local/lib
├── generator-gulp-angular@1.0.0
└── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN EPEERINVALID generator-gulp-angular@1.0.0 requires a peer of yo@>=1.0.0 but none was installed.
 work_folder  》 npm install -g generator-bangular
/usr/local/lib
├── generator-bangular@0.11.3
└── UNMET PEER DEPENDENCY yo@>=1.4.0

npm WARN EPEERINVALID generator-bangular@0.11.3 requires a peer of yo@>=1.4.0 but none was installed.
```
However...
```bash
 work_folder  》 npm -g list | grep yo
│ └─┬ yosay@1.0.5
└─┬ yo@1.4.8
  └─┬ yosay@1.0.5
```

**Comment by soniurvashi11** [comment]
npm WARN EPEERINVALID grunt-karma@0.12.1 requires a peer of karma@^0.13.0 || >=
0.14.0-rc.0 but none was installed.
Can anybody tell me how can i resolve this issue

**Comment by SBoudrias** [comment]
@soniurvashi11 ask `grunt-karma` to remove their peerDependencies.

**Comment by soniurvashi11** [comment]
and how can i do that ?Can u pls tell me?

**Comment by SBoudrias** [comment]
@soniurvashi11 you open an issue like you did here on their repository. Even better, send them a pull request.
