### ISSUE TITLE
Windows 10 x64 & node 4.2.1

### ISSUE THREAD

**Issue by mr47** [yeoman/yo#371]
I used few month ago yeoman and all was just fine. But i get new windows and new node and someting goes wrong.
```
npm install -g yo
```
all doing fine and yo writes that install is success.

i tried reinstall many times but when i try to run yo, always get same: 
```
mr470@MR47-DESKTOP MINGW64 /e/lab/vagrant-test
$ yo

     _-----_
    |       |    .-----------------------.
    |--(o)--|    |      Bye from us!     |
   `---------´   |       Chat soon.      |
    ( _´U`_ )    |      Yeoman team      |
    /___A___\    |    http://yeoman.io   |
     |  ~  |     '-----------------------'
   __'.___.'__
 ´   `  |° ´ Y `



C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:549
    throw e;
    ^

TypeError: Cannot read property 'substring' of undefined
    at Interface.rl._getCursorPos (C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\readline2\index.js:55:51)
    at ScreenManager.render (C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\utils\screen-manager.js:19:27)
    at Prompt.render (C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\prompts\list.js:102:15)
    at Prompt._run (C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\prompts\list.js:73:8)
    at Prompt.run (C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\prompts\base.js:57:8)
    at Object.<anonymous> (C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\ui\prompt.js:83:12)
    at module.exports (C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\run-async\index.js:15:21)
    at C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\lib\utils\utils.js:16:7
    at tryCatcher (C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:537:29)
    at setDisposable (C:\Users\mr470\AppData\Roaming\npm\node_modules\yo\node_modules\inquirer\node_modules\rx-lite\rx.lite.js:5380:36)

```
PS: i have 0 installed generators
May be its all about git bash 2.5.x (its worked before in git 1.9.x) ?

**Comment by SBoudrias** [comment]
See https://github.com/SBoudrias/Inquirer.js/issues/272

**Comment by SBoudrias** [comment]
Also, the main issue you're hitting is https://github.com/nodejs/node/issues/3006 - The short answer is don't use git bash.

**Comment by Sheparzo** [comment]
Dang it. Just when windows was becoming more manageable to work with from the command line. Git bash or Cygwin made it sane. Now I have to keep track of what works in git bash vs native command line.

**Comment by SBoudrias** [comment]
@Sheparzo Powershell is a sane Terminal for Windows that doesn't try to imitate Unix (if you want to use unix, then use Ubuntu or Mac). If you only cared about the git bash style, then wrap your powershell inside of Console2 and customize your command line style.

**Comment by Sheparzo** [comment]
Yes Powershell is sane but it is not where the mindshare is in web tooling. Bash emulation is desired and has been accomplished to a great extent on Windows. I have a large corporate environment tethered to Windows and we need bash and all its tools working on Windows.

**Comment by SBoudrias** [comment]
@Sheparzo Any node.js tool will run correctly on powershell. I've also worked in large windows stack corporate environment, and I never run into issues using powershell to get any tools running. I don't see which part of bash are necessary for any mainstream web tools (maybe nvm, but there's a windows script fork).

**Comment by Sheparzo** [comment]
PowerShell is a distant second choice.  It is more desirable (and fun) to use git bash or cygwin.  Is Git bash absolutely necessary? - no.  Is git bash/cygwin still preferred? absolutely.  And up until a month or two ago, we were golden.  We could use git bash for all our needs and generate a jhipster app with yeoman, run grunt, node, npm all from bash which is clearly the superior cli.  I could do all this in PowerShell, but it is still so clearly inferior to bash.  I realize that I am asking to have my cake and eat it too.  And also that this seems more like node's issue than Yeoman's.  I am going to continue to use git bash or cygwin on windows for everything that I possibly can and convince corporate decision makers to use this tooling that so often is demonstrated from a bash cli.  And then go back to Powershell or the old command line for that which will not work on bash in Windows.
