### ISSUE TITLE
Having yo query private registries, not just the NPM registry

### ISSUE THREAD

**Issue by DullReferenceException** [yeoman/yo#374]
For our internal code base, we have a private repository for hosting private packages and as a proxy for retrieving/caching public packages. I discovered after publishing a generator to this private repository, that `yo` does not search the repository, even if the npm config or `.npmrc` file indicates the private repository.

Is there a way to get `yo` use a different URL when discovering generators?

**Comment by sindresorhus** [comment]
Try master, the `package-json` was bumped to support private scoped modules. Planning to do a new release this weekend.

https://github.com/sindresorhus/package-json/compare/v2.0.0...v2.2.0

**Comment by DullReferenceException** [comment]
That would be helpful for private packages hosted in NPM. Unfortunately, we put our private packages in our own registry, not in the NPM registry. After installing `master`, I see that the registry in my npm config is still not queried.

**Comment by sindresorhus** [comment]
@DullReferenceException It should in theory, as it [reads your scoped auth token](https://github.com/sindresorhus/package-json/blob/4b2eac763f09cc90100df28bdcdc579c7f03fc38/index.js#L11), but I had no way of actually testing that. Open an issue on https://github.com/sindresorhus/package-json
