### ISSUE TITLE
async necessary with this.fs.

### ISSUE THREAD

**Issue by ilanbiala** [yeoman/yo#377]
If I have code like this:
```
var bowerJson = this.fs.readJSON(folderPath + 'bower.json');
// some changes made to bowerJson
this.fs.writeJSON(folderPath + bowerJson);
```
Do I need to call `var done = this.async()` before and then call `done()` after my write statement?

**Comment by SBoudrias** [comment]
Nope, that's not asynchronous.

**Comment by ilanbiala** [comment]
@SBoudrias irrelevant from this issue I guess, but I'm not sure what changed here that broke the build. Could you take a look at https://github.com/codydaig/generator-meanjs/pull/1?
