### ISSUE TITLE
Yo finds linked generator but can't run it.

### ISSUE THREAD

**Issue by StevenUlibarri** [yeoman/yo#378]
I'm following the writing your own generator tutorial and I'm having an odd issue where Yo is registering my linked generator and offering it as an option when I run 'yo' but when I select it I get this:

>Yo version 1.5.0
>You don't seem to have a generator with the name impServices:app installed.
>You can see available generators with npm search yeoman-generator and then install them with npm install [name].
>To see the 1 registered generators run yo with the `--help` option.

The one registered generator it mentions is the one I am trying to run. I went through the tutorial with a friend as a sanity check and it worked for him.

**Comment by StevenUlibarri** [comment]
Turned out to be an unrelated issue with my linux distro. Please disregard.

**Comment by marty-buly** [comment]
Hey @StevenUlibarri, what was the distro issue? Because I'm facing the same... Thnx for info
