### ISSUE TITLE
Yodoctor post install fails on OSX

### ISSUE THREAD

**Issue by mountain65** [yeoman/yo#380]
Since yo does not work, I cannot run run yo --version

*** Log files
npm-debug log attached as PDF

*** Command line output
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

yo@1.5.0 postinstall /usr/local/lib/node_modules/yo
yodoctor

env: node: No such file or directory
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v4.2.2
npm ERR! npm  v3.4.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! yo@1.5.0 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the yo@1.5.0 postinstall script 'yodoctor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mountain/Documents/Projects/Elixir/npm-debug.log

**Comment by mountain65** [comment]
Attempt to add attachment again.
[npm-debug.log.pdf](https://github.com/yeoman/yo/files/39905/npm-debug.log.pdf)

**Comment by urecio** [comment]
Try `npm -g install yeoman-doctor`

**Comment by sindresorhus** [comment]
Use https://github.com/npm/npm/issues for npm install issues.

**Comment by mountain65** [comment]
I'm sorry to see that you closed the issue. The error log clearly states that it must be a yeoman problem. It is the yodoctor that does not work, even if I install it seperately as suggested. Could you please put a little time in this?

**Comment by SBoudrias** [comment]
@mountain65 npm just assumed our command failed. But the issue is npm didn't install correctly. - They assumed wrong.

**Comment by sindresorhus** [comment]
@mountain65 This issue comes up all the time. Search the issue tracker and you'll see. It's not a problem with `yo`.

> Could you please put a little time in this?

I have. Probably hours answering countless of these issues. I know it's painful, but there's not much we can do about it. It's all on npm.

**Comment by mountain65** [comment]
Ok, fair enough. Thanks for all the good work. Don't give up!

**Comment by SBoudrias** [comment]
@mountain65 BTW @urecio answer is correct. That should manually fix your issue.
