### ISSUE TITLE
Cannot Install yo and no error or warning notification

### ISSUE THREAD

**Issue by Ginnoken** [yeoman/yo#381]
I'm trying install yo in windows 7. It didn't give any error or warning notification. Below is my command prompt view when installing.

>npm install -g yo@latest
loadDep:jsbn → checkoutTr ▐ ╢█████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

**Comment by sindresorhus** [comment]
We're not in control of installing. That's npm. https://github.com/npm/npm/issues
