### ISSUE TITLE
Generator fails to install from yo@1.5.0 not meeting dep of yo>=1.0.0

### ISSUE THREAD

**Issue by gentlefox** [yeoman/yo#387]
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
/Users/gregarnott/.nvm/versions/node/v5.1.1/lib
└─┬ yo@1.5.0
  └─┬ insight@0.7.0
    └─┬ request@2.67.0
      └── tunnel-agent@0.4.2

gregarnott@MBP:~/RXP/fh/local-cli-fh-env/yo-angularjs
> npm i -g generator-angularjs-cordova
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
/Users/gregarnott/.nvm/versions/node/v5.1.1/lib
├── generator-angularjs-cordova@1.0.1
└── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN generator-angularjs-cordova@1.0.1 requires a peer of yo@>=1.0.0 but none was installed.

gregarnott@Gregs-MBP:~/RXP/fh/local-cli-fh-env/yo-angularjs
> yo -v
? 'Allo Greg! What would you like to do? Install a generator
? Search npm for generators: angularjs-cordova
? Here's what I found. Official generator → ෴
  Install one? angularjs-cordova
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
/Users/gregarnott/.nvm/versions/node/v5.1.1/lib
├── generator-angularjs-cordova@1.0.1
└── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN generator-angularjs-cordova@1.0.1 requires a peer of yo@>=1.0.0 but none was installed.

I just installed a generator by running:

    npm install -g generator-angularjs-cordova

**Comment by SBoudrias** [comment]
This is only a warning, it shouldn't break anything. Feel free to ignore.

`generator-angularjs-cordova` should remove their peerDependencies.
