### ISSUE TITLE
Error message when generator not found should mention yo doctor

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yo#388]
Let's make it easier on folks and tell them right away they can troubleshoot using `yo doctor`.

**Comment by mischah** [comment]
Question:

Do you mean the use case when someone is trying to fire a generator which they haven’t installed?

```
$ yo generator-webapp-gulp
Error generator-webapp-gulp 

You don't seem to have a generator with the name generator-webapp-gulp installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 14 registered generators run yo with the `--help` option.
```

How will yo doctor help with that?

```
$ yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
```

Running `yo --help` outputs all the informatio needed, right? And it is already mentioned in the error message above. 

Or didn’t I get this issue?

Thanks 😘

**Comment by SBoudrias** [comment]
@mischah some people have misconfigured computer which prevents yo from detecting their generators. `yo doctor` would detect most of these broken configuration and provide fix steps.

**Comment by mischah** [comment]
Thanks @SBoudrias. Do you have any idea how to reproduce that misconfiguration?
Would like to work on this 😘

**Comment by mischah** [comment]
Ah, the problem is that people will get that error message for generators the actually do have installed. Like described here: https://github.com/yeoman/yeoman/issues/1252

Okay. Guess that’s all I need to know.

**Comment by SBoudrias** [comment]
Easiest way is to have a misconfigured `NODE_PATH`.

That being said, a good first step would be just to update the error message with:

1. How to install a generator (kind of what it's printing right now, but it could be better)
2. Use `yo doctor` if yeoman cannot find your generator.

**Comment by mischah** [comment]
PR is over here: https://github.com/yeoman/environment/pull/70

I finally begin to understand how the yeoman repos are interconnected :satisfied:
