### ISSUE TITLE
Unable to install yeoman globally

### ISSUE THREAD

**Issue by foxt7ot** [yeoman/yo#390]
Below is the stacktrace:
 npm install -g yo
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! file C:\Users\Yaseen\AppData\Roaming\npm-cache\root-check\1.0.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\Yaseen\AppData\Roaming\npm-cache\root-check\1.0.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Yaseen\npm-debug.log

**Comment by sindresorhus** [comment]
Works fine for me. Just tried.

Regardless of what that dump npm error message says, this is usually a sign of some kind of npm install corruption. Ensure you're on the latest [Node.js](http://nodejs.org) and npm version (`$ npm i -g npm`). Then delete the `node_modules` folder and run `$ npm cache clean` and then `$ npm install`. Use the [npm issue tracker](https://github.com/npm/npm/issues) for support.
