### ISSUE TITLE
can not create yeoman project on my mac running OS X Yosemite 10.11.2

### ISSUE THREAD

**Issue by FatJoe123** [yeoman/yo#393]
npm WARN deprecated gulp-karma@0.0.4: Please use Karma directly: https://github.com/karma-runner/gulp-karma
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm WARN EPEERINVALID gulp-karma@0.0.4 requires a peer of karma@>=0.10 <=0.13 but none was installed.
Task 'wiredep' is not in your gulpfile
[21:37:54] Please check the documentation for proper gulpfile formatting
? Overwrite package.json? overwrite
    force     package.json
   create     .travis.yml
mytodo@ /Users/alan/Workspace/yeoman/mytodo
├── UNMET PEER DEPENDENCY grunt@0.4.x
├─┬ grunt-karma@0.12.1
│ └── lodash@3.10.1
├─┬ gulp-imagemin@2.4.0
│ └─┬ imagemin@4.0.0
│   └─┬ imagemin-svgo@4.2.0
│     └─┬ svgo@0.6.1
│       └─┬ js-yaml@3.4.6
│         └─┬ argparse@1.0.3
│           └── lodash@3.10.1
├─┬ gulp-jshint@1.12.0
│ └── lodash@3.10.1
├─┬ gulp-sass@2.1.1
│ └─┬ node-sass@3.4.2
│   └─┬ sass-graph@2.0.1
│     └── lodash@3.10.1
├── UNMET PEER DEPENDENCY jasmine-core@*
├── UNMET PEER DEPENDENCY karma@^0.13.0 || >= 0.14.0-rc.0
├── karma-jasmine@0.3.6
├─┬ karma-phantomjs-launcher@0.2.1
│ └── lodash@3.10.1
└── UNMET PEER DEPENDENCY phantomjs@>=1.9

npm WARN EPEERINVALID gulp-karma@0.0.4 requires a peer of karma@>=0.10 <=0.13 but none was installed.
npm WARN EPEERINVALID karma-jasmine@0.3.6 requires a peer of jasmine-core@* but none was installed.
npm WARN EPEERINVALID grunt-karma@0.12.1 requires a peer of grunt@0.4.x but none was installed.
npm WARN EPEERINVALID grunt-karma@0.12.1 requires a peer of karma@^0.13.0 || >= 0.14.0-rc.0 but none was installed.
npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.1 requires a peer of karma@>=0.9 but none was installed.
npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.1 requires a peer of phantomjs@>=1.9 but none was installed.

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/yeoman
Paste in the link to the question here so others can follow ;)

Make sure to include which generator you're trying to use.

**Comment by Kamps-Duac** [comment]
For what it's worth, I have the same issue for yeoman-angular with gulp - following documentation to the "t" on OSX. I have no issues using yeoman-angular with grunt. 

Please post any additional info here as it come up on search engine at the top for this error message.
