### ISSUE TITLE
Getting error during installation

### ISSUE THREAD

**Issue by falcon-europe** [yeoman/yo#395]
I am getting error while installing via command: sudo npm install -g yo
my environment: Mac OS X El Capitan 10.11.2
npm version 3.5.3
node version 5.3.0

I will be glad for your help

I have attached npm-debug file to look into
[npm-debug.txt](https://github.com/yeoman/yo/files/72458/npm-debug.txt)

**Comment by sindresorhus** [comment]
This is a problem with npm. Use the [npm issue tracker](https://github.com/npm/npm/issues) for npm support.
