### ISSUE TITLE
Improve "yo" (ran without any arguments) by listing subgenerators

### ISSUE THREAD

**Issue by geecu** [yeoman/yo#397]
So, running "yo" and selecting "Angular" from the "Run a generator" list, maybe should display a list of sub-generators from the angular generator instead of running "app".

Or, (at least,) if "yo" is being run inside a directory generated by yeoman, it should display the subgenerators of the original generator.

This would save quite a lot of typing, and maybe the need for shell autocompletion.

If anyone finds this interesting, I'd like to try my hand at contributing a PR.

**Comment by eddiemonge** [comment]
Seems very similar to https://github.com/yeoman/yo/issues/394
