### ISSUE TITLE
failed instal: "This is most likely a problem with the yo package" no npm-debug.log on machine

### ISSUE THREAD

**Issue by plm19** [yeoman/yo#402]
OS X: 10.11.2

No npm-debug.log file to be found!  What can I do?

========
sudo npm install -g yo
Password:
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.6.0 postinstall /usr/local/lib/node_modules/yo
> yodoctor

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied
sh: yodoctor: command not found
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.12
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! yo@1.6.0 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the yo@1.6.0 postinstall script 'yodoctor'.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/home/npm-debug.log

**Comment by SBoudrias** [comment]
That's a bug with npm.

Make sure you're using the latest version.

If it doesn't work, run `npm i -g yodoctor` before installing yo.

**Comment by plm19** [comment]
Simon,

Thanks for the quick response.  I installed npn from your web site and then checked for updates.  I got the following negative response to npm i -g yodoctor.  This time it did write a log file.  I renamed with a .txt suffix.  
[npm-debug.txt](https://github.com/yeoman/yo/files/86362/npm-debug.txt)
Here is what is says.
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'yodoctor' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose install initial load of /usr/local/lib/package.json
5 verbose readDependencies loading dependencies from /usr/local/lib/package.json
6 silly cache add args [ 'yodoctor', null ]
7 verbose cache add spec yodoctor
8 silly cache add parsed spec Result {
8 silly cache add   raw: 'yodoctor',
8 silly cache add   scope: null,
8 silly cache add   name: 'yodoctor',
8 silly cache add   rawSpec: '',
8 silly cache add   spec: 'latest',
8 silly cache add   type: 'tag' }
9 silly addNamed yodoctor@latest
10 verbose addNamed "latest" is being treated as a dist-tag for yodoctor
11 info addNameTag [ 'yodoctor', 'latest' ]
12 silly mapToRegistry name yodoctor
13 silly mapToRegistry using default registry
14 silly mapToRegistry registry https://registry.npmjs.org/
15 silly mapToRegistry uri https://registry.npmjs.org/yodoctor
16 verbose addNameTag registry:https://registry.npmjs.org/yodoctor not in flight; fetching
17 verbose request uri https://registry.npmjs.org/yodoctor
18 verbose request no auth needed
19 info attempt registry request try #1 at 3:43:44 PM
20 verbose request id 9ca9d639a1434c8d
21 http request GET https://registry.npmjs.org/yodoctor
22 http 404 https://registry.npmjs.org/yodoctor
23 verbose headers { 'content-type': 'application/json',
23 verbose headers   'cache-control': 'max-age=0',
23 verbose headers   'content-length': '2',
23 verbose headers   'accept-ranges': 'bytes',
23 verbose headers   date: 'Mon, 11 Jan 2016 20:43:45 GMT',
23 verbose headers   via: '1.1 varnish',
23 verbose headers   age: '0',
23 verbose headers   connection: 'keep-alive',
23 verbose headers   'x-served-by': 'cache-jfk1021-JFK',
23 verbose headers   'x-cache': 'MISS',
23 verbose headers   'x-cache-hits': '0',
23 verbose headers   'x-timer': 'S1452545025.038760,VS0,VE96' }
24 silly get cb [ 404,
24 silly get   { 'content-type': 'application/json',
24 silly get     'cache-control': 'max-age=0',
24 silly get     'content-length': '2',
24 silly get     'accept-ranges': 'bytes',
24 silly get     date: 'Mon, 11 Jan 2016 20:43:45 GMT',
24 silly get     via: '1.1 varnish',
24 silly get     age: '0',
24 silly get     connection: 'keep-alive',
24 silly get     'x-served-by': 'cache-jfk1021-JFK',
24 silly get     'x-cache': 'MISS',
24 silly get     'x-cache-hits': '0',
24 silly get     'x-timer': 'S1452545025.038760,VS0,VE96' } ]
25 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/yodoctor
25 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:264:12)
25 verbose stack     at CachingRegistryClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:242:14)
25 verbose stack     at Request._callback (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:172:14)
25 verbose stack     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/request.js:198:22)
25 verbose stack     at emitTwo (events.js:87:13)
25 verbose stack     at Request.emit (events.js:172:7)
25 verbose stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1082:10)
25 verbose stack     at emitOne (events.js:82:20)
25 verbose stack     at Request.emit (events.js:169:7)
25 verbose stack     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1009:12)
26 verbose statusCode 404
27 verbose pkgid yodoctor
28 verbose cwd /Users/home
29 error Darwin 15.2.0
30 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "-g" "yodoctor"
31 error node v4.2.4
32 error npm  v2.14.12
33 error code E404
34 error 404 Registry returned 404 for GET on https://registry.npmjs.org/yodoctor
34 error 404
34 error 404 'yodoctor' is not in the npm registry.
34 error 404 You should bug the author to publish it (or use the name yourself!)
34 error 404
34 error 404 Note that you can also install from a
34 error 404 tarball, folder, http url, or git url.
35 verbose exit [ 1, true ]



(https://github.com/yeoman/yo/files/86360/npm-debug.txt)
![image](https://cloud.githubusercontent.com/assets/13051239/12246202/21f5fa78-b87b-11e5-813e-6697a8cd5229.png)

**Comment by SBoudrias** [comment]
My bad, you want `npm i -g yeoman-doctor` https://www.npmjs.com/package/yeoman-doctor

**Comment by plm19** [comment]
That is better.

> /usr/local/bin/yodoctor -> 
> /usr/local/lib/node_modules/yeoman-doctor/lib/cli.js
> npm WARN unmet dependency 
> /usr/local/lib/node_modules/npm/node_modules/read-installed/node_modules/readdir-scoped-modules 
> requires graceful-fs@'^4.1.2' but will load
> npm WARN unmet dependency 
> /usr/local/lib/node_modules/npm/node_modules/read-installed/node_modules/graceful-fs,
> npm WARN unmet dependency which is version 3.0.8
> yeoman-doctor@2.1.0 /usr/local/lib/node_modules/yeoman-doctor
> ├── object-values@1.0.0
> ├── log-symbols@1.0.2
> ├── semver@5.1.0
> ├── user-home@2.0.0 (os-homedir@1.0.1)
> ├── each-async@1.1.1 (set-immediate-shim@1.0.1, onetime@1.1.0)
> ├── chalk@1.1.1 (escape-string-regexp@1.0.4, ansi-styles@2.1.0, 
> supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
> ├── twig@0.8.6 (walk@2.3.9, minimatch@0.2.14)
> └── bin-version-check@2.1.0 (minimist@1.2.0, semver@4.3.6, 
> semver-truncate@1.1.0, bin-version@1.0.4)

**Comment by borgymanotoy** [comment]
borgymanotoy@azeus:~/dev/npm$ npm i -g yo

> spawn-sync@1.0.15 postinstall /home/borgymanotoy/.npm/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall


> yo@2.0.0 postinstall /home/borgymanotoy/.npm/lib/node_modules/yo
> yodoctor

sh: 1: yodoctor: not found
npm ERR! Linux 4.10.0-28-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i" "-g" "yo"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! yo@2.0.0 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the yo@2.0.0 postinstall script 'yodoctor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/borgymanotoy/.npm/_logs/2017-07-28T05_38_32_517Z-debug.log
