### ISSUE TITLE
Delete chalk whan 

### ISSUE THREAD

**Issue by semiromid** [yeoman/yo#404]
1.Step
npm install gulp-cssnano@2.0.0 --save-dev

2.Step
npm outdated 
Package       Current  Wanted  Latest  Location
chalk           1.1.0   1.1.1   1.1.1  progectapi2
gulp-cssnano    2.0.0   2.1.0   2.1.0  progectapi2

3.Step
npm update gulp-cssnano --save-dev

----------------------------------------------------------------------
E:\Developers\WebDeveloper\OpenServer-WebProg\domains\progectapi2>npm update gul
p-cssnano --save-dev
- object-assign@3.0.0 node_modules\gulp-cssnano\node_modules\object-assign
- source-map@0.1.43 node_modules\gulp-cssnano\node_modules\source-map
- vinyl-sourcemaps-apply@0.1.4 node_modules\gulp-cssnano\node_modules\vinyl-sour
cemaps-apply
supports-color@2.0.0 node_modules\chalk\node_modules\supports-color -> node_modu
les\gulp-util\node_modules\supports-color
- amdefine@1.0.0 node_modules\amdefine
- chalk@1.1.0 node_modules\chalk
npm WARN EPACKAGEJSON progectapi2@1.0.0 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "update" "gulp-cssnano" "--save-dev"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! path E:\Developers\WebDeveloper\OpenServer-WebProg\domains\progectapi2\
node_modules\chalk\node_modules\supports-color
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'E:\Developers\WebDeve
loper\OpenServer-WebProg\domains\progectapi2\node_modules\chalk\node_modules\sup
ports-color' -> 'E:\Developers\WebDeveloper\OpenServer-WebProg\domains\progectap
i2\node_modules\gulp-util\node_modules\supports-color'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Developers\WebDeveloper\OpenServer-WebProg\domains\progectapi2\n
pm-debug.log

----------------------------------------------------------------------

4.Step
npm outdated 
Package       Current  Wanted  Latest  Location
chalk         MISSING   1.1.1   1.1.1  progectapi2
gulp-cssnano    2.0.0   2.1.0   2.1.0  progectapi2

**Comment by sindresorhus** [comment]
This is usually a sign of some kind of npm install corruption. Ensure you're on the latest [Node.js](http://nodejs.org) and npm version (`$ npm i -g npm`). Then delete the `node_modules` folder and run `$ npm cache clean` and then `$ npm install`. Use the [npm issue tracker](https://github.com/npm/npm/issues) for support.
