### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by semiromid** [yeoman/yo#405]
I installed :
step : 1
npm install gulp-cssnano@2.0.0 --save-dev
step : 2
npm install chalk@1.1.0 --save
step : 3
npm install gulp-cssnano --save-dev
Why?

Package       Current  Wanted  Latest  Location
chalk                1.1.0   |     1.1.1    |     1.1.1      progectapi2

_____________________
gulp-cssnano    2.0.0  |     2.1.0   |     2.1.0      progectapi2
_________________________

npm                 3.5.3    |   3.5.4     |   3.5.3           progectapi2
_________________________________
E:\Developers\WebDeveloper\OpenServer-WebProg\domains\progectapi2>npm install gu
lp-cssnano --save-dev
- object-assign@3.0.0 node_modules\gulp-cssnano\node_modules\object-assign
supports-color@2.0.0 node_modules\chalk\node_modules\supports-color -> node_modu
les\gulp-util\node_modules\supports-color
- source-map@0.1.43 node_modules\vinyl-sourcemaps-apply\node_modules\source-map
- amdefine@1.0.0 node_modules\amdefine
- chalk@1.1.0 node_modules\chalk
progectapi2@1.0.0 E:\Developers\WebDeveloper\OpenServer-WebProg\domains\progecta
pi2
├─┬ gulp-autoprefixer@3.1.0
│ └── vinyl-sourcemaps-apply@0.2.1
├─┬ gulp-sass@2.1.1
│ └── vinyl-sourcemaps-apply@0.2.1
└── vinyl-sourcemaps-apply@0.2.1  extraneous

npm WARN EPACKAGEJSON progectapi2@1.0.0 No repository field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-cssnano" "--save-dev"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! path E:\Developers\WebDeveloper\OpenServer-WebProg\domains\progectapi2\
node_modules\chalk\node_modules\supports-color
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

npm ERR! enoent ENOENT: no such file or directory, rename 'E:\Developers\WebDeve
loper\OpenServer-WebProg\domains\progectapi2\node_modules\chalk\node_modules\sup
ports-color' -> 'E:\Developers\WebDeveloper\OpenServer-WebProg\domains\progectap
i2\node_modules\gulp-util\node_modules\supports-color'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     E:\Developers\WebDeveloper\OpenServer-WebProg\domains\progectapi2\n
pm-debug.log

E:\Developers\WebDeveloper\OpenServer-WebProg\domains\progectapi2>

_______________________________________

**Comment by kevva** [comment]
I'm not following what you're asking here. Regardless, it doesn't seem related to `yo`.

**Comment by sindresorhus** [comment]
This is just a duplicate of https://github.com/yeoman/yo/issues/404, which was already answered...
