### ISSUE TITLE
Cannot find module 'latest-version'

### ISSUE THREAD

**Issue by iesta** [yeoman/yo#407]
I have this error whenever i tried to generate any app...

  ProJim:polymer jm$ sudo yo polymer
  module.js:339
    throw err;
    ^

  Error: Cannot find module 'latest-version'

I suppose it's a permission problem but i dont know how to correct it.
Thank you

**Comment by sindresorhus** [comment]
This is usually a sign of some kind of npm install corruption. Ensure you're on the latest [Node.js](http://nodejs.org) and npm version (`$ npm i -g npm`). Then delete the `node_modules` folder and run `$ npm cache clean` and then `$ npm install`. Use the [npm issue tracker](https://github.com/npm/npm/issues) for support.

**Comment by iesta** [comment]
Thank you :-)
