### ISSUE TITLE
What happened with JavaScript?.

### ISSUE THREAD

**Issue by denebchorny** [yeoman/yo#410]
Hi sir,

Sorry for bother you, but What happened with JavaScript?.
I am using generator-angular-fullstack. When I'm creating a project with "yo angular-fullstack [app-name]" there isn't the option of Javascript (As before, previous YO versions), but only babel and typescript.

Thanks in advance.

**Comment by kevva** [comment]
You have to ask them on https://github.com/angular-fullstack/generator-angular-fullstack, but Babel "is" JavaScript, or rather a transpiler that enables you to use new features shipped in ES2015.
