### ISSUE TITLE
Shared options when mixing generators on the command line.

### ISSUE THREAD

**Issue by jamen** [yeoman/yo#416]
For [the generator I'm making](https://github.com/devjs/generator-devjs), the sub generators can rely on some of the same options.  For instance, if I had `devjs:readme` and `devjs:package`, an option `name` could be used for both (in the title, and in the `"name"` field in `package.json`)...  

But the problem is, I don't want to have to have the user to supply that option (or be prompted for it) twice, because once they enter it the first time, the other sub-generator could use it.

Right now, to solve this issue, I have a global object (which is named after the generator, `devjs`), this is used by all of the sub generators (when mixed, and since it is global, they can all access it)...  Then I have a prompting wrapper that checks to see if that value is already defined in `devjs`, before prompting the user to get that option.

Essentially, my desire is to have this functionality built.

<s>How exactly this would be implemented safely along-side `this.options`?  Not a clue.</s>  It should be a separate thing entirely...  I kept thinking with the mindset of "options" for some reason, but in reality it's just a shared storage.

**Comment by jamen** [comment]
Maybe "options" was the wrong term...  Just like a shared store in the yeoman environment, for all the generators to use.

**Comment by SBoudrias** [comment]
When you use `composeWith`, you can pass options down to generators.

We don't want a shared global object approach as that'll make our ecosystem easier to break.

**Comment by jamen** [comment]
I mean when you compose them both at once, not when one composes another.  For instance: `yo foo:bar, foo:baz`

If `foo:bar` prompts for a username, how would I continue to use that data in `foo:baz`?

**Comment by SBoudrias** [comment]
Then ask for the name from the top level generator and pass it down to both.

We don't plan to change that part, but you might be interested in this discussion https://github.com/yeoman/generator/issues/894

**Comment by jamen** [comment]
@SBoudrias: Now that I think about it, this could be as simple as a Map on the environment, since all generators under it hold a reference:

Generator `foo:bar`:
```
this.env.storage.set('name', this.options.name);
```
Generator `foo:baz`:
```
this.env.storage.get('name');
```

Yeoman would never adopt something like that?  

I could just set properties right on `this.env`, like `this.env.foobar`, but I believe doing that has V8 performance reductions (opposed to using something like a map).

Probably not useful when initializing different generators from third parties, but very useful for composing sub generators together, where they can rely on some of the same data.
