### ISSUE TITLE
Windows console changes prefered style

### ISSUE THREAD

**Issue by vkocjancic** [yeoman/yo#417]
After using Yeoman, windows console style is changed to default light gray text on black background. Personally, I always set my console to green text on black background and whenever I use yeoman, that gets reset to default gray on black.

**Comment by SBoudrias** [comment]
Yeoman doesn't change windows terminal style - neither does it have that power.

**Comment by vkocjancic** [comment]
Sorry mate. But it does.

**Comment by SBoudrias** [comment]
I'm not denying you're having this issue. I'm just letting you know it is not related to Yeoman.

**Comment by vkocjancic** [comment]
Let's quickly sum up. No problems when running NPM. No problems when running node.js. No problems when doing normla work in the console. Problem occurs only when using yo. So how can that not be related to Yeoman?
