### ISSUE TITLE
Running generators using yo locally (not global install) does not work

### ISSUE THREAD

**Issue by luanped** [yeoman/yo#418]
If instead of installing globally yeoman I install locally - and then running from ./node_modules it will result in module not found error.

For example yo [path]/generator/app will work
however node ./node_modules/.../cli.js [path]/generator/app will not work

**Comment by SBoudrias** [comment]
Please, don't double post questions - especially as I was already answering you on SO - where questions should go.

Yo is an executable, you want `./node_modules/.../cli.js [path]/generator/app` without node. Even better `./node_modules/_bin/yo`.
