### ISSUE TITLE
Your Node.js version is outdated

### ISSUE THREAD

**Issue by azat-io** [yeoman/yo#419]
Hi there!

I have some problem with updating **Yo**. And this problem looks really strange because Yo require `"node": ">=0.12.0"`. I cannot understand what's wrong here:

```bash
azat@pc:~/git/alch-test$ yo alchemist

     _-----_
    |       |    .------------------------------------------.
    |--(o)--|    | Update available: 1.7.0 (current: 1.5.0) |
   `---------´   |     Run npm install -g yo to update.     |
    ( _´U`_ )    '------------------------------------------'
    /___A___\    
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

Error alchemist 

You don't seem to have a generator with the name alchemist installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 0 registered generators run yo with the `--help` option.


azat@pc:~/git/alch-test$ sudo npm install -g yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js

> yo@1.7.0 postinstall /usr/local/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✖ Node.js version

Your Node.js version is outdated.
Upgrade to the latest version: https://nodejs.org

✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Found potential issues on your machine :(
/usr/local/lib
└── yo@1.7.0 


azat@pc:~/git/alch-test$ nodejs -v
v5.9.0


azat@pc:~/git/alch-test$ node -v
v4.1.1


azat@pc:~/git/alch-test$ npm -v
3.8.2
```

**Comment by SBoudrias** [comment]
run `yo doctor`

**Comment by azat-io** [comment]
@SBoudrias, so?

```bash
azat@pc:/usr/local/lib/node_modules$ yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✖ Node.js version

Your Node.js version is outdated.
Upgrade to the latest version: https://nodejs.org

✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version
✔ NODE_PATH matches the npm root

Found potential issues on your machine :(
```

**Comment by SBoudrias** [comment]
Did you install `generator-alchemist`?

**Comment by caneraydinbey** [comment]
> Yeoman Doctor
> Running sanity checks on your system
> 
> ✔ No .bowerrc file in home directory
> ✔ Global configuration file is valid
> ✔ NODE_PATH matches the npm root
> ✖ Node.js version
> 

I also get errors. when i run sudo npm install -g npm
but i have latest version of nodejs?

look:

> caneraydin@caneraydin-270E5J:~$ sudo apt-get install -y nodejs
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> nodejs is already the newest version.
> The following packages were automatically installed and are no longer required:
>   authbind libcommons-dbcp-java libcommons-pool-java libecj-java
>   libgeronimo-jta-1.1-spec-java libntdb1 libtomcat7-java
>   linux-headers-3.13.0-83 linux-headers-3.13.0-83-generic python-ntdb
>   tomcat7-common
> Use 'apt-get autoremove' to remove them.
> 0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
> caneraydin@caneraydin-270E5J:~$ 
>

**Comment by kevva** [comment]
`node --version`? Installing from `apt` would most likely not give you the latest version unless you have added some other repo to install from.

**Comment by caneraydinbey** [comment]
I solved with

> sudo apt-get install curl
> curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash –
> sudo apt-get install nodejs

thank you.
