### ISSUE TITLE
Yo not installing on Ubuntu 15.04 MATE

### ISSUE THREAD

**Issue by cerberusiscute** [yeoman/yo#420]
Yo is not installing on my Ubuntu 15.04 MATE dist. I have installed NodeJS and NPM as per usual, but when I got to install Yo it gives me this:

npm install -g yo
npm WARN engine yo@1.7.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine deep-extend@0.4.1: wanted: {"node":">=0.12.0","iojs":">=1.0.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hawk@3.1.3: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"1.4.21"})
/home/mark/.node/bin/yo -> /home/mark/.node/lib/node_modules/yo/lib/cli.js

> yo@1.7.0 postinstall /home/mark/.node/lib/node_modules/yo
> yodoctor

/usr/bin/env: node: No such file or directory
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! yo@1.7.0 postinstall: `yodoctor`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the yo@1.7.0 postinstall script.
npm ERR! This is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.2.0-34-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! cwd /home/mark/ang/ang-direc/chap2
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/mark/ang/ang-direc/chap2/npm-debug.log
npm ERR! not ok code 0

Not entirely sure what's going on, but I have googled and googled to no avail

**Comment by SBoudrias** [comment]
http://stackoverflow.com/questions/20881075/npm-install-g-yo-command-gives-err-yo1-1-0-postinstall-node-scripts-doct
