### ISSUE TITLE
error opening the grunt server

### ISSUE THREAD

**Issue by fabiok12** [yeoman/yo#421]
Hello

I am following the tutorial, and when I trigger the grunt server in mytodos project it works perfectly, but when I create another project, for example, mytodos2 yo returns me this error

warning: running "compass: Server" (compass) task
warning: not found: compass use --force to keep

aborted due to warnings

I have found no solution to this problem

thank you!

**Comment by sindresorhus** [comment]
You need to install `compass` per the error message.

http://stackoverflow.com/questions/21015705/grunt-task-compass-fails-could-not-find-rubygem-compass-0
