### ISSUE TITLE
Reference to composed generators

### ISSUE THREAD

**Issue by wwhurley** [yeoman/yo#422]
Looking at `Base.composeWith` if the current generator is running it just calls the `run` function on it and lets it go. Is there any way to get a reference to it? I see there is a `_composedWith` array, but it's only used if the current generator is not running and then generators in it are invoked later.

**Comment by SBoudrias** [comment]
Generators run in total isolation. There's no way to get a hook to the generator instance.

What do you want to do?

**Comment by wwhurley** [comment]
Maybe that's my trouble, I'm trying to allow inter-generator communication. The use case is as follows:

- Composed generator for Grunt
- Allowing multiple other composed generators to add Grunt tasks and stages and Node dependencies

It would be simpler if I could use the native facilities for these, but due to some idiosyncratic constraints we're unable to do that so I have to expose my own functions. So I need to allow the composed generators to expose functions that other generators can use mediated by the initial generator. So having a way to discover them would be helpful.

**Comment by SBoudrias** [comment]
Try to not over engineer your architecture. Gather data the top level and pass it down.

Then rely on the file-system state to let your generator knows what's expected.

Also, you can checkout the gruntfile editor http://yeoman.io/authoring/gruntfile.html
