### ISSUE TITLE
Prompting generates 'event.js' error

### ISSUE THREAD

**Issue by ruffiem** [yeoman/yo#427]
Crashes with the code from the doc 😞 

```bash
    var done = this.async();
    this.prompt({
      type    : 'input',
      name    : 'name',
      message : 'Your project name',
      default : this.appname // Default to current folder name
    }, function (answers) {
      this.log(answers.name);
      done();
    }.bind(this));
```

Any help appreciated ! See screenshot below, cheers!

![screen shot 2016-05-03 at 17 18 15](https://cloud.githubusercontent.com/assets/1785492/14988169/112210d4-1153-11e6-9303-b6f57087215a.png)

**Comment by SBoudrias** [comment]
You need to update yo: `npm -g update yo`

**Comment by ruffiem** [comment]
Thanks for the quick comeback! Did it already and it keeps crashing... Should I rollback to a prior version of the generator ?

**Comment by SBoudrias** [comment]
So you're using `generator-angular2-application-scaffolder`? I'll check what's up later today.

**Comment by ruffiem** [comment]
Thank you !!

**Comment by SBoudrias** [comment]
So, I didn't see that's your generator.

yeoman-generator v0.23 contains a breaking change regarding the `this.prompt` API. It now returns a promise and doesn't take a callback. You could've see this in our release notes https://github.com/yeoman/generator/releases/tag/v0.23.0

My guess is after updating yo you ran into the API error which was different than the first one you posted here. If the first one persist, then try uninstalling/reinstalling `yo`.

**Comment by ruffiem** [comment]
I haven't checked the change log. That's great, thanks!

Le jeu. 5 mai 2016 à 08:40, Simon Boudrias <notifications@github.com> a
écrit :
