### ISSUE TITLE
Install error in ubuntu 16.04

### ISSUE THREAD

**Issue by darking09** [yeoman/yo#434]
Hi, I have node version 5.2.0 and try on install  I get next error:

- sudo npm install -g yo

`npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js
/usr/local/bin/yo-complete -> /usr/local/lib/node_modules/yo/lib/completion/index.js

> yo@1.8.1 postinstall /usr/local/lib/node_modules/yo
> yodoctor && npm run tabtab

/usr/bin/env: ‘node’: No such file or directory
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! yo@1.8.1 postinstall: `yodoctor && npm run tabtab`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the yo@1.8.1 postinstall script 'yodoctor && npm run tabtab'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor && npm run tabtab
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/darking/npm-debug.log
`

**Comment by SBoudrias** [comment]
Your error is: `/usr/bin/env: ‘node’: No such file or directory`

Looks like node is not in your system path under whichever user was used to run that process.

**Comment by hermeslm** [comment]
The solution for me was install nodejs-legacy:

sudo apt install nodejs-legacy

and it will works.
