### ISSUE TITLE
inquirer module exception on hubot generator install

### ISSUE THREAD

**Issue by dpkshrma** [yeoman/yo#435]
On trying to install hubot using ``` node --debug `which yo` hubot```, the installation halts with this exception:

```
/home/deepak/.nvm/versions/node/v4.2.1/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:77
    throw e;
    ^
true

```
Note - This is the entire exception response.

Version info :
node: v4.2.1
npm: v2.14.7
yo: v1.8.1

**Comment by SBoudrias** [comment]
What happen when you only do `yo hubot`?

What happens if you use `yo@^1.7.0`?

**Comment by dpkshrma** [comment]
@SBoudrias `yo hubot` gives the same output. I used the above command for debugging.
and `yo@^1.7.0` gives me _command not found_ error.

**Comment by SBoudrias** [comment]
Generator-hubot itself is broken ATM. See https://github.com/github/generator-hubot/pull/65
