### ISSUE TITLE
Problems getting npm to install yeoman on el capitan

### ISSUE THREAD

**Issue by zz-james** [yeoman/yo#438]
Hi

After typing `npm install -g yo`
I get a string of red text errors starting with 
`npm ERR! Darwin 15.5.0`

I've attached my npm-debug.log (with added txt suffix so it uploads)
[npm-debug.log.TXT](https://github.com/yeoman/yo/files/270379/npm-debug.log.TXT)

Many Thanks

James

**Comment by kevva** [comment]
#437
