### ISSUE TITLE
ENOENT ERROR INSTALLING YO

### ISSUE THREAD

**Issue by raul1977** [yeoman/yo#439]
I have an error installing Yo with npm, I have the following errors:

Microsoft Windows [Versión 6.3.9600]
(c) 2013 Microsoft Corporation. Todos los derechos reservados.

C:\Windows\system32>npm install -g yo
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm a
nd is now out of date with respect to npm
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! path C:\Users\raulrevillas\AppData\Roaming\npm\node_modules\yo\lib\cli.
js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! enoent ENOENT, chmod 'C:\Users\raulrevillas\AppData\Roaming\npm\node_mo
dules\yo\lib\cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
npm ERR! Please include the following file with any support request:
npm ERR!     C:\Windows\system32\npm-debug.log

Can anyone help me? Thank you very much

**Comment by kevva** [comment]
https://github.com/yeoman/yo/issues/437
