### ISSUE TITLE
yo not finding generator with yeoman-generator keyword

### ISSUE THREAD

**Issue by chluchan** [yeoman/yo#440]
Hello everyone,

I'm trying to get a new generator up and running. It's my first npm package so bear with me...

I published an npm package with the "yeoman-generator" keyword here https://www.npmjs.com/package/generator-geb and I can install it with "npm install -g generator-geb" but the generator doesn't show up when you search for it here http://yeoman.io/generators/ and yo doesn't find the generator after installing it with npm. I end up seeing this: 
`Error geb 

You don't seem to have a generator with the name geb installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 63 registered generators run yo with the `--help` option.
`

If I clone the project and run npm link manually the generator works just fine. How can I get the generator to work when installing it from npm?

**Comment by SBoudrias** [comment]
This line is wrong: https://github.com/chluchan/generator-geb/blob/master/package.json#L11

**Comment by chluchan** [comment]
Thanks! That fixed it!
