### ISSUE TITLE
tabtab feature not working

### ISSUE THREAD

**Issue by Physium** [yeoman/yo#441]
tabtab feature does not seems to be working.

After executing yo <tab><tab> seems to only provide me folder options. Is the feature not working as intended?

**Comment by mklabs** [comment]
What is your shell setup / operating system ?

With as little information, it is very difficult for me to see what is going on. There are known issues with zsh / bash I'm currently working on: https://github.com/mklabs/node-tabtab/issues/21

That being said, thank you for the feedback.

**Comment by Walraz** [comment]
also same problem with tabtab

`/Users/Rasmus/.nvm/versions/node/v6.2.0/lib/node_modules/yo/lib/cli.js:18
var tabtab = new (require('tabtab').Commands.default)({
             ^

TypeError: require(...).Commands.default is not a constructor
    at Object.<anonymous> (/Users/Rasmus/.nvm/versions/node/v6.2.0/lib/node_modules/yo/lib/cli.js:18:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:449:3`

**Comment by DevManny** [comment]
same problem here when I run `yo`

```
/usr/local/lib/node_modules/yo/lib/cli.js:18
var tabtab = new (require('tabtab').Commands.default)({
             ^

TypeError: require(...).Commands.default is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:18:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

```

**Comment by abdulapopoola** [comment]
Also have the same issue on Ubuntu

**Comment by eads** [comment]
Same problem, OS X / bash

**Comment by adrianeguez** [comment]
Hello guys, same problem here! I am using : 
`windows 8`, 
npm version `3.9.2` and 
node version `4.4.4` and 
also with the latest node version now `6.2.0`
only using `yo` in the cmd triggers the error:
```
C:\Users\Adrian\AppData\Roaming\npm\node_modules\yo\lib\cli.js:18
var tabtab = new (require('tabtab').Commands.default)({
             ^

TypeError: require(...).Commands.default is not a function
    at Object.<anonymous> (C:\Users\Adrian\AppData\Roaming\npm\node_modules\yo\l
ib\cli.js:18:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by mklabs** [comment]
Thx guys

@SBoudrias this is due to a new version of tabtab where I added the babel plugin for this, that we discussed here: https://github.com/yeoman/yo/pull/436#discussion_r63633707

#442 should fix it

**Comment by adrianeguez** [comment]
I did not understand #442 :cry: what should I do? unninstall tab tab and reinstall globally with another version?

**Comment by mklabs** [comment]
I'll try to unpublish tabtab v1.4 and see if it fixes the issue here.

The problem here is that you most likely have the latest version of tabtab installed with yo, (tabtab@1.4.x) which introduces a change in how babel compiles the generated code. Yo in his current state is compatible with `1.3.x`

It goes in pair with #442 which is not merged yet.

**Comment by mklabs** [comment]
Just unpublished, it should fix your issue with yo. Can anyone confirm yo installs fine now ? It did on my local machine.

Sorry, all my fault. Unintended side effect of publishing a new version of tabtab in order to work on #442

**Comment by MichaelPruefer** [comment]
Great!
Works now on Win 10, npm 3.9.2, node 4.4.4

**Comment by eads** [comment]
@mklabs working now on OS X / bash / npm 3.9.2 / node 4.2.1

**Comment by adrianeguez** [comment]
It fixed it on my local yo,
changed  `package.json`
```javascript
...
    "tabtab": "1.3.0",
...
```
Thanks!

**Comment by mklabs** [comment]
Great, thanks a lot.

@Physium I don't think it was related to your original issue, feel free to keep this issue open and provide more feedback, that being said #442 should improve zsh / bash completions a lot.

**Comment by Walraz** [comment]
@mklabs works fine now with reiinstall of yo! zsh on OSX

**Comment by mklabs** [comment]
@Walraz :+1:

**Comment by DevManny** [comment]
Thanks, works now

```
npm uninstall -g yo
npm install -g yo
```

**Comment by Physium** [comment]
@mklabs 

> Just unpublished, it should fix your issue with yo. Can anyone confirm yo installs fine now ? It did on my local machine.

Hi! Sry for going missing throughout the weekend after posting this issue. I just did a reinstall and notice that it didnt prompt me about the yo-complete feature. I'm assuming that this means that the yo-complete tabtab feature has been remove from for now till #442 has been merge?

**Comment by mklabs** [comment]
Hi @Physium no worries.

Let's continue this discussion on tabtab repo. Yes, the completion feature don't prompt on install anymore, you can get these prompts with `yo completion` right now. #442 will change that (not merged yet)

**Comment by davidsidlinger** [comment]
I am seeing this come up on macOS Sierra. At the moment, I am working around the problem by installing an older version of the package. Sad face.

```
/usr/local/lib/node_modules/yo/lib/cli.js:18
var tabtab = new (require('tabtab').Commands.default)({
             ^

TypeError: require(...).Commands.default is not a constructor
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:18:14)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

Output of `npm install -g yo`:

```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/usr/local/bin/yo -> /usr/local/lib/node_modules/yo/lib/cli.js
/usr/local/bin/yo-complete -> /usr/local/lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall


> yo@1.8.5 postinstall /usr/local/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
```

Output of `npm list -g tabtab`:

```
/usr/local/lib
└─┬ yo@1.8.5
  └── tabtab@1.4.3
```

node: v6.7.0
npm: v3.10.8
fish shell: 2.3.1
macOS 10.12 (16A323)

**Comment by mklabs** [comment]
@davidsidlinger I published a new version of tabtab today but didn't remembered the integration in yo. I unpublished it, it should be okay now.

**Comment by bike2live** [comment]
I get the same error as @davidsidlinger.

node: 5.9.1
npm: 3.8.9
macOS 10.12
bash 3.2

Is the only work-around manually setting the version of tabtab to 1.3.x?

**Comment by mklabs** [comment]
Hi @bike2live, if you try to uninstall yo and reinstall it should install tabtab in its latest 1.x version which is now 1.3.2 now that I unpublished 1.4.3

**Comment by bike2live** [comment]
That appears to have solved the issue. Thanks for the quick response.

**Comment by davidsidlinger** [comment]
Echoing @bike2live. I am up and running on `yo@1.8.5`. Thanks for your help, @mklabs.
