### ISSUE TITLE
Main generator not detected correctly by router when starting generator from home menu in cli

### ISSUE THREAD

**Issue by mlenkeit** [yeoman/yo#444]
I'm creating a generator with sub-generators. My `generators` folder contains `app` (main generator) and `sub-app` (sub-generator) among other sub-generators.
When I call `yo` on the command line and select my generator from the menu, instead of executing the `app` generator, the `sub-app` generator is executed.

I believe the fix is as easy as changing the regex to `/:(app|all)$/`[in the router](https://github.com/yeoman/yo/blob/master/lib/router.js#L60) (note the colon).

I can provide a PR. However, in order to provide proper tests for that bug, I would need to add an additional devDependency such as [rewire](https://www.npmjs.com/package/rewire) to mock reading `package.json`.

What do you think?

**Comment by SBoudrias** [comment]
You'd actually want to stub `this.env.getGeneratorsMeta()` return value. And you can use `sinon` or `proxyquire` for that instead of adding a new dependency.

PR welcomed

**Comment by mlenkeit** [comment]
I created PR #447, let's continue there.
