### ISSUE TITLE
Generator didn't show an error that bower was not installed globally and just skip bower task

### ISSUE THREAD

**Issue by SychevIgor** [yeoman/yo#445]
At least it should show that bower not installed and will be skipped.

![image](https://cloud.githubusercontent.com/assets/578954/15551790/989d35b2-22c8-11e6-8289-bf45eda9a76d.png)

C:\t>yo aspnet

     _-----_
    |       |    .--------------------------.
    |--(o)--|    |      Welcome to the      |
   `---------´   |  marvellous ASP.NET Core |
    ( _´U`_ )    |      1.0 generator!      |
    /___A___\    '--------------------------'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? What type of application do you want to create? Web Application Basic [without Membership and Authorization]
? Which UI framework would you like to use? Bootstrap (3.3.6)
? What's the name of your ASP.NET application? yoaspnet
   create yoaspnet\gulpfile.js
   create yoaspnet\Dockerfile
   create yoaspnet\.bowerrc
   create yoaspnet\.gitignore
   create yoaspnet\bower.json
   create yoaspnet\appsettings.json
   create yoaspnet\package.json
   create yoaspnet\project.json
   create yoaspnet\Program.cs
   create yoaspnet\Properties\launchSettings.json
   create yoaspnet\README.md
   create yoaspnet\Startup.cs
   create yoaspnet\web.config
   create yoaspnet\Controllers\HomeController.cs
   create yoaspnet\Views\_ViewImports.cshtml
   create yoaspnet\Views\_ViewStart.cshtml
   create yoaspnet\Views\Home\About.cshtml
   create yoaspnet\Views\Home\Contact.cshtml
   create yoaspnet\Views\Home\Index.cshtml
   create yoaspnet\Views\Shared\_Layout.cshtml
   create yoaspnet\Views\Shared\Error.cshtml
   create yoaspnet\wwwroot\css\site.css
   create yoaspnet\wwwroot\css\site.min.css
   create yoaspnet\wwwroot\favicon.ico
   create yoaspnet\wwwroot\images\banner1.svg
   create yoaspnet\wwwroot\images\banner2.svg
   create yoaspnet\wwwroot\images\banner3.svg
   create yoaspnet\wwwroot\images\banner4.svg
   create yoaspnet\wwwroot\js\site.js
   create yoaspnet\wwwroot\js\site.min.js

I'm all done. Running npm install & bower install for you to install the required dependencies. If this fails, try running the command yourself.

npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
yoaspnet@0.0.0 C:\t\yoaspnet
+-- gulp@3.9.1
| +-- archy@1.0.0
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.0.0
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- deprecated@0.0.1
| +-- gulp-util@3.0.7
| | +-- array-differ@1.0.0
| | +-- array-uniq@1.0.2
| | +-- beeper@1.1.0
| | +-- dateformat@1.0.12
| | | +-- get-stdin@4.0.1
| | | `-- meow@3.7.0
| | |   +-- camelcase-keys@2.1.0
| | |   | `-- camelcase@2.1.1
| | |   +-- loud-rejection@1.3.0
| | |   | +-- array-find-index@1.0.1
| | |   | `-- signal-exit@2.1.2
| | |   +-- map-obj@1.0.1
| | |   +-- normalize-package-data@2.3.5
| | |   | +-- hosted-git-info@2.1.5
| | |   | +-- is-builtin-module@1.0.0
| | |   | | `-- builtin-modules@1.1.1
| | |   | `-- validate-npm-package-license@3.0.1
| | |   |   +-- spdx-correct@1.0.2
| | |   |   | `-- spdx-license-ids@1.2.1
| | |   |   `-- spdx-expression-parse@1.0.2
| | |   |     `-- spdx-exceptions@1.0.4
| | |   +-- object-assign@4.1.0
| | |   +-- read-pkg-up@1.0.1
| | |   | +-- find-up@1.1.2
| | |   | | +-- path-exists@2.1.0
| | |   | | `-- pinkie-promise@2.0.1
| | |   | |   `-- pinkie@2.0.4
| | |   | `-- read-pkg@1.1.0
| | |   |   +-- load-json-file@1.1.0
| | |   |   | +-- graceful-fs@4.1.4
| | |   |   | +-- parse-json@2.2.0
| | |   |   | | `-- error-ex@1.3.0
| | |   |   | |   `-- is-arrayish@0.2.1
| | |   |   | +-- pify@2.3.0
| | |   |   | `-- strip-bom@2.0.0
| | |   |   `-- path-type@1.1.0
| | |   +-- redent@1.0.0
| | |   | +-- indent-string@2.1.0
| | |   | | `-- repeating@2.0.1
| | |   | |   `-- is-finite@1.0.1
| | |   | |     `-- number-is-nan@1.0.0
| | |   | `-- strip-indent@1.0.1
| | |   `-- trim-newlines@1.0.0
| | +-- gulplog@1.0.0
| | | `-- glogg@1.0.0
| | +-- has-gulplog@0.1.0
| | | `-- sparkles@1.0.0
| | +-- lodash._reescape@3.0.0
| | +-- lodash._reevaluate@3.0.0
| | +-- lodash._reinterpolate@3.0.0
| | +-- lodash.template@3.6.2
| | | +-- lodash._basecopy@3.0.1
| | | +-- lodash._basetostring@3.0.1
| | | +-- lodash._basevalues@3.0.0
| | | +-- lodash._isiterateecall@3.0.9
| | | +-- lodash.escape@3.2.0
| | | | `-- lodash._root@3.0.1
| | | +-- lodash.keys@3.1.2
| | | | +-- lodash._getnative@3.9.1
| | | | +-- lodash.isarguments@3.0.8
| | | | `-- lodash.isarray@3.0.4
| | | +-- lodash.restparam@3.6.1
| | | `-- lodash.templatesettings@3.1.1
| | +-- multipipe@0.1.2
| | | `-- duplexer2@0.0.2
| | |   `-- readable-stream@1.1.14
| | +-- object-assign@3.0.0
| | +-- replace-ext@0.0.1
| | `-- vinyl@0.5.3
| |   +-- clone@1.0.2
| |   `-- clone-stats@0.0.1
| +-- interpret@1.0.1
| +-- liftoff@2.2.1
| | +-- extend@2.0.1
| | +-- findup-sync@0.3.0
| | | `-- glob@5.0.15
| | +-- flagged-respawn@0.3.2
| | +-- rechoir@0.6.2
| | `-- resolve@1.1.7
| +-- minimist@1.2.0
| +-- orchestrator@0.3.7
| | +-- end-of-stream@0.1.5
| | +-- sequencify@0.0.7
| | `-- stream-consume@0.1.0
| +-- pretty-hrtime@1.0.2
| +-- semver@4.3.6
| +-- tildify@1.2.0
| | `-- os-homedir@1.0.1
| +-- v8flags@2.0.11
| | `-- user-home@1.1.1
| `-- vinyl-fs@0.3.14
|   +-- defaults@1.0.3
|   +-- glob-stream@3.1.18
|   | +-- glob@4.5.3
|   | +-- glob2base@0.0.12
|   | | `-- find-index@0.1.1
|   | +-- minimatch@2.0.10
|   | +-- ordered-read-streams@0.1.0
|   | +-- through2@0.6.5
|   | | `-- readable-stream@1.0.34
|   | `-- unique-stream@1.0.0
|   +-- glob-watcher@0.0.6
|   | `-- gaze@0.5.2
|   |   `-- globule@0.1.0
|   |     +-- glob@3.1.21
|   |     | +-- graceful-fs@1.2.3
|   |     | `-- inherits@1.0.2
|   |     +-- lodash@1.0.2
|   |     `-- minimatch@0.2.14
|   |       +-- lru-cache@2.7.3
|   |       `-- sigmund@1.0.1
|   +-- graceful-fs@3.0.8
|   +-- mkdirp@0.5.1
|   | `-- minimist@0.0.8
|   +-- strip-bom@1.0.0
|   | +-- first-chunk-stream@1.0.0
|   | `-- is-utf8@0.2.1
|   +-- through2@0.6.5
|   | `-- readable-stream@1.0.34
|   `-- vinyl@0.4.6
|     `-- clone@0.2.0
+-- gulp-concat@2.6.0
| +-- concat-with-sourcemaps@1.0.4
| | `-- source-map@0.5.6
| `-- through2@0.6.5
|   +-- readable-stream@1.0.34
|   | +-- core-util-is@1.0.2
|   | +-- isarray@0.0.1
|   | `-- string_decoder@0.10.31
|   `-- xtend@4.0.1
+-- gulp-cssmin@0.1.7
| +-- clean-css@3.4.13
| | +-- commander@2.8.1
| | | `-- graceful-readlink@1.0.1
| | `-- source-map@0.4.4
| |   `-- amdefine@1.0.0
| +-- filesize@2.0.4
| +-- graceful-fs@2.0.3
| +-- gulp-rename@1.1.0
| +-- gulp-util@2.2.20
| | +-- chalk@0.5.1
| | | +-- ansi-styles@1.1.0
| | | +-- has-ansi@0.1.0
| | | | `-- ansi-regex@0.2.1
| | | +-- strip-ansi@0.3.0
| | | `-- supports-color@0.2.0
| | +-- lodash._reinterpolate@2.4.1
| | +-- lodash.template@2.4.1
| | | +-- lodash._escapestringchar@2.4.1
| | | +-- lodash.defaults@2.4.1
| | | | +-- lodash._objecttypes@2.4.1
| | | | `-- lodash.keys@2.4.1
| | | +-- lodash.escape@2.4.1
| | | | +-- lodash._escapehtmlchar@2.4.1
| | | | | `-- lodash._htmlescapes@2.4.1
| | | | `-- lodash._reunescapedhtml@2.4.1
| | | |   `-- lodash.keys@2.4.1
| | | +-- lodash.keys@2.4.1
| | | | +-- lodash._isnative@2.4.1
| | | | +-- lodash._shimkeys@2.4.1
| | | | `-- lodash.isobject@2.4.1
| | | +-- lodash.templatesettings@2.4.1
| | | `-- lodash.values@2.4.1
| | |   `-- lodash.keys@2.4.1
| | +-- minimist@0.2.0
| | +-- through2@0.5.1
| | | +-- readable-stream@1.0.34
| | | `-- xtend@3.0.0
| | `-- vinyl@0.2.3
| +-- map-stream@0.0.4
| `-- temp-write@0.1.1
|   +-- graceful-fs@2.0.3
|   `-- tempfile@0.1.3
|     `-- uuid@1.4.2
+-- gulp-uglify@1.5.3
| +-- deap@1.0.0
| +-- fancy-log@1.2.0
| | `-- time-stamp@1.0.1
| +-- isobject@2.1.0
| | `-- isarray@1.0.0
| +-- through2@2.0.1
| | `-- readable-stream@2.0.6
| |   +-- isarray@1.0.0
| |   +-- process-nextick-args@1.0.7
| |   `-- util-deprecate@1.0.2
| +-- uglify-js@2.6.2
| | +-- async@0.2.10
| | +-- uglify-to-browserify@1.0.2
| | `-- yargs@3.10.0
| |   +-- camelcase@1.2.1
| |   +-- cliui@2.1.0
| |   | +-- center-align@0.1.3
| |   | | +-- align-text@0.1.4
| |   | | | +-- kind-of@3.0.3
| |   | | | | `-- is-buffer@1.1.3
| |   | | | +-- longest@1.0.1
| |   | | | `-- repeat-string@1.5.4
| |   | | `-- lazy-cache@1.0.4
| |   | +-- right-align@0.1.3
| |   | `-- wordwrap@0.0.2
| |   +-- decamelize@1.2.0
| |   `-- window-size@0.1.0
| +-- uglify-save-license@0.4.1
| `-- vinyl-sourcemaps-apply@0.2.1
`-- rimraf@2.5.2
  `-- glob@7.0.3
    +-- inflight@1.0.5
    | `-- wrappy@1.0.2
    +-- inherits@2.0.1
    +-- minimatch@3.0.0
    | `-- brace-expansion@1.1.4
    |   +-- balanced-match@0.4.1
    |   `-- concat-map@0.0.1
    +-- once@1.3.3
    `-- path-is-absolute@1.0.0

'bower' is not recognized as an internal or external command,
operable program or batch file.

Your project is now created, you can use the following commands to get going
    cd "yoaspnet"
    dotnet restore
    dotnet build (optional, build will also happen when it's run)
    dotnet run

**Comment by SBoudrias** [comment]
Doesn't the warning let you know that?

> 'bower' is not recognized as an internal or external command,
> operable program or batch file.

**Comment by SychevIgor** [comment]
My bad. Could we highlight it somehow better in a console? I didn't recognize it.
