### ISSUE TITLE
Composing yo within another module

### ISSUE THREAD

**Issue by noffle** [yeoman/yo#448]
Is there a suggested approach for running a yeoman generator using `yo` from within another module?

This would normally be easily done with `require.resolve('yo')` to fish out the location of of `bin/cli.js`, but yo's `package.json` points at `lib`, which makes `require()` fail to find it. Is this intentional? How might I best compose `yo`?

**Comment by SBoudrias** [comment]
@noffle we have documentation about this here http://yeoman.io/authoring/integrating-yeoman.html

Basically, you'll want to use `yeoman-environment`, `yo` is only a UI layer over the yeoman framework.
