### ISSUE TITLE
Option to use different template syntax

### ISSUE THREAD

**Issue by breandr** [yeoman/yo#456]
Is there currently any way of using a template syntax other than EJS? For example, if I wanted to use Mustache instead. Has this been discussed before?

**Comment by SBoudrias** [comment]
Feel free to load your own template engine and process templates if you want. Generators are only Node modules.

This is not something the core will be offering.

Also, just an FYI, if you have further core related feature request, please prefer using the core repository https://github.com/yeoman/generator - and for question/discussion, join us on gitter https://gitter.im/yeoman/yeoman :)
