### ISSUE TITLE
npmconf@2.1.2 deprecated error message during install of yeoman 

### ISSUE THREAD

**Issue by iandstanley** [yeoman/yo#461]
Just installed yeoman for the first time this morning and got this error ... figured the build package needs updating somewhere

> npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

NPR Version ... 
> $ npm -g yo 
> │ /usr/local/lib
> └── yo@1.8.4 
>     CLI tool for running Yeoman generators
>     git+https://github.com/yeoman/yo.git
>     http://yeoman.io

**Comment by SBoudrias** [comment]
This can be pretty much any package we rely upon. It's only a warning, so it really doesn't matter.

**Comment by francescopersico** [comment]
It is fullname@2.1.0
