### ISSUE TITLE
Docker build for aspnet web application fails due to apt-get install

### ISSUE THREAD

**Issue by naamunds** [yeoman/yo#462]
## Steps to reproduce
1. Run `yo aspnet`
2. Select "Web Application"
3. Select "Bootstrap (3.3.6)"
4. Accept the default project name ("WebApplication").
5. `cd WebApplication`
6. `docker build -t aspnet-app .`

## Results
The Docker build fails, ending with the following output:

> The following extra packages will be installed:
  libc-dev-bin libc6-dev linux-libc-dev manpages manpages-dev
Suggested packages:
  glibc-doc sqlite3-doc man-browser
The following NEW packages will be installed:
  libc-dev-bin libc6-dev libsqlite3-dev linux-libc-dev manpages manpages-dev
  sqlite3
0 upgraded, 7 newly installed, 0 to remove and 1 not upgraded.
Need to get 6766 kB of archives.
After this operation, 20.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
The command '/bin/sh -c apt-get update && apt-get install sqlite3 libsqlite3-dev' returned a non-zero code: 1

## Environment
OS: Mac OS 10.11.5
Yeoman version: 1.8.4

## Recommendation
Adding the `-y` option to the `apt-get install` command in the Dockerfile fixes the issue.
https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/apt-get has more info on using apt-get in Dockerfiles.

**Comment by eddiemonge** [comment]
Please open this at the aspnet generator since it sounds like a problem there and not with yo

**Comment by naamunds** [comment]
@eddiemonge Thanks for the quick response.  Where is the repo for the aspnet generator?  I see repos for other generators in https://github.com/yeoman, but not for aspnet.  Is it a private repo?

**Comment by naamunds** [comment]
I think I found it.  It looks like this issue was fixed in https://github.com/OmniSharp/generator-aspnet/pull/787
