### ISSUE TITLE
yo interaction is failing in some parts, arrows and space

### ISSUE THREAD

**Issue by giovannipds** [yeoman/yo#464]
Hello. `yo` interaction is failing for me in some parts. When I run `yo`, I'm not able to interact in the first part (generators, update, etc.), the later on, about SASS, Bootstrap, Modernizr, I also cannot interact, but the last on about DSL style, BDD or TDD, I can interact normally.

`yo doctor` is fine;
`yo --version`: 1.8.4;
`node --version`: v5.10.1;
Unfortunately Windows, 10;
Using Node.js cmd.

Should I update node? LTS or latest?

Thanks in advance for the support.

**Comment by SBoudrias** [comment]
Your node version include a broken readline version on Windows. You can check out https://github.com/nodejs/node/issues/5384 for more context.

**Comment by giovannipds** [comment]
Wow, what a quick response. Thanks @SBoudrias! I'd check that and update node. Thanks again.

**Comment by giovannipds** [comment]
Yep, updating node.js it started to work again. =D o/
