### ISSUE TITLE
sh: yodoctor: command not found

### ISSUE THREAD

**Issue by baksosapi** [yeoman/yo#465]
ian-mbp:symfongular wildan$ npm install -g yo
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
/Users/wildan/.node_modules_global/bin/yo -> /Users/wildan/.node_modules_global/lib/node_modules/yo/lib/cli.js
/Users/wildan/.node_modules_global/bin/yo-complete -> /Users/wildan/.node_modules_global/lib/node_modules/yo/lib/completion/index.js

> spawn-sync@1.0.15 postinstall /Users/wildan/.node_modules_global/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall

> yo@1.8.4 postinstall /Users/wildan/.node_modules_global/lib/node_modules/yo
> yodoctor

sh: yodoctor: command not found
npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.2.0/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! yo@1.8.4 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the yo@1.8.4 postinstall script 'yodoctor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wildan/Myproject/SYMFONY/symfongular/npm-debug.log

**Comment by SBoudrias** [comment]
Please, please, do search google when having issues. A lot of people uses Yeoman and it takes us forever to answer everybody. Please be mindful of the limited resource Open Source project have and start by searching yourself by a solution previously posted.

In this case, you'll want to read http://stackoverflow.com/questions/33487085/yodoctor-command-not-found-when-installing-yo-from-terminal

**Comment by baksosapi** [comment]
ok, thanx,
solved by uninstall n install .. cmiww..

**Comment by Pysis868** [comment]
[Simon Boudrias' answer](https://stackoverflow.com/a/35170199/1091943) was my situation.

I first used [febLay's approach](https://stackoverflow.com/a/25447784/1091943) for changing my npm prefix to my user folder.

After a `npm install -g npm`, and another `npm install -g yo`, I get:
```
...
> yo@2.0.0 postinstall /Users/jsmall/.node_modules/lib/node_modules/yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
+ yo@2.0.0
added 371 packages in 12.342s
```
