### ISSUE TITLE
Unhandled 'error' event when running Fountain Webapp and missing serve

### ISSUE THREAD

**Issue by YewTreeWeb** [yeoman/yo#466]
Hi, 

Every time I try to follow the tutorial for Yeoman and select the options within Fountain Webapp I get the below error:

events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: this.options.ci.includes is not a function
    at writing (/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-gulp/generators/ci/index.js:7:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-fountain-webapp/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-fountain-webapp/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-fountain-webapp/node_modules/yeoman-generator/lib/base.js:432:9
    at processImmediate [as _immediateCallback] (timers.js:383:17)

I also get the below error when trying the command 'npm run serve':

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "serve"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.6

npm ERR! missing script: serve
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Mat/Websites/Git/yeoman-website/webapp/starter/npm-debug.log

I have Yeoman 1.8.4 install and running the latest npm, node, OS for my Mac. Is there anything I am doing wrong? 

Thank you for taking the time to read my issue. I look forward to your reply.

**Comment by sindresorhus** [comment]
The error is coming from `generator-fountain-webapp`. Open an issue there.
