### ISSUE TITLE
npm WARN deprecated

### ISSUE THREAD

**Issue by AustinMH** [yeoman/yo#472]
Hi,

I receive a warning at the $ npm install --global yo stage of set up at http://yeoman.io/codelab/setup.html. Below is my screenshot of the problem.
 
![screen shot 2016-09-09 at 1 56 45 pm](https://cloud.githubusercontent.com/assets/11987394/18399147/4cf737ae-7695-11e6-983b-d186690ada6b.png)

I'm running OS X 10.11.6 El Capitan. Node 4.5.0 and NPM 2.15.9. 

Thanks,

Austin.

**Comment by SBoudrias** [comment]
http://stackoverflow.com/questions/33487085/yodoctor-command-not-found-when-installing-yo-from-terminal

**Comment by AustinMH** [comment]
Trying number 3. After entering export PATH=“/path/to/node_modules/.bin:$PATH" to command line, I get an angle bracket prompt. What do I do? http://notions.me/post/adding-npm-bin-to-path does not make it clear.

![screen shot 2016-09-09 at 2 55 32 pm](https://cloud.githubusercontent.com/assets/11987394/18400908/7b5a3f26-769d-11e6-9dfd-d2fdf5d40a26.png)

**Comment by SBoudrias** [comment]
@AustinMH looks like you use an angled `"` instead of a normal `"`.

**Comment by AustinMH** [comment]
@SBoudrias Thanks! I fixed the brackets and got this:
![screen shot 2016-09-09 at 3 36 16 pm](https://cloud.githubusercontent.com/assets/11987394/18402076/565e1ad4-76a3-11e6-89b7-56d71e94ce1b.png)

How do I know if the global npm module folders is chown/chmod to me?
![screen shot 2016-09-09 at 3 57 56 pm](https://cloud.githubusercontent.com/assets/11987394/18402685/3d86d566-76a6-11e6-93b1-0b148e9c8477.png)
![screen shot 2016-09-09 at 3 57 54 pm](https://cloud.githubusercontent.com/assets/11987394/18402686/3d8724b2-76a6-11e6-8edd-924d775d5014.png)
![screen shot 2016-09-09 at 3 57 48 pm](https://cloud.githubusercontent.com/assets/11987394/18402687/3d8ab1e0-76a6-11e6-9371-a6de698fc75b.png)
![screen shot 2016-09-09 at 3 57 42 pm](https://cloud.githubusercontent.com/assets/11987394/18402688/3d8cd826-76a6-11e6-90d4-d68f4063534f.png)
![screen shot 2016-09-09 at 3 57 36 pm](https://cloud.githubusercontent.com/assets/11987394/18402689/3d8f7806-76a6-11e6-8220-7d385cfbe94c.png)
![screen shot 2016-09-09 at 3 57 32 pm](https://cloud.githubusercontent.com/assets/11987394/18402690/3d929298-76a6-11e6-8828-c4f87ef903ea.png)
![screen shot 2016-09-09 at 3 57 27 pm](https://cloud.githubusercontent.com/assets/11987394/18402691/3d95b586-76a6-11e6-9e1d-3729871efab8.png)
![screen shot 2016-09-09 at 3 57 21 pm](https://cloud.githubusercontent.com/assets/11987394/18402692/3d9839e6-76a6-11e6-88a8-e8c606361d9b.png)
![screen shot 2016-09-09 at 3 57 17 pm](https://cloud.githubusercontent.com/assets/11987394/18402693/3d9be140-76a6-11e6-8ff9-d353d7c310b7.png)
![screen shot 2016-09-09 at 3 57 12 pm](https://cloud.githubusercontent.com/assets/11987394/18402694/3d9f3ce6-76a6-11e6-9737-71ec3c789d29.png)
![screen shot 2016-09-09 at 3 57 03 pm](https://cloud.githubusercontent.com/assets/11987394/18402695/3d9f9c36-76a6-11e6-815b-8fd7c30e29ec.png)

**Comment by SBoudrias** [comment]
`/path/to/x` was an example value. You need to change it to match your own computer file layout.

**Comment by AustinMH** [comment]
So, when I enter "npm list -g" I get the location "/Users/austinmunsch-hayhurst/.node_modules_global/lib", So would I "export PATH=“/Users/austinmunsch-hayhurst/.node_modules_global/lib/.bin:$PATH"?

**Comment by SBoudrias** [comment]
@AustinMH if you `cd` in that folder, you can check where the `.bin` folder is located

**Comment by AustinMH** [comment]
I'm getting "No such file or directory" even though "npm list -g" finds it at "/Users/austinmunsch-hayhurst/.node_modules_global/lib". Am I missing the right syntax in using cd here?

![screen shot 2016-09-09 at 4 27 22 pm](https://cloud.githubusercontent.com/assets/11987394/18403470/9d70ad04-76aa-11e6-88e7-11c51853b5e5.png)
 
![screen shot 2016-09-09 at 4 27 37 pm](https://cloud.githubusercontent.com/assets/11987394/18403472/a2808760-76aa-11e6-8171-fa30356acd9d.png)

**Comment by SBoudrias** [comment]
did you try `npm prefix -g`?

**Comment by AustinMH** [comment]
![screen shot 2016-09-09 at 4 41 51 pm](https://cloud.githubusercontent.com/assets/11987394/18403761/59fed9ea-76ac-11e6-8e4f-92ca888848ee.png)

**Comment by AustinMH** [comment]
Here, I used "npm bin" to locate the bin folder. I used the path it gave in the "export PATH=“/path/to/node_modules/.bin:$PATH"" formula, but after checking .bash_profile, everything was still unchanged.

![screen shot 2016-09-09 at 4 45 50 pm](https://cloud.githubusercontent.com/assets/11987394/18403920/2ad15660-76ad-11e6-8de4-5986cc472aaa.png)
