### ISSUE TITLE
EPERM errors while installing

### ISSUE THREAD

**Issue by ChadCrank** [yeoman/yo#473]
Hello 
I'm trying to install Yomen generator on a user's computer and I receive the errors in the screen shots. This is my first time working with Powershell and installing these generators. Is there a way to resolve these issues?
![yomen install error](https://cloud.githubusercontent.com/assets/22158395/18452534/168dba82-78f0-11e6-81d8-d8730fd31861.JPG)
![yomen install error 2](https://cloud.githubusercontent.com/assets/22158395/18452533/168daf06-78f0-11e6-8516-3d6f476fe6af.JPG)

**Comment by SBoudrias** [comment]
Please read the error message and try searching on google before opening issues and asking for support.

This might help: http://stackoverflow.com/questions/34600932/npm-eperm-operation-not-permitted-on-windows
