### ISSUE TITLE
"Your npm version is outdated"

### ISSUE THREAD

**Issue by tom-seddon** [yeoman/yo#475]
I'm using npm 3.10.8. I'm quite prepared to believe this could be outdated - it is the best part of a month old after all - but there don't appear to be any newer versions available...

If I need to upgrade, which version should I be using?

If not, what can I do to figure out why yodoctor is getting this wrong?

Thanks,

--Tom

[OS X 10.11.6, node.js 6.7.0]

**Comment by tom-seddon** [comment]
The error message above popped up while running yodoctor as part of the `npm install` step for a project.

When I do `npm install -g yo`, it does work.

--Tom

**Comment by SBoudrias** [comment]
I think you might have multiple npm instances on your machine then.

**Comment by sindresorhus** [comment]
http://stackoverflow.com/questions/28225938/why-do-i-have-two-versions-of-npm

**Comment by tom-seddon** [comment]
I've checked and I only have 1 copy of npm on the PATH, unless yeoman is doing something very weird, in which case it should stop ;)

It looks like the root npm package that I'm trying to install depends on ember-cli version something, which depends on npm 2.something. Best guess: that's the one that yeoman is finding during its install process. I'm assuming npm does something with PATH while it does its thing, and that's why the -g one works as expected.

(I wonder why ember does this? How can a package depend on npm when npm isn't installed already? One for the philosophers I suppose.)

--Tom
