### ISSUE TITLE
TypeError: require(...).Commands.default is not a function

### ISSUE THREAD

**Issue by vivaladan** [yeoman/yo#477]
I've read about this issue around May 2016 time which was apparently fixed already. However I've installed latest on two different machines and get this same error.

<img width="524" alt="yo error" src="https://cloud.githubusercontent.com/assets/1514212/18991754/538f0082-8712-11e6-951b-003c283da7a4.PNG">

**Comment by korneel** [comment]
@vivaladan How did you solve this?
