### ISSUE TITLE
TypeError: require(...).Commands.default is not a function

### ISSUE THREAD

**Issue by vivaladan** [yeoman/yo#478]
I've read about this issue around May 2016 time which was apparently fixed already. However I've installed latest on two different machines and get this same error.

<img width="524" alt="yo error" src="https://cloud.githubusercontent.com/assets/1514212/18991754/538f0082-8712-11e6-951b-003c283da7a4.PNG">

I realise the screenshot is wrong. I'm running yo 1.8.5

tabtab 1.4.3 got released 2 hours ago it appears.

**Comment by xtoff** [comment]
I'm facing the same problem atm. 
Node: v4.6.0
Npm: v3.10.8

**Comment by jledentu** [comment]
Same problem here.
Node: v6.2.2
npm: 3.9.5

**Comment by korneel** [comment]
Same problem.

Windows 10
nvm 1.1.1
npm 3.10.8
node 6.7.0

**Comment by erikmartinessanches** [comment]
Same problem. 
OS X 10.11.6
npm 3.10.3
node 6.3.1
Installed what appears to be tabtab 1.3.2, though it doesn't mention it using --version.

**Comment by YerkoPalma** [comment]
Same issue here. I fix this locally by changing [this line](https://github.com/yeoman/yo/blob/master/lib/cli.js#L18) to this

```javascript
var tabtab = new (require('tabtab').Commands)({
```

just remove the `default` property of Commands :+1:

**Comment by Extazium** [comment]
Thanks @YerkoPalma for the temporary fix.

**Comment by mklabs** [comment]
Hi there, I unpublished version 1.4.3 in favor to a new one 2.0.0 which hopefully fix this issue.

**Comment by jledentu** [comment]
Thanks @mklabs for resolving this issue, it works now.

**Comment by SBoudrias** [comment]
Thanks for the fix @mklabs 

Closing this issue now.
