### ISSUE TITLE
Can't update to the latest version

### ISSUE THREAD

**Issue by heinhoang** [yeoman/yo#483]
my yo current version is 1.7.0
NodeJS v5.9.0
my OS is Windows 8
I'd like to update yo to latest version (1.8.5). 
I run "npm install -g yo" to update but it's no use. The version remains 1.7.0 after that.

**Comment by SBoudrias** [comment]
You probably have two npm version installed on your computer. I'd suggest checking where your PATH variable npm bin folder points to and change it to your new version bin path.
