### ISSUE TITLE
Unable to view generators on yeoman.io

### ISSUE THREAD

**Issue by jzgdev** [yeoman/yo#484]
traced back to `generator.js:25 Uncaught TypeError: a.sort is not a function(…)` according to my console.

**Comment by mischah** [comment]
It works over here. Using Chrome 54.

**Comment by mischah** [comment]
There is something in the making to fix the current behavior of the generator list over here btw: https://github.com/yeoman/yeoman-generator-list/pull/51

**Comment by jzgdev** [comment]
Generators showing up for me now. Also on Chrome 54
