### ISSUE TITLE
Drop `pinkie-promise`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [yeoman/yo#487]
Promises are natively supported in `node >= 0.12`, which `yo` supports.

**Comment by mischah** [comment]
[True indeed](http://node.green/).

Guess we would accept a pull request :octocat:

**Comment by mischah** [comment]
@SBoudrias `:thumbsup:`?

**Comment by addyosmani** [comment]
With https://github.com/yeoman/yo/commit/1d22d1cf61f5dbc792c6a32c131f88077c28ed57 now in, this does look fine to drop as a dependency.
