### ISSUE TITLE
update yo through npm,but still show the order version

### ISSUE THREAD

**Issue by jxintang** [yeoman/yo#493]
I use npm update -g yo to update yo from 1.2.0 to 1.8.5. and everything looks fine.
![image](https://cloud.githubusercontent.com/assets/5434292/20801301/5f8277f6-b823-11e6-9daa-727f408e8cc6.png)
the 1.8.5 is installed under folder /Users/xxxxxx/.nvm/versions/node/v4.2.1/lib/node_modules/yo
but when type yo -v,it still shows 1.2.0, I don't know why,maybe I install yo through another package manager previously
what should I do now?

npm version 3.10.7
node version 4.2.1

**Comment by SBoudrias** [comment]
You can see where the version of you is using `where yo` on windows, and `which yo` on Unix systems.

What you'll find out is that you most probably have multiple versions of npm installed, and the node modules in your PATH variable doesn't match your most recent version.

**Comment by mischah** [comment]
Check if there still is a `node_modules` directory in `/usr/local/lib` holding your globally installed packages from an old node version installed before you set up nvm.

**Comment by jxintang** [comment]
@SBoudrias @mischah  tks! problem solved

**Comment by peterremote1980** [comment]
i got same issue when creating sharepoint spfx project, it sill give me old version in package.json, i need to update it manually everytime.

**Comment by bigsee** [comment]
@mischah thank you from a random fellow traveller on the Internet! This problem has been bugging me for ages and yours was the solution! 🙏🏾
