### ISSUE TITLE
Unable to intsall yeoman OR yeoman installation failed.

### ISSUE THREAD

**Issue by hassanshuja** [yeoman/yo#494]
## Type of issue
I am unable to install yo from npm I have found these errors while running installation of yo, I have made all the paths for environment variables, but still getting error, i have also cleared the cache and re-install the nodejs , reboot my pc but still getting this error

Don't know

----

## My environment

* *OS version/details*: . Windows 10 64-bit`
* *Node version:* `v6.9.2` (run `node --version` in your terminal)
* *npm version:* `3.10.9` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal) Installation Failed ->below is the error detail

## Command line output

```
$ npm install --global yo npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm C:\Users\hp\AppData\Roaming\npm\yo -> C:\Users\hp\AppData\Roaming\npm\node_modules\yo\lib\cli.js C:\Users\hp\AppData\Roaming\npm\yo-complete -> C:\Users\hp\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js

spawn-sync@1.0.15 postinstall C:\Users\hp\AppData\Roaming\npm\node_modules\yo\node_modules\spawn-sync node postinstall
npm@1.0.0 C:\Users\hp\AppData\Roaming\npm `-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn-sync@1.0.15 (node_modules\yo\node_modules\spawn-sync): npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn-sync@1.0.15 postinstall: node postinstall npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status -4058 npm ERR! Windows_NT 10.0.14393 npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--global" "yo" npm ERR! node v6.9.2 npm ERR! npm v3.10.9 npm ERR! file ;C:\Program Files\Git\bin;C:\Program Files\Git\cmd npm ERR! path ;C:\Program Files\Git\bin;C:\Program Files\Git\cmd npm ERR! code ELIFECYCLE npm ERR! errno ENOENT npm ERR! syscall spawn ;C:\Program Files\Git\bin;C:\Program Files\Git\cmd

npm ERR! spawn-sync@1.0.15 postinstall: node postinstall npm ERR! spawn ;C:\Program Files\Git\bin;C:\Program Files\Git\cmd ENOENT npm ERR! npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'. npm ERR! Make sure you have the latest version of node.js and npm installed. npm ERR! If you do, this is most likely a problem with the spawn-sync package, npm ERR! not with npm itself. npm ERR! Tell the author that this fails on your system: npm ERR! node postinstall npm ERR! You can get information on how to open an issue for this project with: npm ERR! npm bugs spawn-sync npm ERR! Or if that isn't available, you can get their info via: npm ERR! npm owner ls spawn-sync npm ERR! There is likely additional logging output above. npm@1.0.0 C:\Users\hp\AppData\Roaming\npm `-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn-sync@1.0.15 (node_modules\yo\node_modules\spawn-sync): npm WARN optional SKIPPING OPTIONAL DEPENDENCY: spawn-sync@1.0.15 postinstall: node postinstall npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status -4058 npm ERR! Windows_NT 10.0.14393 npm ERR! argv "C:\Program Files (x86)\nodejs\node.exe" "C:\Program Files (x86)\nodejs\node_modules\npm\bin\npm-cli.js" "install" "--global" "yo" npm ERR! node v6.9.2 npm ERR! npm v3.10.9

npm ERR! Callback called more than once. npm ERR! npm ERR! If you need help, you may report this error at: npm ERR! https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request: npm ERR! C:\Users\hp\npm-debug.log npm ERR! code 1

Please tell me what is the problem with it.
```

**Comment by mischah** [comment]
Hej @hassanshuja,

the error log shows that there are problems with the postinstall script of the spawn-sync module.

You could try try to find a solution over here: https://github.com/ForbesLindesay/spawn-sync/issues/42

Cheers, Michael

**Comment by hassanshuja** [comment]
I have followed the suggestions from the link provided, and I also added the code into postinstall.js from this link https://github.com/ForbesLindesay/spawn-sync/blob/master/postinstall.js, and now postinstall error has gone  but it still gives me the error .Please see below

'CALL "C:\Program Files (x86)\node\\node.exe" "C:\Program Files (x86)\node\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\node\\node.exe" "C:\\Program Files (x86)\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "yo"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! path C:\Users\hp\AppData\Roaming\npm\node_modules\yo
npm ERR! code EISGIT

npm ERR! git C:\Users\hp\AppData\Roaming\npm\node_modules\yo: Appears to be a git repo or submodule.
npm ERR! git     C:\Users\hp\AppData\Roaming\npm\node_modules\yo
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\hp\npm-debug.log

**Comment by hassanshuja** [comment]
This is my error logs.Please check this for more info

[Err_logs.pdf](https://github.com/yeoman/yo/files/644371/Err_logs.pdf)

**Comment by hassanshuja** [comment]
Please also tell me why I am getting this error on executing npm

> **## 'CALL "C:\Program Files\node\\node.exe" "C:\Program Files\node\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
> operable program or batch file.**

C:\Users\hp\AppData\Roaming\npm>npm -v
'CALL "C:\Program Files\node\\node.exe" "C:\Program Files\node\\node_modules\npm\bin\npm-cli.js" prefix -g' is not recognized as an internal or external command,
operable program or batch file.
3.10.9

C:\Users\hp\AppData\Roaming\npm>node -v
v6.9.2

**Comment by mischah** [comment]
Your node/npm installation seems to be pretty messed up. 

Sorry, but this isn’t the place to get support for this kind of problems. 
I’d recommend using [Google](https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=npm-cli.js%22%20prefix%20-g%27%20is%20not%20recognized%20as%20an%20internal%20or%20external%20command%2C) instead.
