### ISSUE TITLE
Bug: Upstream bug in the `debug` module (debug.js:126)

### ISSUE THREAD

**Issue by vmadman** [yeoman/yo#495]
## Type of issue

Bug

## My environment

* *OS version/details*: `CentOS Linux release 7.1.1503 (Core)`
* *Node version:* `6.9.1`
* *npm version:* `3.10.8`
* *Version of yo :* `1.8.5`

The VM I am working on is new, Node.js and NPM were installed moments before installing `yo`.

**Note:** I am executing `yo` as `root`.  

## Expected behavior

Expected `yo` to output its current version.

## Current behavior

`yo` fails with an error.

### Install `yo` as usual:

```
$ npm install -g yo
```

### Run `yo` with `--version`:

```
$ yo --version

/usr/lib/node_modules/yo/node_modules/debug/debug.js:126
  debug.color = selectColor(namespae);
                            ^

ReferenceError: namespae is not defined
    at createDebug (/usr/lib/node_modules/yo/node_modules/debug/debug.js:126:29)
    at Object.<anonymous> (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:12:29)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/router.js:9:52)
```

## Additional Notes

The error is, apparently, a typo bug in the `debug` module, which is a dependency of `tabtab`.

I plan to open issues with those modules (if they do not yet exist), also, and will report links back here.

Given that this is clearly the result of a bug in `debug`, and not [necessarily] in `yo`, I apologize for not knowing the precise convention to follow in this case.  I am working on the assumption that `yo` would benefit from, at least, having an issue tracking the fix upstream.

I also thought it might be worth considering what `yo` should do in cases such as these, or what might be done to prevent this sort of thing from happening in the future.  `npm shrinkwrap` maybe?

## Command line output

The first error is detailed above, however, even after I manually corrected the typo in the `debug` module, additional errors occurred.  I am not sure if they are related, so, just in case, I am including them below.

**Immediately after correcting the typo ..**

```
$ yo -v

/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/root/.config'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at sync (/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:77:24)
    at Object.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:38:13)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:172:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**So, I tried creating the directory manually ...**

```
$ mkdir /root/.config
$ yo -v

/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/root/.config/configstore'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Function.sync (/usr/lib/node_modules/yo/node_modules/mkdirp/index.js:71:13)
    at Object.get (/usr/lib/node_modules/yo/node_modules/configstore/index.js:38:13)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:172:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**.. and, then, the sub-directory manually ..**
```
$ mkdir /root/.config/configstore
$ yo -v

/usr/lib/node_modules/yo/node_modules/configstore/index.js:69
                                throw err;
                                ^

Error: EACCES: permission denied, open '/root/.config/configstore/insight-yo.json.2577009884'
You don't have access to this file.

    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Function.writeFileSync [as sync] (/usr/lib/node_modules/yo/node_modules/write-file-atomic/index.js:78:8)
    at Object.set (/usr/lib/node_modules/yo/node_modules/configstore/index.js:62:21)
    at Object.Configstore (/usr/lib/node_modules/yo/node_modules/configstore/index.js:27:11)
    at new Insight (/usr/lib/node_modules/yo/node_modules/insight/lib/index.js:37:34)
    at Object.<anonymous> (/usr/lib/node_modules/yo/lib/cli.js:172:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**... and then I gave up.**

Again, I am not sure if the problems I am experiencing with these errors is in any way related and I will search for issues that may relate to that immediately following this post.  I just wanted to report them just in case it is related.

**Comment by mischah** [comment]
Thanks. Wish all people would report issues like you do 💖

**Comment by vmadman** [comment]
So, I checked upstream ..

First, its worth noting.. my `yo` install pulled `tabtab@1.3.2` and `debug@2.4.0`.

`tabtab` has released several versions since `1.3.2`.  They've actually bumped their major version and are currently on `2.2.1`. However, they still specify `^2.2.0` of `debug` in their latest version, just as they did back in `1.3.2`.

`debug` has recognized the typo, (here: https://github.com/visionmedia/debug/commit/94d78b5b80fb1282dcf97b739cd58402dbeeec14) and bumped their version to `2.4.1` (here: https://github.com/visionmedia/debug/commit/803fb05785675e262feb37546858c411b56dc35a).

They only bumped to `2.4.1` a few hours ago, so, I guess I should try to reinstall :)

**Comment by vmadman** [comment]
@mischah it is my pleasure, and the least I could do.  Besides, I just filled in the template that GitHub gave me :)

**Comment by vmadman** [comment]
Ok, well, maybe I just wasted some of your time.  The problem has been resolved upstream.  After reinstalling ...

```
$ cd /usr/lib/node_modules/yo
$ npm ls

...
├─┬ tabtab@1.3.2
│ ├─┬ debug@2.4.1
│ │ └── ms@0.7.2
...
```

.. after installation the typo has vanished.  I am still getting the `EACCESS` errors (shown above) but not the original issue.

I will find (or create) a different issue thread for the other problems and will self-close this one.

Thanks,

**Comment by vmadman** [comment]
Just for completeness, here .. I figured out the `EACCESS` error ... 

Turns out, I was mistakenly typing `yo -v` instead of `yo --version` in my subsequent tests.

`yo -v` does, in fact, yield errors.  However, `yo --version` works as expected ...

```
$ yo --version
1.8.5
```

**Comment by SBoudrias** [comment]
@vmadman `yo -v` probably just tried to run usual yo. The permission issue you have is a `chmod` problem.

Given the home directory in your example is `root`, my guess is you're running as an implicit sudo user. This is pretty dangerous in term of security, and you should run as a normal user.

**Comment by vmadman** [comment]
@SBoudrias The question about running things like `yo`, `npm`, and `bower` as `root` is one I've contemplated quite a lot, and, I've not arrived at any strong opinions.  I certainly understand that you should avoid running _anything_ as `root` on Linux.  I also understand that practically 100% of the security-aware Linux admins agree on that point.. and that I am, myself, _not_ a security or Linux expert.

So, what I say next is not meant to be argumentative or combative, and I am really interested in receiving additional insight and information, if you care to provide it...

However, things like SELinux and running applications as non-root users adds a definite layer of complexity on top of every operation that can impede upon people who are trying to operate efficiently and get things done quickly.  So, personally, when operating in certain environments, I tend to skip those concerns outright.

In this, particular, case, I am doing my work within a Vagrant box that is temporary, completely inaccessible from the outside world, hosted on my PC, and for my own, exclusive, use.

In other cases, such as with CI, things are run inside of containers or in other transient environments and, usually, those environments have zero overlap with any critical networks or systems.

In those cases, should I still concern myself with the `root` user question, or other security mechanisms such as SELinux?

Thank you for your time, I appreciate any advice that you give.

**Comment by SBoudrias** [comment]
@vmadman you still want to prevent malicious code from injecting anything in your system. Might it be spyware or any other kind of malicious program. With open registry like npm and the others, it's trivial for people to publish malicious modules executing code on the receiving machine. For example, npm modules build steps will run any code as your current user on install. This code if allowed can do literally anything to your machine.

Why would you care?

- What if your company secrets are leaked? SSH keys, networks topology, or even just company secrets like application source code or specific algorithms.
- What if malicious code inject code tracking your application activity? Like transactions, db writes, visits, etc

There's no safe sandbox environment where you never have to care about security.

**Comment by SBoudrias** [comment]
But the main reason to NOT use sudo might just be to stop having weird permissions bugs all the time.
