### ISSUE TITLE
No directives found under views folder after yo grunt server dist

### ISSUE THREAD

**Issue by abhijits2016** [yeoman/yo#499]
----

## My environment

* *OS version/details*: `eg. Windows 7 64-bit`
* *Node version:* `v6.9.2` (run `node --version` in your terminal)
* *npm version:* `4.0.5` (run `npm --version` in your terminal)
* *Version of yo :* `1.8.5` (run `yo --version` in your terminal)

## Expected behavior

generated dist files with templates and js ready for production

## Current behavior

using yeoman in my project and uses directives as header footer. But after grunt serve:build

Running "ngtemplates:dist" successfully but on dist folder under the views no directives are generated and I get 404 error on my directives calls on homepage. 

my gruntfile.js is as follows

> // Generated on 2016-12-27 using generator-angular 0.15.1
> 'use strict';
> 
> // # Globbing
> // for performance reasons we're only matching one level down:
> // 'test/spec/{,*/}*.js'
> // use this if you want to recursively match all subfolders:
> // 'test/spec/**/*.js'
> 
> module.exports = function (grunt) {
> 
>   // Time how long tasks take. Can help when optimizing build times
>   require('time-grunt')(grunt);
> 
>   // Automatically load required Grunt tasks
>   require('jit-grunt')(grunt, {
>     useminPrepare: 'grunt-usemin',
>     ngtemplates: 'grunt-angular-templates',
>     cdnify: 'grunt-google-cdn'
>   });
> 
>   // Configurable paths for the application
>   var appConfig = {
>     app: require('./bower.json').appPath || 'app',
>     dist: 'dist'
>   };
> 
>   // Define the configuration for all the tasks
>   grunt.initConfig({
> 
>     // Project settings
>     yeoman: appConfig,
> 
>     // Watches files for changes and runs tasks based on the changed files
>     watch: {
>       bower: {
>         files: ['bower.json'],
>         tasks: ['wiredep']
>       },
>       js: {
>         files: ['<%= yeoman.app %>/scripts/{,*/}*.js'],
>         tasks: ['newer:jshint:all', 'newer:jscs:all'],
>         options: {
>           livereload: '<%= connect.options.livereload %>'
>         }
>       },
>       jsTest: {
>         files: ['test/spec/{,*/}*.js'],
>         tasks: ['newer:jshint:test', 'newer:jscs:test', 'karma']
>       },
>       styles: {
>         files: ['<%= yeoman.app %>/styles/{,*/}*.css'],
>         tasks: ['newer:copy:styles', 'postcss']
>       },
>       gruntfile: {
>         files: ['Gruntfile.js']
>       },
>       livereload: {
>         options: {
>           livereload: '<%= connect.options.livereload %>'
>         },
>         files: [
>           '<%= yeoman.app %>/{,*/}*.html',
>           '.tmp/styles/{,*/}*.css',
>           '<%= yeoman.app %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
>           '<%= yeoman.app %>/resources/{,*/}*.json'
>         ]
>       }
>     },
> 
>     // The actual grunt server settings
>     connect: {
>       options: {
>         port: 9000,
>         // Change this to '0.0.0.0' to access the server from outside.
>         hostname: 'localhost',
>         livereload: 35729
>       },
>       livereload: {
>         options: {
>           open: true,
>           middleware: function (connect) {
>             return [
>               connect.static('.tmp'),
>               connect().use(
>                 '/bower_components',
>                 connect.static('./bower_components')
>               ),
>               connect().use(
>                 '/app/styles',
>                 connect.static('./app/styles')
>               ),
>               connect.static(appConfig.app)
>             ];
>           }
>         }
>       },
>       test: {
>         options: {
>           port: 9001,
>           middleware: function (connect) {
>             return [
>               connect.static('.tmp'),
>               connect.static('test'),
>               connect().use(
>                 '/bower_components',
>                 connect.static('./bower_components')
>               ),
>               connect.static(appConfig.app)
>             ];
>           }
>         }
>       },
>       dist: {
>         options: {
>           open: true,
>           base: '<%= yeoman.dist %>'
>         }
>       }
>     },
> 
>     // Make sure there are no obvious mistakes
>     jshint: {
>       options: {
>         jshintrc: '.jshintrc',
>         reporter: require('jshint-stylish')
>       },
>       all: {
>         src: [
>           'Gruntfile.js',
>           '<%= yeoman.app %>/scripts/{,*/}*.js'
>         ]
>       },
>       test: {
>         options: {
>           jshintrc: 'test/.jshintrc'
>         },
>         src: ['test/spec/{,*/}*.js']
>       }
>     },
> 
>     // Make sure code styles are up to par
>     jscs: {
>       options: {
>         config: '.jscsrc',
>         verbose: true
>       },
>       all: {
>         src: [
>           'Gruntfile.js',
>           '<%= yeoman.app %>/scripts/{,*/}*.js'
>         ]
>       },
>       test: {
>         src: ['test/spec/{,*/}*.js']
>       }
>     },
> 
>     // Empties folders to start fresh
>     clean: {
>       dist: {
>         files: [{
>           dot: true,
>           src: [
>             '.tmp',
>             '<%= yeoman.dist %>/{,*/}*',
>             '!<%= yeoman.dist %>/.git{,*/}*'
>           ]
>         }]
>       },
>       server: '.tmp'
>     },
> 
>     // Add vendor prefixed styles
>     postcss: {
>       options: {
>         processors: [
>           require('autoprefixer-core')({browsers: ['last 1 version']})
>         ]
>       },
>       server: {
>         options: {
>           map: true
>         },
>         files: [{
>           expand: true,
>           cwd: '.tmp/styles/',
>           src: '{,*/}*.css',
>           dest: '.tmp/styles/'
>         }]
>       },
>       dist: {
>         files: [{
>           expand: true,
>           cwd: '.tmp/styles/',
>           src: '{,*/}*.css',
>           dest: '.tmp/styles/'
>         }]
>       }
>     },
> 
>     // Automatically inject Bower components into the app
>     wiredep: {
>       app: {
>         src: ['<%= yeoman.app %>/index.html'],
>         ignorePath:  /\.\.\//
>       },
>       test: {
>         devDependencies: true,
>         src: '<%= karma.unit.configFile %>',
>         ignorePath:  /\.\.\//,
>         fileTypes:{
>           js: {
>             block: /(([\s\t]*)\/{2}\s*?bower:\s*?(\S*))(\n|\r|.)*?(\/{2}\s*endbower)/gi,
>               detect: {
>                 js: /'(.*\.js)'/gi
>               },
>               replace: {
>                 js: '\'{{filePath}}\','
>               }
>             }
>           }
>       }
>     }, 
> 
>     // Renames files for browser caching purposes
>     filerev: {
>       dist: {
>         src: [
>           '<%= yeoman.dist %>/scripts/{,*/}*.js',
>           '<%= yeoman.dist %>/styles/{,*/}*.css',
>           '<%= yeoman.dist %>/images/{,*/}*.{png,jpg,jpeg,gif,webp,svg}',
>           '<%= yeoman.dist %>/styles/fonts/*'
>         ]
>       }
>     },
> 
>     // Reads HTML for usemin blocks to enable smart builds that automatically
>     // concat, minify and revision files. Creates configurations in memory so
>     // additional tasks can operate on them
>     useminPrepare: {
>       html: '<%= yeoman.app %>/index.html',
>       options: {
>         dest: '<%= yeoman.dist %>',
>         flow: {
>           html: {
>             steps: {
>               js: ['concat', 'uglifyjs'],
>               css: ['cssmin']
>             },
>             post: {}
>           }
>         }
>       }
>     },
> 
>     // Performs rewrites based on filerev and the useminPrepare configuration
>     usemin: {
>       html: ['<%= yeoman.dist %>/{,*/}*.html'],
>       css: ['<%= yeoman.dist %>/styles/{,*/}*.css'],
>       js: ['<%= yeoman.dist %>/scripts/{,*/}*.js'],
>       options: {
>         assetsDirs: [
>           '<%= yeoman.dist %>',
>           '<%= yeoman.dist %>/images',
>           '<%= yeoman.dist %>/styles'
>         ],
>         patterns: {
>           js: [[/(images\/[^''""]*\.(png|jpg|jpeg|gif|webp|svg))/g, 'Replacing references to images']]
>         }
>       }
>     },
> 
>     // The following *-min tasks will produce minified files in the dist folder
>     // By default, your `index.html`'s  will take care of
>     // minification. These next options are pre-configured if you do not wish
>     // to use the Usemin blocks.
>     // cssmin: {
>     //   dist: {
>     //     files: {
>     //       '<%= yeoman.dist %>/styles/main.css': [
>     //         '.tmp/styles/{,*/}*.css'
>     //       ]
>     //     }
>     //   }
>     // },
>     // uglify: {
>     //   dist: {
>     //     files: {
>     //       '<%= yeoman.dist %>/scripts/scripts.js': [
>     //         '<%= yeoman.dist %>/scripts/scripts.js'
>     //       ]
>     //     }
>     //   }
>     // },
>     // concat: {
>     //   dist: {}
>     // },
> 
>     imagemin: {
>       dist: {
>         files: [{
>           expand: true,
>           cwd: '<%= yeoman.app %>/images',
>           src: '{,*/}*.{png,jpg,jpeg,gif}',
>           dest: '<%= yeoman.dist %>/images'
>         }]
>       }
>     },
> 
>     svgmin: {
>       dist: {
>         files: [{
>           expand: true,
>           cwd: '<%= yeoman.app %>/images',
>           src: '{,*/}*.svg',
>           dest: '<%= yeoman.dist %>/images'
>         }]
>       }
>     },
> 
>     htmlmin: {
>       dist: {
>         options: {
>           collapseWhitespace: true,
>           conservativeCollapse: true,
>           collapseBooleanAttributes: true,
>           removeCommentsFromCDATA: true
>         },
>         files: [{
>           expand: true,
>           cwd: '<%= yeoman.dist %>',
>           src: ['*.html'],
>           dest: '<%= yeoman.dist %>'
>         }]
>       }
>     },
> 
>     ngtemplates: {
>       dist: {
>         options: {
>           module: 'peyalaApp',
>           htmlmin: '<%= htmlmin.dist.options %>',
>           usemin: 'scripts/scripts.js'
>         },
>         cwd: '<%= yeoman.app %>',
>         src: 'views/{,*/}*.html',
>         dest: '.tmp/templateCache.js'
>       }
>     },
> 
>     // ng-annotate tries to make the code safe for minification automatically
>     // by using the Angular long form for dependency injection.
>     ngAnnotate: {
>       dist: {
>         files: [{
>           expand: true,
>           cwd: '.tmp/concat/scripts',
>           src: '*.js',
>           dest: '.tmp/concat/scripts'
>         }]
>       }
>     },
> 
>     // Replace Google CDN references
>     cdnify: {
>       dist: {
>         html: ['<%= yeoman.dist %>/*.html']
>       }
>     },
> 
>     // Copies remaining files to places other tasks can use
>     copy: {
>       dist: {
>         files: [{
>           expand: true,
>           dot: true,
>           cwd: '<%= yeoman.app %>',
>           dest: '<%= yeoman.dist %>',
>           src: [
>             '*.{ico,png,txt}',
>             '.htaccess',
>             '*.html',
>             'views/{,*/}*.html',
>             'images/{,*/}*.{webp}',
>             'styles/fonts/{,*/}*.*',
>             'fonts/{,*/}*.*',
>             'resources/{,*/}*.*'
>           ]
>         }, {
>           expand: true,
>           cwd: '.tmp/images',
>           dest: '<%= yeoman.dist %>/images',
>           src: ['generated/*']
>         }, {
>           expand: true,
>           cwd: '.',
>           src: 'bower_components/bootstrap-sass-official/assets/fonts/bootstrap/*',
>           dest: '<%= yeoman.dist %>'
>         }, {
>           expand: true,
>           cwd: 'bower_components/font-awesome/fonts/',
>           src: '**/*',
>           dest: '<%= yeoman.dist %>/fonts'
>         }, {
>           expand: true,
>           cwd: 'bower_components/angular-i18n/',
>           src: '*.js',
>           dest: '<%= yeoman.dist %>/bower_components/angular-i18n'
>         }]
>       },
>       styles: {
>         expand: true,
>         cwd: '<%= yeoman.app %>/styles',
>         dest: '.tmp/styles/',
>         src: '{,*/}*.css'
>       }
>     },
> 
>     // Run some tasks in parallel to speed up the build process
>     concurrent: {
>       server: [
>         'copy:styles'
>       ],
>       test: [
>         'copy:styles'
>       ],
>       dist: [
>         'copy:styles',
>         'imagemin',
>         'svgmin'
>       ]
>     },
> 
>     // Test settings
>     karma: {
>       unit: {
>         configFile: 'test/karma.conf.js',
>         singleRun: true
>       }
>     }
>   });
> 
> 
>   grunt.registerTask('serve', 'Compile then start a connect web server', function (target) {
>     if (target === 'dist') {
>       return grunt.task.run(['build', 'connect:dist:keepalive']);
>     }
> 
>     grunt.task.run([
>       'clean:server',
>       'wiredep',
>       'concurrent:server',
>       'postcss:server',
>       'connect:livereload',
>       'watch'
>     ]);
>   });
> 
>   grunt.registerTask('server', 'DEPRECATED TASK. Use the "serve" task instead', function (target) {
>     grunt.log.warn('The `server` task has been deprecated. Use `grunt serve` to start a server.');
>     grunt.task.run(['serve:' + target]);
>   });
> 
>   grunt.registerTask('test', [
>     'clean:server',
>     'wiredep',
>     'concurrent:test',
>     'postcss',
>     'connect:test',
>     'karma'
>   ]);
> 
>   grunt.registerTask('build', [
>     'clean:dist',
>     'wiredep',
>     'useminPrepare',
>     'concurrent:dist',
>     'postcss',
>     'ngtemplates',
>     'concat',
>     'ngAnnotate',
>     'copy:dist',
>     'cdnify',
>     'cssmin',
>     'uglify',
>     'filerev',
>     'usemin',
>     'htmlmin'
>   ]);
> 
>   grunt.registerTask('default', [
>     'newer:jshint',
>     'newer:jscs',
>     'test',
>     'build'
>   ]);
> };

## Command line output

```
Running "serve:dist" (serve) task

Running "clean:dist" (clean) task
>> 133 paths cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:test" (wiredep) task

Running "useminPrepare:html" (useminPrepare) task
Configuration changed for concat, uglify, cssmin

Running "concurrent:dist" (concurrent) task

Running "copy:styles" (copy) task
Copied 1 file

Done, without errors.


Execution Time (2017-01-05 11:41:06 UTC+5:30)
loading tasks               568ms  ███████████████████████████████ 89%
loading grunt-contrib-copy   35ms  ██ 5%
copy:styles                  35ms  ██ 5%
Total 639ms

Running "svgmin:dist" (svgmin) task
Total saved: 0 B

Done, without errors.


Execution Time (2017-01-05 11:41:06 UTC+5:30)
loading tasks         586ms  ██████████████ 35%
loading grunt-svgmin  609ms  ███████████████ 36%
svgmin:dist           492ms  ████████████ 29%
Total 1.7s

Running "imagemin:dist" (imagemin) task
Minified 89 images (saved 482.78 kB)

Done, without errors.


Execution Time (2017-01-05 11:41:06 UTC+5:30)
loading grunt-contrib-imagemin   3.3s  ██ 5%
imagemin:dist                   1m 4s  █████████████████████████████ 94%
Total 1m 7.9s

Running "postcss:server" (postcss) task
>> 1 processed stylesheet created.

Running "postcss:dist" (postcss) task
>> 1 processed stylesheet created.

Running "ngtemplates:dist" (ngtemplates) task
>> No templates found
File .tmp/templateCache.js created.
Added .tmp/templateCache.js to <!-- build:js scripts/scripts.js -->

Running "concat:generated" (concat) task
File .tmp\concat\scripts\vendor.js created.
File .tmp\concat\scripts\scripts.js created.

Running "ngAnnotate:dist" (ngAnnotate) task
>> 2 files successfully generated.

Running "copy:dist" (copy) task
Copied 1616 files

Running "cdnify:dist" (cdnify) task
Going through dist/404.html, dist/index.html to update script refs
? bower_components/angular/angular.js changed to //ajax.googleapis.com/ajax/libs
/angularjs/1.5.0-beta.1/angular.min.js
? bower_components/angular-animate/angular-animate.js changed to //ajax.googleap
is.com/ajax/libs/angularjs/1.5.0-beta.1/angular-animate.min.js
? bower_components/angular-cookies/angular-cookies.js changed to //ajax.googleap
is.com/ajax/libs/angularjs/1.5.0-beta.1/angular-cookies.min.js
? bower_components/angular-resource/angular-resource.js changed to //ajax.google
apis.com/ajax/libs/angularjs/1.5.0-beta.1/angular-resource.min.js
? bower_components/angular-route/angular-route.js changed to //ajax.googleapis.c
om/ajax/libs/angularjs/1.5.0-beta.1/angular-route.min.js
? bower_components/angular-sanitize/angular-sanitize.js changed to //ajax.google
apis.com/ajax/libs/angularjs/1.5.0-beta.1/angular-sanitize.min.js
? bower_components/angular-touch/angular-touch.js changed to //ajax.googleapis.c
om/ajax/libs/angularjs/1.5.0-beta.1/angular-touch.min.js
? bower_components/angular/angular.js changed to //ajax.googleapis.com/ajax/libs
/angularjs/1.5.0-beta.1/angular.min.js
? bower_components/angular-animate/angular-animate.js changed to //ajax.googleap
is.com/ajax/libs/angularjs/1.5.0-beta.1/angular-animate.min.js
? bower_components/angular-cookies/angular-cookies.js changed to //ajax.googleap
is.com/ajax/libs/angularjs/1.5.0-beta.1/angular-cookies.min.js
? bower_components/angular-resource/angular-resource.js changed to //ajax.google
apis.com/ajax/libs/angularjs/1.5.0-beta.1/angular-resource.min.js
? bower_components/angular-route/angular-route.js changed to //ajax.googleapis.c
om/ajax/libs/angularjs/1.5.0-beta.1/angular-route.min.js
? bower_components/angular-sanitize/angular-sanitize.js changed to //ajax.google
apis.com/ajax/libs/angularjs/1.5.0-beta.1/angular-sanitize.min.js
? bower_components/angular-touch/angular-touch.js changed to //ajax.googleapis.c
om/ajax/libs/angularjs/1.5.0-beta.1/angular-touch.min.js

Running "cssmin:generated" (cssmin) task
>> 2 files created. 146.01 kB → 116.84 kB

Running "uglify:generated" (uglify) task
>> 2 files created.

Running "filerev:dist" (filerev) task
Revved 93 files

Running "usemin:html" (usemin) task
Replaced 2 references to assets

Running "usemin:css" (usemin) task
Replaced 2 references to assets

Running "usemin:js" (usemin) task
Replaced 2 references to assets

Running "htmlmin:dist" (htmlmin) task
Minified 2 files

Running "connect:dist:keepalive" (connect) task
Waiting forever...
Started connect web server on http://localhost:9000


GET http://localhost:9000/templates/main/directives/headerDirective.html
	
404 Not Found

GET http://localhost:9000/templates/main/directives/footerDirective.html
	
404 Not Found

GET http://localhost:9000/templates/main/main.html
	
404 Not Found


```

**Comment by sindresorhus** [comment]
This should be opened on the generator you used.
