### ISSUE TITLE
>.net generator

### ISSUE THREAD

**Issue by warheadcoder** [yeoman/yo#510]
## Type of issue

Attempting to use yeoman in Visual Studio Code. I can create a .net web application successfully, but when trying to prompt "dotnet restore" or "dotnet build" it states that it is unable to find project.json and I am unable to view it. 

----

## My environment

* *OS version/details*: Windows 10 64-bit
* *Node version:* 6.9.4 
* *npm version:* 3.10.5
* *Version of yo :* 1.8.5

## Expected behavior

To host the project in port:5000 as usual and run it in the browser

## Current behavior

Unable to build and run it

## Steps to reproduce the behavior

After building a .net web application the steps are as follows:
dotnet restore
dotnet build
dotnet run

```
Paste your error output over here
The folder does not contain a project to restore.

The current project is not valid because of the following errors:
 Project file does not exist 'C:\...\project.json'.

**Comment by SBoudrias** [comment]
You should open this ticket on the generator you used.

`yo` (and the Yeoman project) is just a generator runner. People writing the actual generators are the one who can help you with bugs with the output setup.
