### ISSUE TITLE
this.log is not printing the object when supplied as second argument

### ISSUE THREAD

**Issue by amiteshhh** [yeoman/yo#511]
## Type of issue

Bug

----

## My environment

* Windows 10 64-bit
* *Node version:* `6.9.2`
* *npm version:* `3.10.9`
* *Version of yo :* `1.8.5`

## Expected behavior

Statement `this.log('Log Title', {'key':'value'});` should log the object in console window.

I spent whole day thinking `obj` in `this.log('Log Title', obj);`   is empty :(

## Current behavior

Its just printing the `first argument` supplied to _this.log_

Its working fine if the second argument is string or number.

## Command line output

```
Log Title
```

**Comment by SBoudrias** [comment]
`this.log` is a UI utility. If you need to debug your generator, then use `debugger` and `console.<x>`.

**Comment by amiteshhh** [comment]
Yes, but It should work consistently. I am under assumption that It is equivalent to `console.log` in window terminal environment. Moreover its working correctly when string is supplied as second argument.

**Comment by mischah** [comment]
@amiteshhh 
> I am under assumption that It is equivalent to console.log in window terminal environment.

You shouldn’t assume that without reading the source code 😜

@SBoudrias I don’t get it.

What is the use case for the second parameter context described here:
https://github.com/yeoman/environment/blob/master/lib/util/log.js#L57-L59

**Comment by SBoudrias** [comment]
@mischah it's old style template strings `this.log('hey %name', {name: 'Michael'})`.

These functions are very old, I didn't even knew it was supporting this option 😛

**Comment by mischah** [comment]
Ahh 💡  … thanks.

Going to close this.
