### ISSUE TITLE
Improve error message when you do `yo generator-foo`

### ISSUE THREAD

**Issue by joshkpeterson** [yeoman/yo#512]
I'm new to yeoman and missed that you use the generator- prefix when installed the package from npm, but NOT when you run the generator. Try to run `yo generator-foo` and you get the standard error message when the generator is not installed:

`You don’t seem to have a generator with the name “generator-gulp-sass-livereload” installed.`

But it seems like there could be some simple check to see if you're trying to run something that begins with 'generator-' and if so, be like "Hey just run `yo foo`"

Seems dumb, but I just spent some time on a red herring - thought it was something to do with nvm or my node path something more nefarious.

**Comment by sindresorhus** [comment]
Agreed. Or even better, show the helpful message about it being incorrect, and then run `foo`.

**Comment by toubou91** [comment]
I believe #520 also solves this issue.
I suggest closing it.

**Comment by mischah** [comment]
Jup. Thanks for pointing out.
