### ISSUE TITLE
npm WARN deprecated npmconf@2.1.2

### ISSUE THREAD

**Issue by ivostoykov** [yeoman/yo#513]
## Type of issue

----

## My environment

* *OS version/details*: Windows 10 64-bit
* *Node version:* 7.7.2
* *npm version:* 4.4.1
* *Version of yo :* 1.8.5

## Expected behavior

clean installation

## Current behavior

installed with WARN

## Steps to reproduce the behavior

npm install -g yo (with admin rights after node & npm fresh install)

## Command line output

```
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
```

**Comment by mischah** [comment]
Thanks for creating the issue.

There is nothing we can change about this since `npmconf` is a subdependency deep down in our dependency tree.

But, you don’t have to worry. Its just a warning and won’t break anything.
Most people (including me) don’t even care about npm warnings during installation of packages ☺️

**Comment by peterblazejewicz** [comment]
The dependant module has been rewritten to not use `npmconf` months ago:
https://github.com/sindresorhus/fullname/commit/53420ef8e5ab91585f94a5afbf02b21c6511f5f2

**Comment by SBoudrias** [comment]
Yes, we did not update at the time because with this rewrite, the module dropped Node < 4 support - which was not an option for Yeoman at the time.

**Comment by peterblazejewicz** [comment]
@SBoudrias Thanks! 
I assume that's OK to make PR now after Yo was ES2015-ied:
https://github.com/yeoman/yo/blob/master/package.json#L15

**Comment by peterblazejewicz** [comment]
@ivostoykov 
It appears the `Yo` already contains a version of `fullname` module that dos not show that warning when installed - but the version containing updated dependency is not yet released:
https://github.com/sindresorhus/fullname/commit/53420ef8e5ab91585f94a5afbf02b21c6511f5f2
https://github.com/yeoman/yo/blob/master/package.json#L50
Thanks!
