### ISSUE TITLE
Gettting error on yo fountain-webapp

### ISSUE THREAD

**Issue by hemachandrav** [yeoman/yo#514]
## Type of issue
Not able to setup project using yeoman. getting following error whey i try to install fountain-webapp.
Yo version is 1.8.5

C:\Hema\Philips\H2H\project>yo fountain-webapp
C:\Users\310242265\AppData\Roaming\npm\node_modules\generator-fountain-webapp\node_modules\fountain-generator\lib\Base.js:21
    const {framework, modules, js} = this.options;
          ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\310242265\AppData\Roaming\npm\node_modules\generator-fountain-webapp\node_modules\fountain-generator\index.js:2:9)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

----

## My environment

* *OS version/details*: `eg. Windows 7 64-bit`
* *Node version:* `4.4.4` (run `node --version` in your terminal)
* *npm version:* `4.4.1` (run `npm --version` in your terminal)
* *Version of yo :* `1.8.5` (run `yo --version` in your terminal)

## Command line output

```
Paste your error output over here
```

**Comment by SBoudrias** [comment]
You need to use a recent version of Node.js (>= 4)

**Comment by betweenbrain** [comment]
@SBoudrias http://yeoman.io/codelab/setup.html states that you need Node.js v4 or higher, as you do as well, but @hemachandrav is using 4.4.4 and I am experiencing this issue with 4.4.1. Should it be >= v5, or is there a bug here?

**Comment by betweenbrain** [comment]
Okay, according to #516, the version of Node needs to be 6 or higher.

**Comment by SBoudrias** [comment]
@zckrs Hey, any chance you're requiring Node 6? If so, I really think generator-fountain-webapp should hold a bit on es6 features and keep support for v4 given it's still widely used.

@betweenbrain I'd suggest opening an issue on the `generator-fountain-webapp` repository.

**Comment by bArraxas** [comment]
Nodejs : v6.11, v7.7
NPM : v5
Nothing works, error :
"events.js:160 -> throw er; // Unhandled 'error' event
