### ISSUE TITLE
tutorial crashes

### ISSUE THREAD

**Issue by focussing** [yeoman/yo#516]
During tutorial http://yeoman.io/codelab/setup.html in Step 3 there are error messages; preventing to proceed.

## My environment

* *OS version/details*: Mac OS Sierra 10.12.4
* *Node version:* 4.6.2
* *npm version:* 4.4.4
* *Version of yo :* 1.8.5

## Expected behavior

Tutorial does not work as described... se below

## Command line output

iMac:mytodo raymond$ npm install generator-fountain-webapp
\

spawn-sync@1.0.15 postinstall /Users/raymond/node_modules/generator-fountain-webapp/node_modules/fountain-generator/node_modules/yeoman-generator/node_modules/yeoman-environment/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
node postinstall
npm WARN unmet dependency /Users/raymond/node_modules/angular-ui-grid requires angular@'>=1.2.16 1.4.x' but will load
npm WARN unmet dependency /Users/raymond/node_modules/angular,
npm WARN unmet dependency which is version 1.6.1
generator-fountain-webapp@1.0.0 ../../../node_modules/generator-fountain-webapp
├── chalk@1.1.3 (escape-string-regexp@1.0.5, supports-color@2.0.0, ansi-styles@2.2.1, strip-ansi@3.0.1, has-ansi@2.0.0)
├── yosay@2.0.0 (strip-ansi@3.0.1, ansi-regex@2.1.1, cli-boxes@1.0.0, pad-component@0.0.1, string-width@2.0.0, taketalk@1.0.0, ansi-styles@3.0.0, wrap-ansi@2.1.0)
├── fountain-generator@1.0.0 (minimatch@3.0.3, falafel@2.1.0, ejs@2.5.6, mem-fs-editor@3.0.2, mem-fs@1.1.3, yeoman-generator@1.1.1, lodash@4.17.4)
├── generator-fountain-vue@1.0.0 (generator-fountain-gulp@1.0.0)
├── generator-fountain-angular2@1.0.0 (generator-fountain-gulp@1.0.0)
├── generator-fountain-react@1.0.0 (generator-fountain-gulp@1.0.0)
└── generator-fountain-angular1@1.0.0 (generator-fountain-gulp@1.0.0)
iMac:mytodo raymond$ yo fountain-webapp
/Users/raymond/node_modules/generator-fountain-webapp/node_modules/fountain-generator/lib/Base.js:21
const {framework, modules, js} = this.options;
^

SyntaxError: Unexpected token {
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object. (/Users/raymond/node_modules/generator-fountain-webapp/node_modules/fountain-generator/index.js:2:9)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
iMac:mytodo raymond$

**Comment by mischah** [comment]
The generator you are using [requires Node version 6](https://github.com/FountainJS/generator-fountain-webapp#requirement-node-6--npm-3) (or above).

**Comment by focussing** [comment]
So sorry! http://yeoman.io/codelab/setup.html states:

Install prerequisites

Before installing Yeoman, you will need the following:

Node.js v4 or higher
npm (which comes bundled with Node)
git

**Comment by mischah** [comment]
No Problem. 

@zckrs Guess that needs to be changed:

> Install prerequisites
> 
> Before installing Yeoman, you will need the following:
> 
> Node.js v4 or higher


Right?

**Comment by betweenbrain** [comment]
Pull request to address this issue has been created at https://github.com/yeoman/yeoman.github.io/pull/723

**Comment by bArraxas** [comment]
Nodejs : v6.11, v7.7
NPM : v5
Nothing works, error :
"events.js:160 -> throw er; // Unhandled 'error' event
