### ISSUE TITLE
yo code doesn't work in gitbash for windows

### ISSUE THREAD

**Issue by Radi123** [yeoman/yo#517]
Hello,
I use all commands (npm, git, yarn, and more) in Git Bash for windows...
I try to use ```yo code``` in Git Bash, but it doesn't work...
https://code.visualstudio.com/docs/extensions/yocode
![image](https://cloud.githubusercontent.com/assets/12954909/25073532/66efb84e-22f1-11e7-8af8-d86e89afab7a.png)
Here i can't switch the type of extension with arrows.

After that I try ```yo code``` in windows ```cmd```. It works... But I don't want to switch between ```cmd``` and **Git Bash**, when I work in one project.
> I think this issue is for label: bug

Please solve this. Thanks

**Comment by SBoudrias** [comment]
git bash is not a TTY terminal. It doesn't have interactive features - as such, the yo UI cannot support it.

You can use cmd, powershell or any other windows TTY terminal.

**Comment by wenfangdu** [comment]
Run `winpty yo.cmd code`
