### ISSUE TITLE
npm ERR! 404 no such package available : execall

### ISSUE THREAD

**Issue by jasonwong1991** [yeoman/yo#519]
## Type of issue
I want to install yeoman, but it is not work. I changed nodejs version but it's still not work!!

----

## My environment

* *OS version/details*: `10.12.4 `
* *Node version:* `v6.10.2` (run `node --version` in your terminal)
* *npm version:* `3.10.10` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Command line output
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yo"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code E404

npm ERR! 404 no such package available : execall
npm ERR! 404
npm ERR! 404  'execall' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'parse-help'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Jason/npm-debug.log
```
Paste your error output over here
```
![image](https://cloud.githubusercontent.com/assets/8357581/25614261/d3f21594-2f63-11e7-8f41-1a3d9efad3fc.png)

**Comment by sindresorhus** [comment]
Install issues should be reported on the npm issue tracker: https://github.com/npm/npm/issues
