### ISSUE TITLE
GIFs Consistently Produce EJS Compile Errors

### ISSUE THREAD

**Issue by mattc41190** [yeoman/yo#521]
## Bug

----

## My environment

* Mac OSX 
* 6.9.5
* 3.10.8
* 1.8.5

## Expected behavior

A user can scaffold a project containing GIF files.

## Current behavior

A user can NOT scaffold a project containing GIF files.

## Steps to reproduce the behavior

Create a templates dir with a /public/anyName.gif

## Command line output

```
Error: Could not find matching close tag for "<%".
    at /Users/myStuff/generator-magic/node_modules/ejs/lib/ejs.js:595:19
```

**Comment by SBoudrias** [comment]
Use `this.fs.copy()` instead of `this.fs.copyTpl()` to binary files.

**Comment by mischah** [comment]
Closing this. Fell free to open another issue when the hint from Simon didn’t help.

**Comment by mattc41190** [comment]
:1st_place_medal:

**Comment by mattc41190** [comment]
That fix was a winner! Sorry for not saying anything earlier!
