### ISSUE TITLE
Bug with Node.js 8.1.0 on Linux 

### ISSUE THREAD

**Issue by JulioJu** [yeoman/yo#522]
## Type of issue

On Linux , with NodeJS 8.1.0, it's impossible to use arrow keys when we generate a new project with command `yo jhipster`.

I've tried with zsh, sh, bash, and with Gnome-Terminal, XTerm, tty, and with Yeoman 1.8.5 or 2.0.0 and with Jhipster 4.3.0, 4.5.2 and 4.5.3.

If we kill yeoman (`pkill yo`), after having use this command, in the same shell there are many other issues with other commands like `sudo` (can't enter passwords).

With Node.js 8.1.0, there is no problems with command `yo jhipster entity myentityname`.

With Node.js 7.9.0 or Node.js 6.11.0, there isn't any problem. All work fine.

## My environment

* *OS version/details*: `Linux`
* *Node version:* `8.1.0`
* *npm version:* `4.6.1` 
* *Version of yo :* `2.0.0` or `1.8.5`

## Steps to reproduce the behavior

* Install Linux and Node.js 8.1.0, and jhipster.
* In a new folder, type `yo jhipster`
* Try to use arrow keys. Doesn't work.
* In an other terminal, kill yeoman (`pkill yo`)
* In the first terminal, try to run `sudo`: it's not possible to enter password.
* Try other commands with inputs, like ([Y/n]. Doesn't work too.

## See also
I have post an issue on https://github.com/jhipster/generator-jhipster/issues/5905#issuecomment-307569911. The JHipster's leader asked me to post an issue here.

**Comment by SBoudrias** [comment]
Bug on the Node repo: https://github.com/nodejs/node/issues/13557

A fix has been merge, it should be fix with the next release.

**Comment by JulioJu** [comment]
Ok !
