### ISSUE TITLE
Installation warns of potential problems with my machine

### ISSUE THREAD

**Issue by ricardo-1937** [yeoman/yo#523]
the yo command produces this output:
C:\Users\Caribbean1\AppData\Roaming\npm\node_modules\yo\lib\cli.js:3
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

C:\
λ yo --version
C:\Users\Caribbean1\AppData\Roaming\npm\node_modules\yo\lib\cli.js:3
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

C:\
## Type of issue

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Command line output

```
Paste your error output over here
```

**Comment by SBoudrias** [comment]
Please answer the question in the issue templates. In this case it just looks like your Node version is too old. Please update to a maintained version.

**Comment by ricardo-1937** [comment]
Simon,


Closing a case at 2:52 AM without a chance to reply is illogical, of course ,I have the latest versions of npm and node.

Would you like some proof?


Ricardo Sanchez
(561) 372-9299


________________________________

**Comment by kevva** [comment]
> `SyntaxError: Use of const in strict mode.`

This leads me to believe that you don't have the latest `node` version.

**Comment by ricardo-1937** [comment]
Kevin,


This error message was received prior to upgrading my versions (see attached), however, after uninstalling yeoman , upgrading the versions and reinstalling yeoman, I still

get an error from yeoman telling me that my versions are old, I wrote other ticket , but it was closed today at 2:52 AM ( I am in Florida) without any resolution or discussion

assuming that I did have old versions, you can tell by the attached that I do have the latest.

I do really want to join your user group and want to learn and use yeoman in my web sites.


Ricardo Sanchez
(561) 372-9299


________________________________

**Comment by ricardo-1937** [comment]
Kevin,


Here is a picture of the errors, Yeoman does not run after reinstalling it and cleaning the cache.

What should I do to fix it?


Ricardo Sanchez
(561) 372-9299


________________________________

**Comment by SBoudrias** [comment]
The error isn't displaying here. Mind re-attaching it?
