### ISSUE TITLE
The Yo installed in Visual Studio Code For Mac , It can not work correctly.

### ISSUE THREAD

**Issue by HuangYanQi** [yeoman/yo#530]
I enter 'yo' in command line has nothing be actived

**Comment by SBoudrias** [comment]
Are the npm package binaries in your system PATH variable?

**Comment by HuangYanQi** [comment]
I can use yo command in mac terminal.But I can't use it in Visual Studio Code For Mac.For details, please see attached.Please help me check problems in VS Code Extentions ,because i in great need of Yo to program Asp.net in my Mac.Thanks!
<img width="591" alt="qq20170728-154639 2x" src="https://user-images.githubusercontent.com/18044251/28707819-638e9344-73ac-11e7-92e8-b517338ed31d.png">
<img width="618" alt="qq20170728-154710 2x" src="https://user-images.githubusercontent.com/18044251/28707820-63dc9a58-73ac-11e7-9881-518cd60468b2.png">

**Comment by SBoudrias** [comment]
You should ask for support on one of the VS support channels. We're unfortunately not handling how VS code works; so we won't be able to point you in the right direction.
