### ISSUE TITLE
Error Installing Yo in Ubuntu 17 with Node v8.2.1 and NPM v5.3.0

### ISSUE THREAD

**Issue by borgymanotoy** [yeoman/yo#531]
## Type of issue

Yo Installation error

----

## My environment

Ubuntu 17.04
NodeJS 8.2.1
NPM 5.3.0
Yo (Cannot be installed)

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Expected behavior

I should be able to call npm package binaries like yodoctor, I am guessing that once yodoctor command works.... the installation would push thru.

## Current behavior

Unable to install yo package, getting error yodoctor not found.
Seems that all package binaries are not found by ubuntu.
I am unable to locate the directory for all npm package binaries.

## Steps to reproduce the behavior
1. Fresh Install of NodeJS (NPM) for Ubuntu using PPA

cd ~
curl -sL https://deb.nodesource.com/setup_8.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt-get install nodejs

2. Install Yeoman-Doctor

npm i -g yeoman-doctor (Successful)

3. Call yeoman-doctor or yodoctor

Tried using the following commands 
yodoctor
sudo youdoctor
yeoman-doctor
sudo yeoman-doctor

* All returns 'command not found'

5. Install Yo

npm i -g yo (ERROR)

## Command line output
borgymanotoy@azeus:~$ npm doctor
Check                               Value                        Recommendation
npm ping                            OK
npm -v                              v5.3.0
node -v                             v8.2.1
npm config get registry             https://registry.npmjs.org/
which git                           /usr/bin/git
Perms check on cached files         ok
Perms check on global node_modules  ok
Perms check on local node_modules   ok
Verify cache contents               verified 2 tarballs

borgymanotoy@azeus:~/temp$ npm i -g yeoman-doctor
+ yeoman-doctor@2.1.0
updated 68 packages in 8.668s

borgymanotoy@azeus:~/temp$ yo
yo: command not found

borgymanotoy@azeus:~/temp$ yodoctor
yodoctor: command not found

borgymanotoy@azeus:~/temp$ sudo yodoctor
sudo: yodoctor: command not found

borgymanotoy@azeus:~/temp$ npm i -g yo

> spawn-sync@1.0.15 postinstall /home/borgymanotoy/.npm/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall

> yo@2.0.0 postinstall /home/borgymanotoy/.npm/lib/node_modules/yo
> yodoctor

sh: 1: yodoctor: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! yo@2.0.0 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the yo@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/borgymanotoy/.npm/_logs/2017-07-28T07_14_45_989Z-debug.log

```
Paste your error output over here
```
sh: 1: yodoctor: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! yo@2.0.0 postinstall: `yodoctor`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the yo@2.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/borgymanotoy/.npm/_logs/2017-07-28T07_14_45_989Z-debug.log

**Comment by SBoudrias** [comment]
Please take the time to search for your issue before opening new bug reports. This question has been asked countless times: https://github.com/yeoman/yo/search?q=yodoctor%3A+not+found&type=Issues&utf8=%E2%9C%93
