### ISSUE TITLE
I have yo downloaded successfully but can not find command yo

### ISSUE THREAD

**Issue by bayon** [yeoman/yo#535]
## Type of issue

----

## My environment
mac bought in late 2011
* *OS macOS Sierra/10.12.5*: `eg. Windows 10 64-bit`
* *Node version:* `8.2.1` (run `node --version` in your terminal)
* *npm version:* `5.3.0` (run `npm --version` in your terminal)
* *Version of yo :* `2.0.0` (run `yo --version` in your terminal)
** GIT 2.11.0 ( Apple Git-81)

## Expected behavior
I expect that since I have all the prerequisites I can just install it , check the version....
and get on with some stuff I'm trying to work on.

Instead my machine will not find the yo command....
I believe my PATH is set up correctly ....it 'should be'  for node, npm, and git if it's finding the versions right?
I've heard of people having to uninstall node and npm and reinstall them.?
/usr/local/bin  is in my path and is where node, npm , and yo are located at...
Please help if you can.
Thanks,
Bayon

## Current behavior
AFTER seeing this upon installing yeoman:::
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
+ yo@2.0.0

I try to check the version:::
my-MacBook-Pro:/ <MyName> $ yo --version
-bash: yo: command not found

## Command line output

```
Paste your error output over here
```

**Comment by SBoudrias** [comment]
The only issue that can cause `yo: command not found` are PATH issues.

I'd say go at it step by step:

1. Find where yo is installed
2. Run it with the path you found (e.g. type `/usr/bin/yo` in your terminal - path may be different)
3. Make sure that folder is in your PATH (`echo $PATH`)

**Comment by bayon** [comment]
Thanks Simon.-Bayon
