### ISSUE TITLE
yo does not find angular-2-crud generator 

### ISSUE THREAD

**Issue by gorums** [yeoman/yo#537]
## Type of issue

**yo** does not find my generator

The generator is public and you have it in your repository with the name "angular-2-crud", but when I run 

`#yo angular-2-crud`

```
You don't seem to have a generator with the name angular-2-crud installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-angular-2-crud.
```

If I run `#yo doctor`

```gorums@gorums-dev:~/Work/gorums/generator-angular-2-crud(master)$ yo doctor

Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
```
If I run `#yo` and try to find the generator

```yo
? 'Allo gorums! What would you like to do? Install a generator
? Search npm for generators: angular-2-crud
? Here's what I found. Official generator → ෴
  Install one? 
❯ angular-2-crud This app generate a CRUD for Angular2  
  Search again 
  Return home 
```
but still the same error after the install above

## My environment

* *OS version/details*: `Ubuntu 17.04`
* *Node version:* `8.0.0` (run `node --version` in your terminal)
* *npm version:* `5.4.2` (run `npm --version` in your terminal)
* *Version of yo :* `2.0.0` (run `yo --version` in your terminal)

## Steps to reproduce the behavior

here the steps [Github project](https://github.com/gorums/generator-angular-2-crud/blob/master/README.md)

```
You don't seem to have a generator with the name “angular-2-crud” installed.
But help is on the way:

You can see available generators via npm search yeoman-generator or via http://yeoman.io/generators/. 
Install them with npm install generator-angular-2-cru
```

**Comment by SBoudrias** [comment]
Did you `npm install -g  generator-angular-2-crud` first?

**Comment by gorums** [comment]
Yes I did

**Comment by mischah** [comment]
Seems that that was was caused by updating to `"yeoman-generator": "^2.0.0"` without adapting the breaking changes.

**Comment by gorums** [comment]
Any link to know about "the breaking changes"?

**Comment by SBoudrias** [comment]
@gorums https://github.com/yeoman/generator/releases/tag/v2.0.0

This generator can just downgrade the version if they don't plan to adjust for the new API. It'll continue to work as is.
