### ISSUE TITLE
yeoman dont run when I install 'yo' with NPM

### ISSUE THREAD

**Issue by serazul** [yeoman/yo#539]
## Command line output

yo : The term 'yo' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ yo @microsoft/sharepoint
+ ~~
    + CategoryInfo          : ObjectNotFound: (yo:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by SBoudrias** [comment]
Did you add your npm installed binaries inside your system PATH variable?

**Comment by serazul** [comment]
i solved that , install yo with yarn
