### ISSUE TITLE
cannot install @microsoft/generator-sharepoint

### ISSUE THREAD

**Issue by sandhya943** [yeoman/yo#541]
I am not able to install sharepoint generator .
It gives an error saying "unrecognised token in source text"
I am not able find this generator in the search as well.

**Comment by mischah** [comment]
Sorry, this is not related to Yo.

I had no problems installing the generator with:

```
npm install @microsoft/generator-sharepoint -g
```

as described over [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator). 

I couldn’t find the generator at the [sharepoint GitHub organisation](https://github.com/SharePoint) 😞 

So I recommend filing an issue over [here](https://github.com/SharePoint/sp-dev-docs) or leaving a comment over [here](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator).

Cheers, Michael
