### ISSUE TITLE
Problems when using registerTransformStream()

### ISSUE THREAD

**Issue by sanserna** [yeoman/yo#550]
## Type of issue

bug

----

## My environment

* *OS version/details*: `macOS Sierra 10.12.6`
* *Node version:* `6.11.3`
* *npm version:* `3.10.10`
* *Version of yo :* `2.0.0`

## Expected behavior

I'm facing proeblems when trying to use `registerTransformStream()`, I would like to have an especific bunch of files to be passed through a `stream`, for example I would like to have all my `.css` files passed through `gulp-sass` and then `gulp-cssnano` and on the other hand take all my `.js` files and pass them through `gulp-uglify`, so how can I achive this beahvior?, I already read the documentation but did not understand quite well how to use it.

## Current behavior

All my files are going through all the registered transformStreams.

**Comment by mischah** [comment]
I’m not sure what you trying to achieve with these Gulp plugin in your generator.
But  you can use gulp add-ons like described [here](http://yeoman.io/authoring/file-system.html) to filter your files.

**Comment by sanserna** [comment]
The idea behind this is to be able to customize the scaffold and the tools that the user need, for example like boostrap does on it download page, so the process that I have in mind is to promp the user to select what tools and modules he need and put them all together in a final `bundle.min.js` file when the project is generated, also with `.css` files. So I need to pre-process the files with a `gulp-module` or something similar.

**Comment by mischah** [comment]
That

**Comment by Spown** [comment]
>I’m not sure what you trying to achieve with these Gulp plugins in your generator.
But you can use gulp add-ons like described here to filter your files.

>Tools like gulp-if or gulp-filter will help filter invalid types and pass them through.

^ How is this "described" exactly? I know these tools can help, duh. How about showing how to integrate them with your system? I've tried 

```js
this.registerTransformStream(
    filter(['**/*.js', '**/*.json'])
    .pipe( beautify({
        indentSize: 4,
        max_preserve_newlines: 2
     }) )
)
```
and beautify was applied to all files.

Then I tried (as suggested [here](/yeoman/yeoman/issues/1535#issuecomment-168262061))
```js
filter = gulpFilter(['**/*.js', '**/*.json'], { restore: true })
this.registerTransformStream(
    filter,
    beautify({
        indentSize: 4,
        max_preserve_newlines: 2
    }),
    filter.restore
)
```
and I got ``"write after end"`` error
