### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by brpaz** [yeoman/yo#551]
Hello.
I found a couple of closed issues regarding tab completion, like #222 but I couldn't understand if its implemented or not.

I tried to follow the instructions of this PR #436 yo-complete command returns nothing.

I really missed autocomplete in yo. 

Thank you.

**Comment by brpaz** [comment]
Ok. I found out I need to run  "yo completion" command to generate completion. Now its searching for completions but It didnt show any results.

I expect when I type yo tabtab to get a list of all installed generators. I am missing something?

Still, the yo completion command, could be better documented, maybe in the README file. I can do a PR with that, but first I need to have autocompletion fully working on my PC ;)

**Comment by SBoudrias** [comment]
Maybe @mklabs can weight in on that.

I believe the completion are auto-installed when possible, but I can see a lot of ways this wouldn't work by default - just like with git or other tools.

**Comment by brpaz** [comment]
I am revisiting old issues created by me and do some cleanup. Since this issue has 4 yo and I don´t use Yeoman anymore, I will close it.
