### ISSUE TITLE
npm install uuid /Users/v-link └── uuid@3.1.0   npm WARN enoent ENOENT: no such file or directory, open '/Users/v-link/package.json' npm WARN v-link No description npm WARN v-link No repository field. npm WARN v-link No README data npm WARN v-link No license field.

### ISSUE THREAD

**Issue by trollcodelord** [yeoman/yo#556]
## Type of issue

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Command line output

```
Paste your error output over here
```

**Comment by SBoudrias** [comment]
Was this issue open by mistake?

I'll close as no information is provided, but feel free to answer and I'll reopen if details and bug explanation are provided.
