### ISSUE TITLE
Npm install -g yo :::: FAILED

### ISSUE THREAD

**Issue by vishnu2017** [yeoman/yo#560]
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for timed-out

I have node and npm set to latest versions!!!!! 
Thanks for the help !!

![test](https://user-images.githubusercontent.com/20475543/34643413-eed01456-f349-11e7-8b7b-fe473e009e64.PNG)

**Comment by vishnu2017** [comment]
![image](https://user-images.githubusercontent.com/20475543/34643441-45b922f8-f34a-11e7-9d94-326d77eee5b9.png)

**Comment by SBoudrias** [comment]
NPM is having issues right now. You'll have to wait and try again later unfortunately 😞 

You can track the status over here https://status.npmjs.org

I'll close this ticket as not actionnable from our side.

**Comment by vishnu2017** [comment]
Thanks for the quick update I appreciate
