### ISSUE TITLE
yeoman installation failed

### ISSUE THREAD

**Issue by aswathykrishna18** [yeoman/yo#561]
[2018-01-16T08_11_34_094Z-debug.log](https://github.com/yeoman/yo/files/1634126/2018-01-16T08_11_34_094Z-debug.log)

**Comment by aswathykrishna18** [comment]
$ npm install --global yo
C:\Users\aswathy\AppData\Roaming\npm\yo-complete -> C:\Users\aswathy\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js
C:\Users\aswathy\AppData\Roaming\npm\yo -> C:\Users\aswathy\AppData\Roaming\npm\node_modules\yo\lib\cli.js

> spawn-sync@1.0.15 postinstall C:\Users\aswathy\AppData\Roaming\npm\node_modules\yo\node_modules\spawn-sync
> node postinstall

npm ERR! file C:\Users\aswathy\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
npm ERR! path C:\Users\aswathy\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\Users\aswathy\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! spawn C:\Users\aswathy\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng ENOENT
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aswathy\AppData\Roaming\npm-cache\_logs\2018-01-16T08_11_34_094Z-debug.log

**Comment by aswathykrishna18** [comment]
$ npm -v
5.6.0


$ node -v
v8.9.4

**Comment by SBoudrias** [comment]
That's the relevant part of your trace:

```
ENOENT
npm ERR!
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script.
```

You'd need to check why you couldn't build `spawn-sync`.
