### ISSUE TITLE
Not Found: @sindresorhus/is@^0.7.0

### ISSUE THREAD

**Issue by yangerlang** [yeoman/yo#564]
![image](https://user-images.githubusercontent.com/16792231/35494956-32796386-04f9-11e8-82b0-6a30a1256aa9.png)

**Comment by Valered** [comment]
+1

**Comment by SBoudrias** [comment]
Seems like an npm issue.

This package does exists: https://www.npmjs.com/package/@sindresorhus/is

You might be able to get support from npm team, but most likely it'll be back online soon.
