### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by vikramdurai** [yeoman/yo#567]
## Type of issue
Meta

----

## My environment
Github's env
* *OS version/details*: `eg. Windows 10 64-bit` dunno
* *Node version:* `x.x.x` (run `node --version` in your terminal) dunno
* *npm version:* `x.x.x` (run `npm --version` in your terminal) dunno
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal) not related

## Expected behavior
This repo should be active

## Current behavior
Dead repo

## Steps to reproduce the behavior
Visit project github source
## Command line output
-
```
Paste your error output over here
```
-

**Comment by SBoudrias** [comment]
If you think there's an important missing feature, please contribute and send a PR.

Otherwise, Yeoman's working pretty good for most people/use case; so there's not been a lot of changes recently. It just became a pretty stable project.
