### ISSUE TITLE
Problem with yo office in cmd 

### ISSUE THREAD

**Issue by Nikolay-Uvarov** [yeoman/yo#569]
I install last version(8.9.4 LTS) from: https://nodejs.org/en/ 
Then i run: npm install -g yo generator-office
and have some issues.
Also i run: npm i -g npm, but it doesn't help.
And i have problem with: yo office
## My environment

Windows 10 64-bit
Node version: v0.12.2
NPM version: 2.7.4
Version of yo : **const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.**

## Expected behavior

Open your command prompt/shell in an empty directory. Enter yo office and follow the prompts.+

Would you like to create a new subfolder for your project?: No
What would you want to name your add-in?: Git the Gist
Which Office client application would you like to support?: Outlook
Would you like to create a new project?: Yes, I need to create a new web app and manifest file for my add-in
Would you like to use TypeScript?: No
Choose a framework: Jquery

## Current behavior

see below

## Steps to reproduce the behavior
install node.js
>npm i -g npm
>npm install -g yo generator-office
>yo office
## Command line output
![errors](https://user-images.githubusercontent.com/22148553/36843320-9d2e909c-1d5f-11e8-98bb-95cc9f918620.jpg)

![after yo office](https://user-images.githubusercontent.com/22148553/36843420-f4588274-1d5f-11e8-9543-3fa2345ce3b4.jpg)

**Comment by SBoudrias** [comment]
We only support recent Node versions (6 and over)

**Comment by Nikolay-Uvarov** [comment]
@SBoudrias  but I have installed the latest version from: site [](https://nodejs.org/en/download/current/)
and in control panel I have
![latest](https://user-images.githubusercontent.com/22148553/36848865-91f9e190-1d73-11e8-82b5-5d5bbbf2599b.jpg)

**Comment by SBoudrias** [comment]
Run `node --version` inside your command line to see.

Also your first bug report stated you had Node 0.12?
