### ISSUE TITLE
ASP.Net Generator Global.json SDK Version Needs Update to Current

### ISSUE THREAD

**Issue by DanJ210** [yeoman/yo#571]
## Type of issue

Update scaffolding asp.net projects to match updated .Net Core 2.0 version. Global.json file has a version that doesn't work with current. Users who don't know or understand this will be stumped.

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
8.10.0
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
5.6.0
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)
2.0.1

## Steps to reproduce the behavior

npm install generator-aspnet
Select any aspnet application. I used Web Application Basic [without Membership and Authorization] but you can select any.
I selected Bootstrap but you can select any.
Name project.
Open project and start restoring and building.

The .Net Core tools will fail with code 1 because the SDK version in the scaffolded global.json file is an old "1.0.0-rc4-004771" version when it should be at least "2.0.0" which then fixes the issue. Without this you have to build every single time which can take quite a while for it to always fail. This has been an issue for almost a year now.

## Command line output

```
Failed to create prime the NuGet cache. restore failed with: 1
```

**Comment by SBoudrias** [comment]
Hi, the Yeoman core team doesn't maintains all the community generators (over 5000 now). You will need to open an issue on the repository of the generator you want to use to request supports or report bugs.

Cheers!

**Comment by DanJ210** [comment]
Ok thank you.
