### ISSUE TITLE
Ability to statically opt out of usage statistics

### ISSUE THREAD

**Issue by asottile** [yeoman/yo#575]
## Type of issue

feature

----

We use yeoman to template services at lyft and are composing a series of generators to template out code.  We run yeoman inside a docker container (as this fits best with our developer tooling setup).

Because yeoman is presented with a fresh filesystem on each run, it *always* prompts the user from this code [here](https://github.com/yeoman/yo/blob/479250a28220a6dcb75130f687f2e097498d4cfc/lib/cli.js#L183-L189).

This feature request is an ability to opt out of this through a commandline option (something like `--no-usage-statistics`) or through an environment variable `YO_NO_USAGE_STATISTICS=1` or something of the sort.

**Comment by mischah** [comment]
There actually is a CLI option for this: `--no-insight`.

See https://github.com/yeoman/yo#options

**Comment by asottile** [comment]
idk how I missed that!  Thanks!
