### ISSUE TITLE
Credits on original ideas

### ISSUE THREAD

**Issue by mklabs** [yeoman/yo#585]
## Credits

I'd like to clarify some things and give credits to Yehuda Katz (https://github.com/wycats) somewhere maybe in the readme. Yeoman wasn't at first a generator only thing, and was inspired by Thor.

Related:

- https://yehudakatz.com/2008/05/12/by-thors-hammer/
- http://whatisthor.com/
- https://github.com/erikhuda/thor

Everything comes from ideas, and the original one come from the Rails ecosystem. Languages are quite different and if you follow through, you'll see some similarities.

So thank you @rails, we learnt a lot from you. And thank you for maintaining @yeoman I know it is a huge work. I unfortunately don't have the time and energy to rework on yeoman right now, but maybe, just maybe a v3 with a more functional, focused and minimalist approach could be good.

It makes me remind also about grunt-usemin where the original idea was from @necolas

Note: Sorry if it's not the good place to open up this issue, I feel like yeoman/generators is more appropriate. A tweet about [webpacker](https://github.com/rails/rails/pull/33079) made me open this issue.

**Comment by mischah** [comment]
Hej Mickael,

I found 2 places which are mentioning Rails:

# 1. http://yeoman.io/learning/faq.html

![image](https://user-images.githubusercontent.com/441011/41876544-6ef47a1e-78ce-11e8-822e-d16679c92c9f.png)

# 2. https://github.com/yeoman/generator

![image](https://user-images.githubusercontent.com/441011/41876385-e19a60ca-78cd-11e8-972e-f40312328273.png)

Do you feel, that this should be mentioned more prominently?

**Comment by mklabs** [comment]
Thanks @mischah probably not, it was just an open letter I wrote before getting some sleep. I'm thinking about yeoman a lot recently.

**Comment by mklabs** [comment]
Some ideas:

- http://yeoman.io/humans.txt
- https://github.com/h5bp/html5-boilerplate/blob/master/src/humans.txt

**Comment by mklabs** [comment]
@mischah Let's close this
