### ISSUE TITLE
🐛 yo version check fails while behind proxy

### ISSUE THREAD

**Issue by Olian04** [yeoman/yo#589]
## Type of issue

🐛 __bug__ 

----

## My environment

* *OS version/details*: `Windows 10 64-bit`
* *Node version:* `10.5.0`
* *npm version:* `6.1.0` 
* *Version of yo :* `2.0.3`

## Expected behavior

I expect the version check to use the same proxy settings as npm does.

## Current behavior

At work I'm sitting behind a company proxy and for some reason the version check fails while the install succeeds. 

## Command line output

```powershell
PS C:\Users\xxqqvc\Projects\test> npm init -y
PS C:\Users\xxqqvc\Projects\test> ls

    Directory: C:\Users\xxqqvc\Projects\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       2018-07-04     11:48            200 package.json


PS C:\Users\xxqqvc\Projects\test> npm i --save yo

> spawn-sync@1.0.15 postinstall C:\Users\xxqqvc\Projects\test\node_modules\spawn-sync
> node postinstall


> yo@2.0.3 postinstall C:\Users\xxqqvc\Projects\test\node_modules\yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
{ RequestError: connect ETIMEDOUT 104.18.97.96:443
    at ClientRequest.req.once.err (C:\Users\xxqqvc\Projects\test\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 104.18.97.96:443',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
× yo version
{ RequestError: connect ETIMEDOUT 104.18.97.96:443
    at ClientRequest.req.once.err (C:\Users\xxqqvc\Projects\test\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 104.18.97.96:443',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
× yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

(node:6016) UnhandledPromiseRejectionWarning: Error: callback() can only be called once.
    at onetime (C:\Users\xxqqvc\Projects\test\node_modules\each-async\node_modules\onetime\index.js:15:11)
    at rule.verify.err (C:\Users\xxqqvc\Projects\test\node_modules\yeoman-doctor\lib\index.js:23:7)
    at binVersionCheck.then (C:\Users\xxqqvc\Projects\test\node_modules\yeoman-doctor\lib\rules\yo-version.js:21:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:6016) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6016) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
√ npm version

Found potential issues on your machine :(
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

+ yo@2.0.3
added 535 packages from 262 contributors and audited 1892 packages in 281.485s
found 0 vulnerabilities
```

**Comment by Olian04** [comment]
@SBoudrias I tried cloning that pr and got the same error.

```powershell
Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
{ RequestError: connect ETIMEDOUT 104.18.98.96:443
    at ClientRequest.req.once.err (C:\Users\xxqqvc\Projects\test\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 104.18.98.96:443',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
× yo version
{ RequestError: connect ETIMEDOUT 104.18.98.96:443
    at ClientRequest.req.once.err (C:\Users\xxqqvc\Projects\test\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  code: 'ETIMEDOUT',
  message: 'connect ETIMEDOUT 104.18.98.96:443',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
× yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

(node:15956) UnhandledPromiseRejectionWarning: Error: callback() can only be called once.
    at onetime (C:\Users\xxqqvc\Projects\test\yo\node_modules\each-async\node_modules\onetime\index.js:15:11)
    at rule.verify.err (C:\Users\xxqqvc\Projects\test\yo\node_modules\yeoman-doctor\lib\index.js:23:7)
    at binVersionCheck.then (C:\Users\xxqqvc\Projects\test\yo\node_modules\yeoman-doctor\lib\rules\yo-version.js:21:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:15956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
√ npm version

Found potential issues on your machine :(
added 960 packages from 1424 contributors and audited 5180 packages in 263.605s
found 12 vulnerabilities (2 low, 5 moderate, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by Olian04** [comment]
I managed to get it to pass by running `yo doctor` using `npx`.
```powershell
PS C:\Users\xxqqvc\Projects\test> npx yo doctor

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ yo version
√ npm version

Everything looks all right!
```

**Comment by MarcoScabbiolo** [comment]
@Olian04 can you confirm the `http_proxy` environment variable is properly set in your shell session?

**Comment by Olian04** [comment]
@MarcoScabbiolo Yea, I've got the proxy set both in npm, powershell and on a system wide level.
Ave already tried #588, but with no luck.

**Comment by SBoudrias** [comment]
@Olian04 could you also check if there's any chance this is related to the slow performance you're seeing from `yo`? The proxy support has been added recently, so maybe it had a side effect on the performance of some users.

@MarcoScabbiolo any chance you could have a quick look at the latests comments on #176, it seems correlated to adding the http proxy tunnel library.

**Comment by xbotuk** [comment]
I am having exact same issue.
I have authenticating proxy setup for NPM. It does not seem to be picked up by Yoman. What needs to be done?

**Comment by MarcoScabbiolo** [comment]
@xbotuk are you running the latest version of Yeoman (2.0.4)? On what npm config setting are you configuring the proxy and what is the proxy protocol (http/https)?

**Comment by Olian04** [comment]
@MarcoScabbiolo I just tried with #590/yo@2.0.4 but its still failing on `yo version`.

**Comment by MarcoScabbiolo** [comment]
Couldn't reproduce the issue so far, I debugged the request and it is being tunneled through my proxy. I'm on Win 10, using PowerShell.

```bash
PS D:\Tmp\yo\node> node -v
v8.11.3
PS D:\Tmp\yo\node> yo --version
2.0.4
PS D:\Tmp\yo\node> npm config get proxy
http://10.6.10.11:3389/
PS D:\Tmp\yo\node> yo doctor

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version
√ yo version

Everything looks all right!
PS D:\Tmp\yo\node> npx yo --version
npx: installed 1 in 1.292s
Path must be a string. Received undefined
D:\Tmp\yo\node\node_modules\yo\lib\cli.js
2.0.4
PS D:\Tmp\yo\node> npx yo doctor
npx: installed 1 in 1.172s
Path must be a string. Received undefined
D:\Tmp\yo\node\node_modules\yo\lib\cli.js

Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
√ npm version
√ yo version

Everything looks all right!
PS D:\Tmp\yo\node>
```

¿Can you share some details on the type of proxy you're using (or are being forced to use)?

**Comment by MarcoScabbiolo** [comment]
Please try #597 setting the `DEBUG` environment variable to `global-tunnel` and share the output.

**Comment by vladodias** [comment]
Had the same problem, I think it is a dodgy proxy, the following worked for me...
   npm config set registry=http://registry.npmjs.org/
   npm config set strict-ssl false
https://stackoverflow.com/questions/33162560/error-tunneling-socket-could-not-be-established-cause-connect-econnrefused-10

**Comment by aaronhawryluk** [comment]
I had this issue on WIn10 and needed to update my HTTP_PROXY env variable to get around it.
Previously, I had https://user:pass@proxy:port
I had to HTML-encode (percent-encode) the value of that variable to get the new yo (2.0.5) to work properly. I assume this is because whatever library does the HTTP_PROXY env variable parsing now needs a string with special characters encoded. Works like a charm now (and everything else that uses HTTP_PROXY seems fine with the change).

**Comment by SBoudrias** [comment]
@MarcoScabbiolo About the last comment from @aaronhawryluk, do you think we can fix that in the tunnel library directly?

**Comment by MarcoScabbiolo** [comment]
@SBoudrias Added [the issue](https://github.com/np-maintain/global-tunnel/issues/21), I should have some time in the weekend to get it done. Thanks @aaronhawryluk

**Comment by playhard21** [comment]
Having the same problem, did u solve it ?

**Comment by angular2fan** [comment]
+1, same issue. any fix yet?

**Comment by EstelleLUO** [comment]
I also ran into this issue... It may be something wrong with your npm proxy setting. You may try to clear .npmrc file (Or just comment the content)
get the upstream-proxy:
$ npm i upstream-proxy
Then it should work properly:
$ npm install -g yo

This works for me.

**Comment by mplwork** [comment]
I have the exact same problem, `npx yo doctor` works.

```
pc> npm i -g yo
C:\Users\mplwork\AppData\Roaming\npm\yo -> C:\Users\mplwork\AppData\Roaming\npm\node_modules\yo\lib\cli.js
C:\Users\mplwork\AppData\Roaming\npm\yo-complete -> C:\Users\mplwork\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js

> yo@2.0.5 postinstall C:\Users\mplwork\AppData\Roaming\npm\node_modules\yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

? Global configuration file is valid
? NODE_PATH matches the npm root
? Node.js version
? No .bowerrc file in home directory
? No .yo-rc.json file in home directory
{ RequestError: connect ECONNREFUSED 104.16.27.35:80
    at ClientRequest.req.once.err (C:\Users\mplwork\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNREFUSED',
  message: 'connect ECONNREFUSED 104.16.27.35:80',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
? yo version
{ RequestError: connect ECONNREFUSED 104.16.27.35:80
    at ClientRequest.req.once.err (C:\Users\mplwork\AppData\Roaming\npm\node_modules\yo\node_modules\latest-version\node_modules\got\index.js:73:21)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ECONNREFUSED',
  message: 'connect ECONNREFUSED 104.16.27.35:80',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/yo' }
? yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

(node:4500) UnhandledPromiseRejectionWarning: Error: callback() can only be called once.
    at onetime (C:\Users\mplwork\AppData\Roaming\npm\node_modules\yo\node_modules\each-async\node_modules\onetime\index.js:15:11)
    at rule.verify.err (C:\Users\mplwork\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-doctor\lib\index.js:23:7)
    at binVersionCheck.then (C:\Users\mplwork\AppData\Roaming\npm\node_modules\yo\node_modules\yeoman-doctor\lib\rules\yo-version.js:21:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:4500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
? npm version

Found potential issues on your machine :(
+ yo@2.0.5
updated 1 package in 85.266s

```

**Comment by tremblaysimon** [comment]
I encountered the same problem here. With @MarcoScabbiolo post (enable some debugging information for global-tunnel library) I saw that problem: 

```
DEBUG global-tunnel: Found proxy in environment variable https_proxy
DEBUG global-tunnel: Found proxy in environment variable http_proxy
DEBUG global-tunnel: Proxy configuration to be used is {
  "protocol": "localhost:",
  "host": "3128",
  "port": null,
  "proxyAuth": null
}
```

It's because for some reason I forgot to specify protocol for my proxy environment variables. Here what it's look like: 

```
https_proxy=localhost:3128
http_proxy=localhost:3128
```

after I fixed that problem (added http protocol), it works perfectly!

Now my environment variables for proxy are:

```
https_proxy=http://localhost:3128
http_proxy=http://localhost:3128
```
I don't know if it's a correct behavior from that library (global-tunnel) for not assuming any protocol...

In the end, I think we can close that bug if other people can confirm that their proxy environment variables wasn't set properly like me...

**Comment by mplwork** [comment]
> 
> 
> I encountered the same problem here. With @MarcoScabbiolo post (enable some debugging information for global-tunnel library) I saw that problem:
> 
> ```
> DEBUG global-tunnel: Found proxy in environment variable https_proxy
> DEBUG global-tunnel: Found proxy in environment variable http_proxy
> DEBUG global-tunnel: Proxy configuration to be used is {
>   "protocol": "localhost:",
>   "host": "3128",
>   "port": null,
>   "proxyAuth": null
> }
> ```

Can you help me with this? `setenv DEBUG global-tunnel` doesn't have any effect for me. What are the instructions exactly?


> 
> It's because for some reason I forgot to specify protocol for my proxy environment variables. Here what it's look like:
> 
> ```
> https_proxy=localhost:3128
> http_proxy=localhost:3128
> ```
> 
> after I fixed that problem (added http protocol), it works perfectly!
> 
> Now my environment variables for proxy are:
> 
> ```
> https_proxy=http://localhost:3128
> http_proxy=http://localhost:3128
> ```
> 
> I don't know if it's a correct behavior from that library (global-tunnel) for not assuming any protocol...
> 
> In the end, I think we can close that bug if other people can confirm that their proxy environment variables wasn't set properly like me...

I cannot confirm  this. I believe my variables are set correctly:

```
 pc# printenv | grep -i http
HTTP_PROXY=http://localhost:8888
HTTPS_PROXY=http://localhost:8888
```

```
 pc# npm config ls -l|grep -i prox
https-proxy = "http://localhost:8888/"
proxy = "http://localhost:8888/"
; https-proxy = null (overridden)
noproxy = null
; proxy = null (overridden)
 ```

@tremblaysimon 
Could you elaborate what your settings are?

**Comment by tremblaysimon** [comment]
I was testing only the command **yo doctor**, that works fine after I fixed my proxy environment variables. Installation with npm fails when using the yodoctor script (I suspect that script doesn't use global-tunnel).

If you run **yo doctor** you should see the debug information about global-tunnel. I don't see that information when running **npm install -g yo**.

I set DEBUG env var with that command: **export DEBUG=global-tunnel**.

**Comment by mplwork** [comment]
> 
> 
> I was testing only the command **yo doctor**, that works fine after I fixed my proxy environment variables. Installation with npm fails when using the yodoctor script (I suspect that script doesn't use global-tunnel).
> 
> If you run **yo doctor** you should see the debug information about global-tunnel. I don't see that information when running **npm install -g yo**.
> 
> I set DEBUG env var with that command: **export DEBUG=global-tunnel**.

Thank you. With `yo doctor` and `setenv DEBUG global-tunnel` (which is the equivalent of yours for my shell) I get the same results as you. But the issue was `npm i yo` and that is still broken.

**Comment by tremblaysimon** [comment]
@SBoudrias I think we can close that issue with the new doctor release!

**Comment by SBoudrias** [comment]
@tremblaysimon thanks a lot for your help!

**Comment by Carracer66** [comment]
Here's this FIX for the proxy issue:
as per the global-agent README.md, you must set env var:
export GLOBAL_AGENT_HTTP_PROXY=http://proxy_server:proxy_port
Issue resolved! Why was this buried in that README file!?!

**Comment by mplwork** [comment]
> 
> 
> Here's this FIX for the proxy issue:
> as per the global-agent README.md, you must set env var:
> export GLOBAL_AGENT_HTTP_PROXY=http://proxy_server:proxy_port
> Issue resolved! Why was this buried in that README file!?!

Interesting. So yeoman uses `global-agent`, good to know. If you manage to set env var `GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE` to an empty value, which is impossible from cmd but easy from node (`process.env.GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE="";`), your standard HTTP_PROXY settings will be used.

**Comment by coloco21** [comment]
Hi, I am still having issues with this. I have set http_proxy, proxy and https_proxy environment variables + the npm http-proxy, proxy and https-proxy conf settings globally + the GLOBAL_AGENT_HTTP_PROXY env var (tried with HTML URL encoding and without).
`yo doctor` works fine but `npm i yo` spends way too much time waiting for the yo version.

Normally this wouldn't be too much of an issue but this is impacting my Gitlab CI builds a lot as I use frontend-maven-plugin to do a npm install before every script. My build lasts for 20mn instead of maybe 3.

Could you please make the postinstall script use global-tunnel as well please ? @SBoudrias

**Comment by paztis** [comment]
I use yeoman over a private network without I internet access.
I point to a private repository (not nom) that contains all the needed modules.
Is there's a way to disable the Postinstall process of yo to avoid these useless checks over yo last version ?
Or do these checked through nom info command instead of any custom http request ?

For now all my Jenkins builds are long to build because of it.

Thanks

**Comment by paztis** [comment]
Perhaps you might remove this Postinstall step and let people decide to run it or not through the Postinstall of theirs module. When we work over a controlled environment, we don't care all of these checks

**Comment by Olian04** [comment]
> Perhaps you might remove this Postinstall step and let people decide to run it or not through the Postinstall of theirs module. When we work over a controlled environment, we don't care all of these checks

Have you tried disabling post-install scripts when installing deps? Might be enough for your use case.

```
$ npm install --ignore-scripts
```

**Comment by paztis** [comment]
Other modules have Postinstall scripts that are importants.
I want only to disable this Postinstall one. I've look in the code source and there's no way to disable it.
An env var check might be added for example to do this
YO_DOCTOR_DISABLE for example

**Comment by Olian04** [comment]
> Other modules have Postinstall scripts that are importants. I want only to disable this Postinstall one. I've look in the code source and there's no way to disable it. An env var check might be added for example to do this YO_DOCTOR_DISABLE for example

You should probably open a feature request issue for that.

**Comment by paztis** [comment]
Sure.
Done in this one #714

**Comment by weshouman** [comment]
> > Here's this FIX for the proxy issue:
> > as per the global-agent README.md, you must set env var:
> > export GLOBAL_AGENT_HTTP_PROXY=http://proxy_server:proxy_port
> > Issue resolved! Why was this buried in that README file!?!
> 
> Interesting. So yeoman uses `global-agent`, good to know. If you manage to set env var `GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE` to an empty value, which is impossible from cmd but easy from node (`process.env.GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE="";`), your standard HTTP_PROXY settings will be used. Note, I didn't try any of this with yeoman.

I would recommend, that this issue be fixed at `global-agent`'s side by avoiding differentiating the behavior based on whether `GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE` is `undefined` or set to empty, thus respecting Windows restrictions.

*The current workaround though is setting the env variable as mentioned from inside javascript:
for example: change `node_modules\yeoman-doctor\lib\rules\yo-version.js` to include*
```
...
exports.verify = async () => {
  try {
    process.env.GLOBAL_AGENT_ENVIRONMENT_VARIABLE_NAMESPACE="";
...
```
