### ISSUE TITLE
Running yo CLi choosing default prompts without user interacations

### ISSUE THREAD

**Issue by masterviana** [yeoman/yo#609]
I would like to ask if there is any flag or option in yeoman CLI tool to choose all default prompts parametes without user interesation. 

I've search in inquier documentation issues tracker, I've found some old discussion about passing a JSON file containing all the answeers for que quetions?

My final goal is running the yeoman process fired using another process so that way it doesn't have the any user interaction. There is any way to to that?

**Comment by SBoudrias** [comment]
There's no such global options, but generator author can implement this on their own if desired.

You can see how generator-node implemented a similar idea: https://github.com/yeoman/generator-node/blob/master/generators/app/index.js#L184

**Comment by masterviana** [comment]
You can close the ticket I found the solution its a external tool to do what I want to do

https://www.npmjs.com/package/yeoman-gen-run
