### ISSUE TITLE
Your yo version is outdated in Windows Server 2019 Standard

### ISSUE THREAD

**Issue by kavaghela** [yeoman/yo#610]
I am trying to install Yeoman in my pc but it gives error like "Your yo version is outdated".

My environment

OS version/details: Windows Server 2019 Standart
Node version: v10.15.1
npm version:6.7.0

It's the fresh machine I installed latest node JS from officecial site today.
I want to install Yeoman for development of SPFX web part hence I ran below command to install it

**npm install -g yo**

When I run above command it gives below error 

```
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
C:\Users\sp_admin\AppData\Roaming\npm\yo -> C:\Users\sp_admin\AppData\Roaming\npm\node_modules\yo\lib\cli.js
C:\Users\sp_admin\AppData\Roaming\npm\yo-complete -> C:\Users\sp_admin\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js

> yo@2.0.5 postinstall C:\Users\sp_admin\AppData\Roaming\npm\node_modules\yo
> yodoctor


Yeoman Doctor
Running sanity checks on your system

√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ Node.js version
√ No .bowerrc file in home directory
√ No .yo-rc.json file in home directory
× yo version

Your yo version is outdated.

Upgrade to the latest version by running:
npm install -g yo@latest

√ npm version

Found potential issues on your machine :(
+ yo@2.0.5
updated 1 package in 42.608s
```

Could you please help me what I am missing here?

I tried below links to resolve issue but none of this would help
[#591](https://github.com/yeoman/yo/issues/591)
[#38](https://github.com/yeoman/doctor/issues/38)
[#589](https://github.com/yeoman/yo/issues/589)

**Comment by MajDogbyte** [comment]
im having this same issue
