### ISSUE TITLE
yo --generators command is showing folders not intended to be generators

### ISSUE THREAD

**Issue by andrewvaughan** [yeoman/yo#611]
## Type of issue

A bug!

## My environment

* *OS version/details*: `MacOS 10.13.6 (High Sierra)`
* *Node version:* `10.13.0`
* *npm version:* `6.7.0`
* *Version of yo :* `2.0.5`

## Expected behavior

When running `yo --generators` on the command line, I expect to see all generators and sub-generators as prescribed in the `package.json` file under the `files` array.

My current generator has a `generators` folder, and my `package.json` section looks as follows:

```json
  "files": [
    "generators"
  ],
  "keywords": [
    "yeoman-generator"
  ],
```

As such, I would expect only folders in my `./generators/` directory to be listed as sub-generators.

My current generator project has a structure similar to this:

```
generators/
  app/
    index.js
  expected-generator/
    index.js
gulpfile.js/
  index.js
package-lock.json
package.json
```

And I would expect the following on the command line:

```
$ yo --generators
Available Generators:

  my-generator
    expected-generator
```

## Current behavior

All folders in both the root and `generators` directories that contain an `index.js` file are being listed as sub-generators.  As such, when I create an advanced `gulpfile.js` folder, this is being listed as a sub-generator.

```
$ yo --generators

Available Generators:

  my-generator
    expected-generator
    gulpfile.js
```

Given that I explicitly stated for the `generators` folder in my `files` array to contain my generators, I would expect other, non-related directories to be ignored.

## Steps to reproduce the behavior

Create a generator with the above configuration in `package.json` and create any directory with an `index.js` file in the root.  These should not show up as a sub-generator unless explicitly listed in the `files` array, according to the documentation, but as of now, all folders are listed as sub-generators (regardless of what is in `files`).

## Command line output

N / A

**Comment by SBoudrias** [comment]
Yeoman doesn't read the package.json file to know which folders are generators. We looks at the folder structure, and in this case, gulpfile.js is in a generator location.

That being said, as this file won't be included in your published package, it won't be an issue once published to npm.

**Comment by andrewvaughan** [comment]
Thanks for the response.  Just in case it's helpful, your explanation seems in contrast to the Yeoman documentation:

> Yeoman allows two different directory structures. It’ll look in `./` and in `generators/` to register available generators.
>
>...
>
> If you use this second [`generators/`] directory structure, make sure you point the files property in your package.json at all the generator folders.
>
> ```
>{
>  "files": [
>    "app",
>    "router"
>  ]
>}
>```

I don't plan on publishing the package (we use it internally), so it's a bit inconvenient for me, but not a high-priority issue
