### ISSUE TITLE
All commands fail with a TypeError

### ISSUE THREAD

**Issue by RichardMisiak** [yeoman/yo#613]
## Type of issue

Bug

----

## My environment

* *OS version/details*: Windows 10 64-bit
* *Node version:* 10.15.3
* *npm version:* 6.9.0
* *Version of yo :* 2.0.5

## Expected behavior

Yo works

## Current behavior

All `yo` commands fail with an error

## Steps to reproduce the behavior

```
npm install -g yo
yo
```

## Command line output

```
C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\node_modules\conf\index.js:69
                        throw new TypeError('Use `delete()` to clear values');
                        ^

TypeError: Use `delete()` to clear values
    at Conf.set (C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\node_modules\conf\index.js:69:10)
    at Insight.set optOut [as optOut] (C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\node_modules\insight\lib\index.js:56:15)
    at Object.<anonymous> (C:\Users\Richard\AppData\Roaming\npm\node_modules\yo\lib\cli.js:198:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
```

**Comment by bmbknds** [comment]
I have same issue in Mac Os Mojave :'(

**Comment by wkcole** [comment]
![image](https://user-images.githubusercontent.com/8675871/56094895-fd44ce00-5f09-11e9-9199-90a81942b421.png)
![image](https://user-images.githubusercontent.com/8675871/56094910-0cc41700-5f0a-11e9-9e6d-3b1204b5612a.png)

me too...

**Comment by bmbknds** [comment]
@SBoudrias Sbau, @sindresorhus 
can you help us, please?

**Comment by naporin0624** [comment]
I also tried with windows and mac, but I got the same error.

**Comment by mischah** [comment]
Can’t reproduce this running macOS 10.14.4 with Yo v2.0.5 on Node 8 or 11 😕 

<img alt="" src="https://user-images.githubusercontent.com/441011/56096593-7e8c6880-5eea-11e9-98b6-0031ed967dde.png">
<img alt="" src="https://user-images.githubusercontent.com/441011/56096596-83511c80-5eea-11e9-91f9-b864eba9fc05.png">

**Comment by mischah** [comment]
According to the stack trace above the error seems comes from a »wrongish« value passed to the conf module over here:
https://github.com/yeoman/insight/blob/08e254e60706d24ff22982cb14d690772d428d04/lib/index.js#L56

But I still can’t reproduce after opting of insight via `yo --no-insight`.

**Comment by ankurgupta325** [comment]
getting the same error:

node --version
v10.15.3

yo --version
2.0.5

Windows 10 machine.

**Comment by RichardMisiak** [comment]
@mischah it appears to be caused by the latest (0.10.2) of insight
Removing the caret from [this line]( https://github.com/yeoman/yo/blob/db5372d666d50774f223656422004283dd73d51a/package.json#L56) and running npm install fixes my local copy

**Comment by wujc12** [comment]
getting the same error:
Both on Ubuntu 16.04 and Windows 10.

**Comment by mischah** [comment]
Thanks @RichardMisiak  Going to publish a new `yo` version in a few minutes which has a pinned version of insight 0.10.1.

**Comment by bmbknds** [comment]
did you resolved the main error ? Richard

**Comment by mischah** [comment]
It would be awesome if people could stop posting »me too« comments 😆

**Comment by mischah** [comment]
# Fixed

Yo `2.0.6` fixes this and landed in the npm registry.

So all affected users just have to install the latest version to get rid of this bug:

```
npm install -g yo@latest
```
