### ISSUE TITLE
Fix using yo behind a proxy on Node versions >= 11.6.0

### ISSUE THREAD

**Issue by mischah** [yeoman/yo#616]
## Type of issue

Bug

## What happens

Running `yo` fails when using a system Proxy since Node.js `11.6.0`.

## Background

We are using [global-tunnel-ng](https://github.com/np-maintain/global-tunnel) to make it possible to use yo behind a proxy. This was implemented in https://github.com/yeoman/yo/pull/573.

Sadly `global-tunnel-ng`is broken since Node.js `11.6.0` and [according](https://gitter.im/yeoman/yeoman?at=5cc4c9e63d78aa6c03a7065c) to one of the contributors it probably won’t support newer Node versions in the future.

## How to fix this

Switch from using `global-tunnel-ng` to [global-agent](https://github.com/gajus/global-agent):

1. Change the global-tunnel initialization at the entry of the [yo cli](https://github.com/yeoman/yo/blob/932ef07104b81de32fa3f0f6c9c2df61f4f0d9e6/lib/cli.js#L20) and [yo doctor](https://github.com/yeoman/doctor/blob/3a3689c2d88ff1c1233e728313a38e6c4edaaec0/lib/cli.js#L6) according https://github.com/gajus/global-agent/blob/master/README.md#usage should do the trick
1. Adding a note in the documentation would help, mainly because global-agent uses the environment variable GLOBAL_AGENT_HTTP_PROXY instead of the traditional HTTP_PROXY. Keep in mind global-agent does not look for a proxy in the npm configuration and may not support all the different kinds of proxy connections.

## How to test this

This should be testable using a local proxy like [Burp Proxy ](https://portswigger.net/burp), [Charles](https://www.charlesproxy.com/) or [mitmproxy](https://mitmproxy.org/).

## Who could help with this

@gajus, the maintainer of 'global-agent' was so kind to offer his help in the [Yeoman Chat](https://gitter.im/yeoman/yeoman?at=5cc70b3e3d78aa6c03b5da9a) 💖

**Comment by gajus** [comment]
> Change the global-tunnel initialization at the entry of the yo cli and yo doctor according https://github.com/gajus/global-agent/blob/master/README.md#usage should do the trick

The only thing to consider is that `global-agent` in its current form support only Node.js v11.6.0+ (officially, v12+). I can implement support for older Node.js versions if it is required?

**Comment by mischah** [comment]
Oops. I just read that `global-agent` [only supports Node.js v12 and above]. 
So it’s probably a bit early to do a simple switch from `global-tunnel-ng` to `global-agent`.

@SBoudrias, What do you think to check the Node version and do a conditional require depending on that?

**Comment by mischah** [comment]
@gajus Yeah. We support Node back to the current [Maintenance LTS](https://github.com/nodejs/Release) version.

> I can implement support for older Node.js versions if it is required?

Is this possible?

**Comment by gajus** [comment]
> Is this possible?

Yes, it is relatively straightforward change. Just need to patch `http.reqest` and `http.get` methods.

Can have this out by mid week.

**Comment by mischah** [comment]
That would be awesome 💯
Could you ping us in this issue when it’s done?

**Comment by gajus** [comment]
Node v10 is supported as of [v1.5.0](https://github.com/gajus/global-agent/releases/tag/v1.5.0).

**Comment by LitoMore** [comment]
@gajus `yo` requires `node >=8`, but `global-agent` requires `node >= 10`. Maybe we need to change `engines` to `node: >=8`?

Does `global-agent` support Node.js 8 in `global-agent@1.5.0`?

**Comment by LitoMore** [comment]
> Does global-agent support node >= 8 in 1.5.0?

I checked. `global-agent@1.5.0` does not support 1.5.0.

@gajus Is that possible add support for Node.js 8?

**Comment by gajus** [comment]
@LitoMore Have you tested it with Node v8?

I have not tested it, but it should work. As far as I know, there were no features added to HTTP core module that would have changed http agent behaviour between v8 and v10.

**Comment by LitoMore** [comment]
@gajus Yes, I tested that `global-agent@1.5.0` does not support Node.js 8.

Could you add support for Node.js 8 also?

**Comment by gajus** [comment]
It is not something that I can take a look at immediately, but I have added it to my TODO list.

https://github.com/gajus/global-agent/issues/7

**Comment by gajus** [comment]
I have added example of how to conditionally use `global-agent` or `global-tunnel-ng` depending on the Node.js version. No plan to support Node.js <10.

https://github.com/gajus/global-agent#setup-proxy-using-bootstrap-routine
