### ISSUE TITLE
name.socket.js not generated

### ISSUE THREAD

**Issue by lilian131** [yeoman/yo#621]
## Type of issue

bug

----

## My environment

* *OS version/details*: `macos mojave 10.14.4`
* *Node version:* `10.15.1`
* *npm version:* `6.4.1` 
* *Version of yo :* `2..0.5`

## Expected behavior

name.sockes.js should be generated when yo angular-fullstack:endpoint name
## Current behavior

name.socket.js file is not generated
## Steps to reproduce the behavior
just yo angular-fullstack:endpoint name
## Command line output

```
yo angular-fullstack:endpoint shopPacket
? What will the url of your endpoint be? /api/shopPackets
   create server/api/shopPacket/shopPacket.controller.js
   create server/api/shopPacket/shopPacket.events.js
   create server/api/shopPacket/shopPacket.integration.js
   create server/api/shopPacket/shopPacket.model.js
   create server/api/shopPacket/index.js
   create server/api/shopPacket/index.spec.js
```

**Comment by SBoudrias** [comment]
Please report this bug to `generator-angular-fullstack`. The Yeoman core team unfortunately cannot provide supports for all open-sourced generators.

**Comment by lilian131** [comment]
Solution gave here https://stackoverflow.com/questions/56750046/yo-angular-fullstackendpoint-message-does-not-generate-message-socket-js
