### ISSUE TITLE
Running `yo` in PowerShell 6 requires administrative rights

### ISSUE THREAD

**Issue by ManfredLange** [yeoman/yo#627]
## Type of issue

----

## My environment

* *OS version/details*: `Windows 10 64-bit, 1903`
* *Node version:* `10.14.2` (run `node --version` in your terminal)
* *npm version:* `6.10.1` (run `npm --version` in your terminal)
* *Version of yo :* `3.1.0` (run `yo --version` in your terminal)
* *Version of PowerShell Core:* `6.2.2`, 64 bit

## Expected behavior

After installing yo with `npm install -g yo` I can use `yo` commands in PowerShell terminal without running it "As Administrator".

## Current behavior

After installing yo with `npm install -g yo`, in the PowerShell terminal without administrative rights it fails with message:

> yo : The term 'yo' is not recognized as the name of a cmdlet, function, script file, or operable program.

## Steps to reproduce the behavior

1. Install PowerShell Core version 6.2.2, 64 bit. This is the cross platform version of PowerShell. The one that is currently bundled with Windows 10 is version 5.1.18362.145
2. Install `yo` with `npm install -g yo`
3. Open a PowerShell 6 terminal
4. Execute `yo` commands, e.g. `yo doctor`

## Command line output

```
The term 'yo' is not recognized as the name of a cmdlet, function, script file, or operable program.
```

## More Observation

Running `yo` in a PowerShell terminal as an Administrator works fine. However, this essentially means that all `yo` commands would run with administrative permissions as well, introducing additional risks.

Also while `npm install -g yo` executes, the following error is shown in the output of "Yeoman Doctor":
```
Error: Couldn't find the 'yo' binary. Make sure it's installed and in your $PATH
```
This error may or may not be related.

**Comment by ManfredLange** [comment]
The PowerShell 6 version I'm using is the cross-platform version. It is possible that the same problem manifests differently or not at all on non-Windows platforms such as MacOS or Linux.

**Comment by SBoudrias** [comment]
This is an issue on your machine. When you install yo globally with npm, that binary end up being reserved for admin only. I'm not too familiar with Windows, but you could install the dependency somewhere else (see `npm prefix`) or change the default permissions or binaries installed in the global npm folder.

That's not something we can fix on our side.

Hope this help you debug your issue.

**Comment by ManfredLange** [comment]
@SBoudrias Simon, your comment was actually very helpful. Based on what you wrote I had another look, `npm prefix` put me on the right track, although I ended up using `npm bin -g`.

Here is I resolved the issue:

1. Use `npm bin -g` (or `npm bin -global`) to determine where global npm packages are installed. In my case the path was `C:\Users\<UserName>\AppData\Roaming\npm`
2. Add the path found in step 1 to the `PATH` environment for the *User*
3. Restart `Explorer.exe` or log out and back in
4. Start a new terminal, CMD or PowerShell (version doesn't matter). `yo` now works. No need to run it with administrative rights.

I noticed there were a few entries for `npm` but suspect they were incorrect due to the installer/unintaller script of some older version. I've had this box for quite some time.

So, all sorted! Thank you again, and keep up the great work! Yeoman has proven to be a very valuable tool for our work in the cloud with microservices, functions, build pipelines, etc. :-)

**Comment by carsten-engelke** [comment]
> * Add the path found in step 1 to the `Path` environment for the _User_ (not the System environment variable)

The Powershell command to do this is:
`$env:Path += ";C:\Users\YOUR_USERNAME\AppData\Roaming\npm"`
Mind the leading semicolon.
