### ISSUE TITLE
cli-list

### ISSUE THREAD

**Issue by jamen** [yeoman/yo#628]
I made the [cli-list](https://github.com/jamen/cli-list) dependency for https://github.com/yeoman/yo/pull/414, but I don't use generators anymore, and I was wondering where I could transfer the package.

**Comment by SBoudrias** [comment]
Do you want to transfer it to the Yeoman organization?

I can transfer your repo if you give me write access to it.

**Comment by jamen** [comment]
@SBoudrias Sounds good to me. I'm not sure how to give you access, but I sent a collaborator and transfer request to you.

**Comment by SBoudrias** [comment]
There it is https://github.com/yeoman/cli-list :)

Cheers
