### ISSUE TITLE
[Need Help]How to use a generator which is not start with generator-?

### ISSUE THREAD

**Issue by Sara2009** [yeoman/yo#632]
We use a private registry where all the npm packages we publish are under the namespace named @componyName. For example, @componyName/generator-myapp. How can I yo this generator?
`yo @componyName/generator-myapp`
`yo myapp`
Not work!

**Comment by SBoudrias** [comment]
You have 2 choices:

1. `yo @companyName/myapp` (I believe that's the right syntax for scoped packages; you can always run `yo generators` to see all available namespaces)
2. `yo /node_modules/@companyName/myapp/app/index.js` (you can also run directly by filepath as a workaround)

**Comment by Sara2009** [comment]
> You have 2 choices:
> 
> 1. `yo @companyName/myapp` (I believe that's the right syntax for scoped packages; you can always run `yo generators` to see all available namespaces)
> 2. `yo /node_modules/@companyName/myapp/app/index.js` (you can also run directly by filepath as a workaround)

I choose the first solution. It works well~ Thank you very much!

**Comment by Sara2009** [comment]
> You have 2 choices:
> 
> 1. `yo @companyName/myapp` (I believe that's the right syntax for scoped packages; you can always run `yo generators` to see all available namespaces)
> 2. `yo /node_modules/@companyName/myapp/app/index.js` (you can also run directly by filepath as a workaround)
A little mistake: 
run `yo --generators` to see all available generators
