### ISSUE TITLE
npm audit - low severity vulnerability

### ISSUE THREAD

**Issue by Mamuuut** [yeoman/yo#634]
## Vulnerability found in npm audit security report

It seems the fullname dependency needs to be updated.
```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Denial of Service                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ mem                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=4.0.0                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ yo [dev]                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ yo > fullname > mem                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1084                            │
└───────────────┴──────────────────────────────────────────────────────────────┘

```

**Comment by Mamuuut** [comment]
Already fixed in master branch. Still waiting for a new release.

**Comment by Bharat311** [comment]
Hey @SBoudrias, Thanks for the amazing work on this package. :+1: :smile: 

Any ETA on when can we expect a newer release with the fix above. I am eagerly waiting for the updated package to use in some of my projects.

**Comment by SBoudrias** [comment]
I pushed a new version to npm.

BTW `yo` being a dev dependency, this doesn't make your apps vulnerables to hacking.

As you might guess and see, `npm audit` generates a LOT of noise, and it's next to impossible for project maintainers to keep on top of this across all our repositories.

I'm not sure if these are requirements from your company or what, but those tools are creating a lot of extra work and noise for the maintainers; so I'd encourage to not add more on top of what's already out there requesting package maintainers to constantly update (that's the best way to burn us all).
