### ISSUE TITLE
npm install -g yo fails

### ISSUE THREAD

**Issue by johnnyak99** [yeoman/yo#636]
## Type of issue
Bug
## My environment

* *OS version/details*: `CentOS Linux release 7.7.1908 (Core)`
* *Node version:* `v6.17.1`
* *npm version:* `3.10.10`
* *Version of yo :* `N/A`

## Expected behavior

npm install -g yo will install OK

## Current behavior
SyntaxError: Unexpected token (

## Steps to reproduce the behavior
npm install -g yo

## Command line output

npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
/home/john/.npm-packages/bin/yo -> /home/john/.npm-packages/lib/node_modules/yo/lib/cli.js
/home/john/.npm-packages/bin/yo-complete -> /home/john/.npm-packages/lib/node_modules/yo/lib/completion/index.js

> core-js@3.6.0 postinstall /home/john/.npm-packages/lib/node_modules/yo/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> spawn-sync@1.0.15 postinstall /home/john/.npm-packages/lib/node_modules/yo/node_modules/spawn-sync
> node postinstall

> yo@3.1.1 postinstall /home/john/.npm-packages/lib/node_modules/yo
> yodoctor

/home/john/.npm-packages/lib/node_modules/yo/node_modules/yeoman-doctor/lib/index.js:12
  (async () => {
         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/john/.npm-packages/lib/node_modules/yo/node_modules/yeoman-doctor/lib/cli.js:3:1)
npm ERR! Linux 3.10.0-1062.4.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "yo"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! yo@3.1.1 postinstall: `yodoctor`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the yo@3.1.1 postinstall script 'yodoctor'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     yodoctor
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yo
npm ERR! Or if that isn't available, you can get t
[npm-debug.log](https://github.com/yeoman/yo/files/3991932/npm-debug.log)
heir info via:
npm ERR!     npm owner ls yo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/john/npm-debug.log

**Comment by johnnyak99** [comment]
Looks like Async functions are not supported by Node versions older than version 7.6. ... 
Guess I will have to try something different here

**Comment by brianpmccullough** [comment]
I see closed, but in case anyone else is coming across this and wondering what else to try, you could try uninstalling "yo" (npm uninstall -g yo).  The reinstalling with a particular version number such as 2.0.6 (npm install -g yo@2.0.6).  If you are developing with Microsoft's SharePoint Framework (SPFx), you may need to do this in order to develop for earlier versions of SharePoint (e.g. SharePoint 2016/2019).
