### ISSUE TITLE
cant change Hashrouter to BrowserRouter

### ISSUE THREAD

**Issue by waveheart** [yeoman/yo#640]
i need use some property of BrowserRouter, i tried to change hashRouter to browserRouter,
```
    devServer: {
      headers: {
        'Access-Control-Allow-Origin': '*'
      },
     ...
      historyApiFallBack: true
    }
```
it didn't work, do i need set other settings?

**Comment by SBoudrias** [comment]
Please report bugs running a generator on the specific generator repository.

The Yeoman team works on the core system and unfortunately cannot maintain the ~5000 publicly available generators. Thanks for your understanding!
