### ISSUE TITLE
Yeoman gives warnings on installation and although it gets installed successfully, but it doesn't work as expected!

### ISSUE THREAD

**Issue by imalitavakoli** [yeoman/yo#653]
## My environment

* *OS version/details*: Windows 10 64-bit`
* *Node version:* `14.15.1`
* *npm version:* `6.14.8`
* *Version of yo :* `3.1.1`

## Expected behavior

I expect Yeoman to be installed without any warnings!

## Current behavior

Yeoman gets installed with warnings! But it installs successfully... But that's not all! Actually, it didn't get installed successfully! The Yeoman options won't work as expected like before! I mean when I run `yo` to see the options... Yeoman says use the array keys to choose what you like to do... But arrow keys won't choose the options! This problem is also true when I like to customize a generator's options when I'm going to scaffold a brand new project... The arrow keys just don't work!

![MINGW64__c_Users_ponte-11_18_2020-6_20_29-PM](https://user-images.githubusercontent.com/12460805/99558014-87072800-29d8-11eb-88d7-ac9140f452f7.jpg)

## Steps to reproduce the behavior

Just run `npm install -g yo` to install Yeoman in Git Bash(Version 2.29.2)

## Command line output

```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
C:\Users\ponte\AppData\Roaming\npm\yo -> C:\Users\ponte\AppData\Roaming\npm\node_modules\yo\lib\cli.js
C:\Users\ponte\AppData\Roaming\npm\yo-complete -> C:\Users\ponte\AppData\Roaming\npm\node_modules\yo\lib\completion\index.js
```

**Comment by imalitavakoli** [comment]
It appears that the problem is with the Git Bash(Version 2.29.2)! Selecting the options with arrow keys work just fine inside the Windows Command Prompt.

**Comment by retorquere** [comment]
The warnings are not just on windows though -- I get the deprecation warnings too on MacOS.
