### ISSUE TITLE
yeoman-environment  version error

### ISSUE THREAD

**Issue by qiangzi7723** [yeoman/yo#660]
## Type of issue
*  When I run `yo generator-xxx`, I got a error, it seems dependencies was wrong.
----

## My environment

* *OS version/details*: `osx`
* *Node version:* `15.12.0` (run `node --version` in your terminal)
* *npm version:* `7.6.3` (run `npm --version` in your terminal)
* *Version of yo :* `3.1.1` (run `yo --version` in your terminal)

## Steps to reproduce the behavior
```
yo generator-xxx(this is my generator)
```

## Command line output

```
Error

This generator (via:app) requires yeoman-environment at least 3.0.0, current version is 2.10.3, try reinstalling latest version of 'yo' or use '--ignore-version-check' option
```

In the yo project, we can see the package.json file, the dependencies yeoman-environment version is `"yeoman-environment": "^2.4.0",`, in my computer's node_modules, the download yeoman-environment's version is `2.10.3`, so I think  this is the reason.

I try delete `yeoman-environment`  and reinstall `yeoman-environment 3.2.0`, but it seems no work.

**Comment by qiangzi7723** [comment]
Dependencies link here：https://github.com/yeoman/yo/blob/v3.1.1/package.json

**Comment by qiangzi7723** [comment]
I update yo's version to 4.0.0, and can solve this problem. But this version seems it is not stable?

**Comment by mshima** [comment]
Yo 4.0.0 and 4.1.0 should be stable.
You can downgrade yeoman-generator to 4.x to use yo@3.
