### ISSUE TITLE
Security: Upgrade meow

### ISSUE THREAD

**Issue by ntucker** [yeoman/yo#672]
## Type of issue

Security

https://www.npmjs.com/advisories/1753 is problematic due to super outdated meow

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Command line output

```
Paste your error output over here
```

**Comment by timwright12** [comment]
+1
