### ISSUE TITLE
yo code, lookups.flatMap is not a function

### ISSUE THREAD

**Issue by Lhhpw0204** [yeoman/yo#681]
## Type of issue

----

## My environment

* *OS version/details*: macOS 10.15.7 (19H15)
* *Node version:*  v10.24.0
* *npm version:* 6.14.11
* *Version of yo :* 4.3.0

## Expected behavior
yo code work

## Current behavior
yo code fail

## Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/37644477/131817411-27d97433-ab9b-47e1-8db1-6cdba5734f7c.png)

## Command line output

```
Paste your error output over here
```

**Comment by SBoudrias** [comment]
This is due to your old Node.js version. Version 10 has been out of LTS for a while already; so we dropped support.

See https://nodejs.org/en/about/releases/ for more information about stable Node versions.
