### ISSUE TITLE
Trying to copy from a source that does not exist

### ISSUE THREAD

**Issue by kachihro** [yeoman/yo#736]
## Type of issue
Cannot copy from a location - the file DOES exist.

Trying to copy from a source that does not exist: 
C:\Program Files (x86)\Nodist\bin\node_modules\@microsoft\generator-sharepoint\lib\generators\solution\templates\spo\tsconfig.json

----

## My environment

* *OS version/details*: 
* Windows 11 64-bit

* *Node version:* `x.x.x` (run `node --version` in your terminal)
12.22.7    (using NODIST as node manager)

* *npm version:* `x.x.x` (run `npm --version` in your terminal)
6.14.15

* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)
4.3.0

(using package for SPFX @microsoft/generator-sharepoint)

## Expected behavior
When creating new project, the template would define a scaffolded new solution.
I've tried with different NODE versions (switching using NODIST)

## Current behavior
Error message ; 
Error

Trying to copy from a source that does not exist: C:\Program Files (x86)\Nodist\bin\node_modules\@microsoft\generator-sharepoint\lib\generators\solution\templates\spo\tsconfig.json

## Command line output

C:\Repos\Nintex\SPFX-CONSENT [master ≡ +2 ~0 -0 !]> yo
? 'Allo Chris! What would you like to do? @microsoft/sharepoint

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo @microsoft/sharepoint

     _-----_     ╭──────────────────────────╮
    |       |    │      Welcome to the      │
    |--(o)--|    │  SharePoint Online SPFx  │
   `---------´   │  Yeoman Generator@1.14.0 │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

See https://aka.ms/spfx-yeoman-info for more information on how to use this generator.
Let's create a new SharePoint solution.
? What is your solution name? spfx-consent
? Which type of client-side component to create? WebPart
Add new Web part to solution spfx-consent.
? What is your Web part name? HelloWorld
? Which template would you like to use? React

Error

Trying to copy from a source that does not exist: C:\Program Files (x86)\Nodist\bin\node_modules\@microsoft\generator-sharepoint\lib\generators\solution\templates\spo\tsconfig.json

     _-----_     ╭───────────────────────╮
    |       |    │      Bye from us!     │
    |--(o)--|    │       Chat soon.      │
   `---------´   │      Yeoman team      │
    ( _´U`_ )    │    http://yeoman.io   │
    /___A___\   /╰───────────────────────╯
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

**Comment by mischah** [comment]
Hej, this seems to be a problem with the generator you are using: 

[@microsoft\generator-sharepoint](https://www.npmjs.com/package/@microsoft/generator-sharepoint)

I guess that’s the repo where you should post this issue 🤔 
https://github.com/SharePoint/sp-dev-docs/issues
