### ISSUE TITLE
homebrew package manager

### ISSUE THREAD

**Issue by gintering1000** [yeoman/yo#741]
## Type of issue : Feature request

may i ask this cli homebrew package?

for example : brew install yeoman

cuz. it is not only for web developer.
even native android, ios, desktop developer can use this for scaffolding system.
( they dont use node usually )
so.. they can install globally yeoman without node command

how to make homebrew package with node package : https://docs.brew.sh/Node-for-Formula-Authors

**Comment by LitoMore** [comment]
Yeoman usually serves Node.js-related things. In most cases, the Node.js runtime should already be installed on your system. I think it's unnecessary to publish it to Homebrew.

And most tools document their usage in this way:

```sh
# VS Code: https://code.visualstudio.com/api/get-started/your-first-extension
npm install -g yo generator-code
```

You can find more packages here: https://www.npmjs.com/search?q=keywords%3Ayeoman-generator&ranking=popularity

**Comment by Anselmoo** [comment]
Fixed in https://github.com/Homebrew/homebrew-core/pull/194374

```shell
brew install yo
```

**Comment by UlisesGascon** [comment]
Thanks @Anselmoo! I will close this issue as seems solved :+1:
