### ISSUE TITLE
Add command line option to pass file with values for all prompts/answers

### ISSUE THREAD

**Issue by baolsen** [yeoman/yo#756]
## Type of issue

Feature request.

For automation purposes eg CI, it would be very useful to be able to optionally pass a file specifying values for prompts and have these used by an arbitrary generator. Perhaps the answers could even be optionally validated.

Currently this can be implemented on specific generators but not generally available.

See this SO post for more detail.
https://stackoverflow.com/questions/72554279/programmically-give-input-to-yeoman-cmd-for-ci-cd-tool

**Comment by mischah** [comment]
Sounds like an existing feature to me:
https://yeoman.io/authoring/storage.html

I used to use a self defined option to make that optional:
https://github.com/micromata/generator-baumeister/blob/master/app/index.js#L20-L69
