### ISSUE TITLE
No sorry

### ISSUE THREAD

**Issue by jntombebe** [yeoman/yo#757]
## Type of issue

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
* *Node version:* `x.x.x` (run `node --version` in your terminal)
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Command line output

```
Paste your error output over here
```
~/C/p/m/create-single-spa $ cd ..
~/C/p/mf $ mkdir gen-test
~/C/p/mf $ cd gen-test
~/C/p/m/gen-test $ ../create-single-spa/packages/create-single-spa/bin/create-single-spa.js

? Select type to generate single-spa application / parcel
? Which framework do you want to use? react
? Which package manager do you want to use? yarn
? Will this project use Typescript? Yes
? Organization name (use lowercase and dashes) op
? Project name (use lowercase and dashes) fe

**Comment by mischah** [comment]
Huh? I don’t get the point of this issue 🤔 
Sorry.
