### ISSUE TITLE
How to generate a vs code extension pack via `yo code`

### ISSUE THREAD

**Issue by ZhaoKunLong** [yeoman/yo#759]
Hello! I just got a `yo code` issue. not sure is `yo` or `code` issue.  Is anyone can help teach me how to resolve it?

## My environment

* *OS version/details*: `mac os Catalina 10.15.7`
* *Node version:* `16.12.0`
* *npm version:* `8.0.1` 
* *Version of yo :* `4.3.0`
* *Version of generator-code:* `1.6.14`

## Expected behavior

I just want to create a vs code extensions pack via `yo code`

## Issues detail

1. I install the pack in global

```sh
npm i -g yo generator-code
```

2. I run it
```sh 
yo code
```

3. then I got the issue. This is the output
```sh

     _-----_     ╭──────────────────────────╮
    |       |    │   Welcome to the Visual  │
    |--(o)--|    │   Studio Code Extension  │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

? What type of extension do you want to create? New Extension Pack
? Add the currently installed extensions to the extension pack? Yes
/Users/.nvm/versions/node/v16.12.0/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:402
    throw error instanceof Error ? error : new Error(error);
    ^

Error: Command failed: code --list-extensions
/bin/sh: code: command not found

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.emit (node:domain:475:12)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 127,
  signal: null,
  cmd: 'code --list-extensions'
}
```

**Comment by mischah** [comment]
It seems that you don’t have the VSCode command line tools installed.

Try to enter in your terminal:
```bash
code --list-extensions
```

This should print your installed VSCode extensions.

**Comment by ZhaoKunLong** [comment]
@mischah  OH! nice. thank you. Find it. I should install the code into the path.
