### ISSUE TITLE
Generator Office does not support the Node LTS 19.8.1

### ISSUE THREAD

**Issue by jezzar042015** [yeoman/yo#792]
## Type of issue
BUG: Does not Support the LTS version of Node

----

## My environment

* *OS*: Windows 11 64-bit
* *Node:* `19.8.1` 
* *npm:* `9.5.1` 
* *yo :* `4.3.1` 

## Expected behavior

Trying to run the office generator

## Current behavior

I cant proceed as the message is asking me to switch to the latest LTS version of Node while I am already on the LTS Version. I already restarted my machine but the problem persist

## Steps to reproduce the behavior

``` 
yo office
```

## Command line output

```
     _-----_     ╭──────────────────────────╮
    |       |    │   generator-office does  │
    |--(o)--|    │ not support your version │
   `---------´   │  of Node. Please switch  │
    ( _´U`_ )    │     to the latest LTS    │
    /___A___\   /│     version of Node.     │
     |  ~  |     ╰──────────────────────────╯
   __'.___.'__
 ´   `  |° ´ Y `
```

## Note
1. `yo webapp` command works
2. I also tried to run the 
`yo doctor`

and this is output

```
Yeoman Doctor
Running sanity checks on your system

√ No .bowerrc file in home directory
√ Global configuration file is valid
√ NODE_PATH matches the npm root
√ No .yo-rc.json file in home directory
√ Node.js version
√ npm version
√ yo version
```

**Comment by UlisesGascon** [comment]
Hi @jezzar042015! 

I believe that this issue should be open directly in the generator repository: https://github.com/OfficeDev/generator-office.

The current Node.js LTS version is 18 and not 19, you can find more details [here](https://github.com/nodejs/release#release-schedule)
