### ISSUE TITLE
pnpm add yo gives unmet peer dependency warning

### ISSUE THREAD

**Issue by LandonSchropp** [yeoman/yo#810]
## Type of issue

🐛 Bug

----

## My environment

* *OS version/details*: macoS 14.4.1 
* *Node version:* v21.4.0
* *pnpm version:* 8.14.0 (the bug is related to pnpm)
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Expected behavior

When installing `yo` in an empty repo, the installation should work without an error or warning.

## Current behavior

Instead, I get a peer dependency warning for `@yeoman/types`:

![Screenshot 2024-05-19 at 11 56 14 AM](https://github.com/yeoman/yo/assets/361591/7e4e761c-fa4f-41f5-9350-a8e510df9fd0)

## Steps to reproduce the behavior

``` shell
mkdir example
cd example
pnpm init
pnpm add yo
```

## Command line output

```
WARN  Issues with peer dependencies found
.
└─┬ @yeoman/types 1.2.0
  └── ✕ unmet peer mem-fs@^3.0.0: found 4.1.0
```

**Comment by mshima** [comment]
See https://github.com/yeoman/generator/issues/1493 and https://github.com/yeoman/generator/issues/1502

**Comment by LandonSchropp** [comment]
Cool, seems like this is already being worked on then. Thanks!

**Comment by mshima** [comment]
I don’t know if pnpm supports acceptDependencies.
You may create an issue in pnpm repo.
