### ISSUE TITLE
Grunt server

### ISSUE THREAD

**Issue by luizrhs** [yeoman/yo#9]
I've run the following commands after installing yo, grunt-cli and bower.

<pre>
npm install generator-angular generator-testacular
yo angular
npm install & bower install
grunt server
</pre>

And I'm getting this error

<pre>
Running "clean:server" (clean) task

Running "coffee:dist" (coffee) task
>> Destination not written because compiled files were empty.

Running "compass:server" (compass) task
Errno::ENOENT on line ["33"] of /home/paulo/.rvm/gems/ruby-1.9.3-p392/gems/compass-0.12.2/lib/compass/exec/global_options_parser.rb: No such file or directory - /components
Run with --trace to see the full backtrace

Running "livereload-start" task
... Starting Livereload server on 35729 ...

Running "connect:livereload" (connect) task
Starting connect web server on localhost:9000.

Running "open:server" (open) task

Running "watch" task
Watching /scripts/*.coffee
Watching test/spec/*.coffee
Watching /styles/*.{scss,sass}
Watching /*.html,/*/*.html,{.tmp,}/styles/*.css,{.tmp,}/scripts/*.js,{.tmp,}/scripts/*/*.js,/images/*.{png,jpg,jpeg}
Fatal error: EACCES, readdir '/lost+found'
</pre>

node -v 0.8.20
npm -v 1.2.10

**Comment by rojarohini** [comment]
we can solve this error by running "grunt server" as "sudo grunt server" if os is ubuntu, open command prompt/ git bash whatever as root/admin then run "grunt server" in windows.
